= Interface
:sectnums:

== Assumptions
* {empty}
+
> The approach taken would be conservative: we want to provide boring and proven infrastructure, so that innovation can be built on top of it.
-- Federico Tomassetti in <<metametamodel.adoc#goals, M3 spec>>

* We want to support several target languages, and want to "fit in" with their style as good as possible.

* All _effective_ member names within a Concept must be unique, as we want to support textual target languages.

== Why interfaces?
* Exist in both MPS and Ecore.
* In combination with derived features, one solution to https://en.wikipedia.org/wiki/Multiple_inheritance#The_diamond_problem[multiple inheritance diamond problem].

If we allowed concrete features in Interfaces, they were no different from Abstract Concepts.
Then we'd rather remove Interfaces from M3 and allow multiple inheritance for Concepts.

== Possible solutions
=== Diamond inheritance problem
[NOTE]
====
As long as we don't have any behavior, diamond inheritance is not a problem.
The problem might be <<name-clashes>>.

<<derived, Derived features>> are behaviors in this sense, as there might be different implementations in the hierarchy.
#TODO is this correct?#
====

.Example M2
[source]
----
concept A
    property id: String

concept B extends A
    // inherits A.id: String

concept C extends A
    // inherits A.id: String

concept D extends B, C
    // inherits B.A.id: String
    // inherits C.A.id: String
----

==== Allow only one concrete implementation in hierarchy
Make sure there's only one concrete implementation present in the hierarchy.
This is mostly achieved by disallowing multiple inheritance, or only allowing abstract members in multiple inheritance.

.Adjusted M2
[source]
----
interface A
    property id: String  [derived]

concept B extends A
    // inherits A.id: String

concept C extends A
    // inherits A.id: String

concept D extends B, C
    // implements B.A.id: String and C.A.id: String
    property id: String
----

Pro::
* Supported by most languages
* Simple to understand

Con::
* Structural effort to guarantee single implementation

==== Serialize hierarchy
Establish a linear order between all concepts, always chose the closest concrete implementation.

.Adjusted M2
(no changes needed)

Pro::
* Cleaner M3

Con::
* Not supported by all languages
* Might be hard to understand which implementation gets picked

==== Explicit selection
User has to explicitly select the concrete implementation in ambiguous cases.

.Adjusted M2
[source]
----
concept A
    property id: String

concept B extends A
    // inherits A.id: String

concept C extends A
    // inherits A.id: String

concept D extends B, C
    id: String from B
----

Pro::
* Cleaner M3
* Seems to get more popular (Java interface default methods, C# interface default methods, Kotlin)

Con::
* Not supported by all languages
* Changing a superclass can break a subclass

=== Diamond inheritance and specializations
(Provided by Alex)

What happens if we specialize the type of a link in diamond inheritance?

.Example M2
[source]
----
concept Place
    containment address: Address[1]

concept PrivatePlace extends Place
    containment homeAddress: PersonalAddress[1]   specializes Place.address

concept CompanyPlace extends Place
    containment factoryAddress: OfficeAddress[1]  specializes Place.address

concept FreelancerPlace extends PrivatePlace, CompanyPlace

concept Address

concept PersonalAddress extends Address

concept OfficeAddress extends Address
----

For `FreelancerPlace`, if we do _not_ "hide" original link (`address`) then it'll be unclear what to put into original `address` link (`PersonalAddress` or `OfficeAddress`).

If we do hide original link then there will be two "independent" links with different names, but internally working with the same original one, so storing instances into the original field.
In this case following code should throw exception:

[source]
----
freelancerPlace.homeAddress = <myHome>;
node<OfficeAddress> officeAddress = freelancerPlace.factoryAddress;
----

[#name-clashes]
=== Name clashes
What to do if we inherit two features with the same name, but different characteristics?

.Example M2
[source]
----
concept G extends E, F
    // inherits E.name: String[1]
    // inherits F.name: String[1]
    // effectively identical

    // inherits E.specialChild: Child[1]
    // inherits F.specialChild: SubChild[1]
    // maybe conflict in type


    // inherits E.child: Child[1]
    // inherits F.child: Child[0..1]
    // conflict in required

    // inherits E.id: String[1]
    // inherits F.id: Integer[1]
    // conflict in type

    // inherits E.target: Target[0..*]
    // inherits F.target: Target[1]
    // conflict in multiple

    // inherits property E.description: String[0..1]
    // inherits containment F.description: Description[0..1]
    // conflict in Feature kind

concept Child

concept SubChild extends Child

concept Target

concept E
    property name: String[1]
    containment specialChild: Child[1]

    containment child: Child[1]
    property id: String[1]
    reference target: Target[0..*]
    property description: String[0..1]

concept F
    property name: String[1]
    containment specialChild: SubChild[1]

    containment child: Child[0..1]
    property id: Integer[1]
    reference target: Target[1]
    containment description: Description[0..1]
----

==== Merge compatible names
If two names are _compatible_, consider them to be identical.
_Compatible_ might mean "equal in all characteristics" (e.g. `E.name` and `F.name`),
or "compatible in all characteristics" (e.g. in Java, an overridden method can have a more specific return type.)
Non-compatible names are invalid.

When defining _compatible_, we need to make sure to fulfil the contracts of the superclasses.
For example, if we considered _required_ characteristics `E.child: Child[1]` and `F.child: Child[0..1]` compatible by rule "stronger wins", we would violate the contract "G is an F, so I can write ``(myG as F).child = null``" (see also <<ex-special-unsound>>).


Pro::
* No additional effort for user
* Proven to work in many languages

Con::
* Might limit possible combinations: If `E` and `F` had very different ideas what to put in field `name` (and only accidentally use compatible features), `G` had to chose which semantics to follow.

[#_rename_conflicting_names]
==== Rename conflicting names
On name clashes, we have to rename all but one of the conflicts.

.Adjusted M2
[source]
----
// other concepts stay the same

concept G extends E, F
    // inherits E.name: String[1]
    // inherits F.name: String[1]
    // effectively identical, no action needed

    rename F.specialChild as specialSubChild
    rename E.child as optionalChild
    rename E.id as fqn
    rename E.target as targets
    rename F.description as complexDescription
----

Pro::
* Solves all possible cases

Con::
* Might be confusing to access the same value under different names:
+
[source]
----
myG.fqn = "a.b.c"
myE: E = myG
println(myE.id) // prints "a.b.c"
----

==== Require qualification
On name clashes, all access to conflicting names need to be qualified.
If the target language does not support this, the LionWeb implementation would auto-rename.

.Usage in language that supports qualified member access
[source]
----
myG.<E>id = "a.b.c"
----

.Usage in language that does not support qualified member access
[source]
----
myG.E_id = "a.b.c"
----

Pro::
* No additional effort for the user
* Keeps similarity between accessing `E.id` and `G.id` (see _con_ of <<_rename_conflicting_names>>)

Con::
* Not supported by many languages
* If we wanted to be absolutely safe with auto-renaming, we would need to use fully qualified names:
+
[source]
----
package a
    concept X
        property name: String[0..1]

package b
    concept X
        property name: String[1]

package c
    concept Y extends a.X, b.X


myY.a_X_id = null
----

==== Disallow conflicts
Inheriting conflicting names is invalid.

Pro::
* Very easy to understand

Con::
* Seriously limits where we can apply inheritance, especially if we cannot change the super-concepts.


[[derived]]
== Why derived features?
Compromise between having arbitrary methods in M3 and supporting non-structural model access.

Example: <<ex-mix-decl-ref>>.

.Context
* <<metametamodel#derived, Description in M3 spec>>
* https://github.com/LionWeb-io/specification/issues/6[How to represent DerivedFeature in M3? #6]

[[specialization]]
== Why specialization?
Simplified approximation of generics.

Example: <<ex-reuse-special>>

.Context
* <<metametamodel#specialization, Description in M3 spec>>
* https://github.com/LionWeb-io/specification/issues/8[Which parts of a link can be specialized? #8]

== Examples

[[ex-set-name]]
=== Set name of all named things
Example by Federico: I want to be able to set the name of all named things.

.M2
[source]
----
interface INamed
    property name: String  [derived]

concept House implements INamed
    property name: String

concept Person implements INamed
    property name: String
----

.Desired usage
[source]
----
namedStuff: list<INamed> = { myHouse, myPerson }
foreach n in namedStuff
    n.name = "(unknown)"
----

[[ex-mix-decl-ref]]
=== Mix declarations and references
Example by Niko: I want to define small shapes inline in `ShapeContainer` and externalize complex shapes, but treat them uniformly.

.M2
[source]
----
interface Shape
    property name: String        [derived]
    reference sides: Side[0..*]  [derived]

concept InlineShape implements Shape
    property name: String
    containment sides: Side[0..*]

concept ExternalShapeRef implements Shape
    property name: String        [derived]
    reference sides: Side[0..*]  [derived]
    // source of derived features
    reference declaration: ComplexStandaloneShape

concept ComplexStandaloneShape implements Shape
    property name: String
    containment sides: Side[0..*]
    // a lot more

concept ShapeContainer
    containment shapes: Shape[0..*]
----

.Desired usage
[source]
----
maxSides: Integer = myShapeContainer.shapes.max(it -> it.sides.count)
----

[[ex-reuse-special]]
=== Reuse through specialization
Example by Niko: I want to reuse the complex logic about dependency resolution for all kinds of containers.
For example, a `House` can only be `nextTo` other houses in the same `HouseContainer` or in house containers mentioned in `HouseContainer.dependsOn`.

.M2
[source]
----
abstract concept Member
    property name: String

abstract concept Container
    reference dependsOn: Container[0..*]  //maybe [derived]
    containment members: Member[0..*]     //maybe [derived]


concept House extends Member
    reference nextTo: House

concept HouseContainer extends Container
    reference dependsOn: HouseContainer[0..*]  specializes Container.dependsOn
    containment houses: House[0..*]            specializes Container.members


concept Person extends Member
    reference parents: Person[0..*]

concept PersonContainer extends Container
    reference dependsOn: PersonContainer[0..*]  specializes Container.dependsOn
    containment persons: Person[0..*]           specializes Container.members
----

.Desired usage
[source]
----
foreach container in allMyContainers
    // generic access to all kind of Containers
    dependencies: list<Container> = container.dependsOn
    resolveComplexDependencies(dependencies)

    concept switch(container.concept)
        is PersonContainer pc
            // pc is known to be of concept PersonContainer, thus having a list of Persons
            somebody: Person = pc.persons.first
        is HouseContainer hc
            homeSweetHomes: list<House> = hc.houses
----

[[ex-special-unsound]]
=== Specialization leads to unsound typesystem
https://github.com/LionWeb-io/specification/issues/8[Example by Sascha]

.M2
[source]
----
concept GreenTreeThing

concept Tree
    containment greenThings: GreenTreeThing[0..*]


conept Needle extends GreenTreeThing

concept NeedleTree extends Tree
    containment needles: Needle[0..*]  specializes Tree.greenThings
----

.Problematic usage
[source]
----
needleTree: NeedleTree = new NeedleTree()
tree: Tree = needleTree
tree.greenThings.add(new GreenTreeThing())
needle: Needle = needleTree.needles.last // ClassCastException: Cannot cast GreenTreeThing to Needle
----