== Models Representations

I am not sure this should be covered here but regarding models the propositions is to have:

Node:: A Node will have a reference to the Concept using to define it.
+
* A Node will have a parent, with the exception of the Model node.
* A Node will be able to return the list of all of its children.
It will be built as the combination of all the values in the containment relations.
It will not include the annotations on the Node.

Model:: A Model will be a particular kind of Node that can have no root.
+
* A Model can hold several top-level Nodes.
* The Model will have a qualified name.
* It will have a list of metamodels used.
The Nodes contained in the model will be allowed to use only the concepts specified by those metamodels.
* A Model will have a list of models imported.
The Nodes contained in the model will be able to have references only to other nodes in the model and to nodes listed in the imports

Metamodel:: A Metamodel will be a particular kind of Model which could hold only metamodel elements.
