= References

[[ref-resolve-null]]
== Meaning and rationale of `null` values for reference id and resolveInfo

Based on{fn-org36-null}

NOTE: We only consider low-level model structure here.
If we had a reference of type `Car`, but the id points to an existing `Wheel`, we would _still_ consider the reference valid on this low level.

In the following matrix, the columns describe _reference_, the rows _resolveInfo_.

reference:

* _valid_ means there it is known that a node with the target id exists.
Undefined whether the targeted node is part of the same model fragment, known locally, or only known to the repository.
* _unknown_ means we don't know whether a node with the target id exists.
* _invalid_ means we know that no node with the target id exists.

resolveInfo:

* _uniquely resolvable_ means that the resolver[1] can find exactly one existing node that could match the given resolve info.
* _ambiguously resolvable_ means that the resolver[1] can find more than one existing node that could match the given resolve info.
* _non-resolvable_ means that the resolver[1] can not find any existing node that could match the given resolve info.

ad [1]: It's currently undefined who the resolver is.
We just assume it can somehow interpret the resolve info, and can return [0..*] valid target nodes.

[%header,cols=">h,<,<,<,<"]
|===
|id &rarr; +
resolveInfo &darr;
^|non-null, valid
^|non-null, unknown
^|non-null, invalid
^|null

|non-null, uniquely resolvable
|happy case
|transient, resolvable
|brittle
|brittle

|non-null, ambiguously resolvable
|mostly happy
|transient
|external selection required
|external selection required

|non-null, non-resolvable
|mostly happy
|transient
|external help required
|external help required

|null
|mostly happy
|transient
|broken
|broken
|===

.Happy case
We know and can reach the target node of the reference.
We also have information how to find the target in case the target is not reachable (e.g. because it has been deleted).

.Transient
We know a target node id, but don't know yet whether that node exists.

.Resolvable
Either through node id or resolveInfo, we're sure we can eventually find our target.

.Brittle
We cannot find the target node by id, but via resolveInfo.
However, resolveInfo might stop working at some point (e.g. if the target gets renamed before resolving the nodeInfo).

.Mostly happy
We know and can reach the target node of the reference.
But we could not re-establish the reference if the target is not reachable (e.g. because the user cuts+pastes the target node, and the pasted one gets a new id).

.External selection required
We don't know the target node.
However, we can present the user with a list of options to chose from.
We populate this list with the potential targets of the resolveInfo.

.External help required
We don't know the target node, and cannot make sense of resolveInfo.
The user might use the resolveInfo to find the actual target.

.Broken
We have no technical way to find the target node, or meaningful ways to support the user to find it.

[NOTE]
====
Instead of the user helping out, we might also infer the same information from language specifics.

Example: Assume a function with only one parameter.
If we had a reference that can only target a parameter, we can infer that target to be the one parameter.
In practice, that means scoping could help us out here (but that's out of scope as of the first remark above).
====