[[client, client]]
=== Client characteristics
A client is a program connecting to a <<repository>>.
Each client has exactly one <<participation>> with one repository at one point in time.
The same client can have several consecutive participations with the same repository, but never at the same time.  +
A client might interact with several repositories, but they are completely independent (i.e. same as two clients connecting to two repositories).{fn-org337}

A client stays up-to-date with the repository's contents if it applies all events in order.{fn-org297}
The order is defined by the event's sequence number.{fn-org341}  +
A client can either decide to apply its own change immediately and filter out events based on that command, or wait for the correlated event to arrive and apply the change only then.

The client has the responsibility to guarantee uniqueness of <<queryIdType, query ids>> and <<commandIdType, command ids>> within the same participation.

Authentication and authorization are out of scope of this API.
