[[repository, repository]]
=== Repository characteristics
A repository is a set of partitions, and a set of APIs, amongst them this delta API.
The repository has an ID that must be unique for all repositories in the same context.
LionWeb doesn't specify the scope of the context.{fn-org401}

A repository is “its own universe”: nodes within it can't reference nodes, or be referenced from nodes from other repositories.
All nodes within the same repository MUST have unique IDs.
Nodes can refer to nodes from the LionCore and built-in languages.

[[repository-contents]]
==== Contents
The repository is always the ultimate arbiter of its contents.{fn-org339}
It can decide to apply each command verbatim, with some tweaks (e.g. because of <<conflict-resolution, concurrent changes>>), or not at all (e.g. because the command would introduce containment loops).

[[conflict-resolution]]
==== Conflict resolution
Each repository might introduce its own strategy how to handle commands.{fn-org291}
For example, assume client 1 sends a `DeleteChild` command to delete node `X`, and then client 2 sends a `SetProperty` command on node `X`.
The repository has to _resolve that conflict_ somehow.

* Repository A applies all commands in order, thus deletes node `X` and ignores the second command, i.e. does not set any property, but attaches both commands' `commandId` to the resulting `ChildDeleted` event.

* Repository B keeps an internal "trash can" of all deleted nodes.
It deletes node `X` on the first command, but resurrects node `X` on the second command and changes the property as requested.
It first emits a `ChildDeleted` event (correlated to the first command), but later `ChildAdded` and `PropertyChanged` events (both correlated to the second command).

* Repository C batches command processing.
It looks at both messages together, and decides it's more important to keep the new property value around.
It emits one `PropertyChanged` event, correlated with both commands.

Conflict resolution might depend on which commands a repository considers to arrive together, i.e. at the same time.
A repository is free to chose its own interpretation of "at the same time".
Examples include "never, every command stands on its own", "sliding window of 10 ms", or "within one processing cycle".
