[[subscription, subscription]]
=== Subscription characteristics
The subscription, or subscription scope, is the set of partitions a <<participation>> gets events for.
A subscription does not have an identity on its own; it is bound to one participation.

Scope is defined by the node id of a <<{m3}.adoc#partition, partition>>; it includes all changes to the partition and all its descendants (including annotation instances).{fn-org269}

At the start of a participation, the subscription scope is empty.
A client can change its subscription scope by

* <<qry-ListAndSubscribePartitions>> for requesting and subscribing to all existing partitions,
* <<qry-InformAboutChangingPartitions>> for being informed about newly created partitions,
* <<qry-SubscribeToChangingPartitions>> for subscribing to newly created partitions,
* <<qry-SubscribeToPartitionContents>> for subscribing to / <<qry-UnsubscribeFromPartitionContents>> for unsubscribing from a specific partition, or
* <<cmd-AddPartition>> for adding a new partition.

A client can change the subscription scope at any time during a participation.
However, a client MUST NOT mix <<qry-InformAboutChangingPartitions>> and <<qry-SubscribeToChangingPartitions>> queries.
If any <<qry-InformAboutChangingPartitions>> query is active, the same client MUST NOT issue a <<qry-SubscribeToChangingPartitions>> query, and vice versa.
Once all <<qry-InformAboutChangingPartitions>> are disabled (i.e. both <<InformAboutChangingPartitions.creation>> and <<InformAboutChangingPartitions.deletion>> are `false`), the client MAY issue a <<qry-SubscribeToChangingPartitions>> query.{fn-org438}

A client CAN send commands for any node id, independent of the client's subscription.
Assume a client sends a command for a node that's part of a partition that client is not subscribed to.
The repository treats that command the same as from a client that was subscribed to the containing partition, i.e. applies it in accordance with the repository's policy.
The repository sends out the same events to subscribed clients, and _also_ to the sending client.{fn-org352}

This means a client:

* _always_ gets the events for its own commands, event if it relates to a node outside the client's subscription scope.
* _can_ get an event it didn't subscribe to, if the event originates in the client's own command.

[[compositeEvents, composite events]]
==== Composite events
For a <<evnt-CompositeEvent, composite event>>, arising from a <<cmd-CompositeCommand, composite command>>, the following MUST hold:

* Every client gets a composite event with only the events it's subscribed to.
* No client gets an empty composite event.
* The client that sent the composite command always gets the complete composite event, modulo repo changes, e.g. conflict resolutions.
