include::../shared/issue-footnotes.adoc[]

:m3: metametamodel/metametamodel
:serialization: serialization/serialization
:bulk: bulk/repo-access-api

:emquad: &#x2001;

= LionWeb Version 2024.1

Stable xref:{serialization}.adoc[serialization format] (including JSON schema)
and xref:{m3}.adoc[meta-metamodel] describing
xref:{m3}.adoc#Language[Languages],
xref:{m3}.adoc#Concept[Concepts],
xref:{m3}.adoc#Interface[Interfaces],
xref:{m3}.adoc#Annotation[Annotations],
xref:{m3}.adoc#Enumeration[Enumerations],
xref:{m3}.adoc#PrimitiveType[PrimitiveTypes],
xref:{m3}.adoc#Property[Properties],
xref:{m3}.adoc#Containment[Containments],
and xref:{m3}.adoc#Reference[References].

The standard library contains classifiers xref:{m3}.adoc#Node[Node]
and xref:{m3}.adoc#INamed[INamed],
and primitive types xref:{m3}.adoc#Boolean[Boolean],
xref:{m3}.adoc#String[String],
xref:{m3}.adoc#Integer[Integer]

== Contents

* Serialization format{emquad}xref:{serialization}.adoc[html]{emquad}link:{serialization}.pdf[pdf]

* Meta-metamodel{emquad}xref:{m3}.adoc[html]{emquad}link:{m3}.pdf[pdf]

* Bulk Repository Access API{emquad}xref:{bulk}.adoc[html]{emquad}link:{bulk}.pdf[pdf]

== Known issues

=== M3 (lioncore.json) Mismatched child vs. node id

Details: lioncore.json: Mismatched child vs. node id `-id-Classifier-features-2024-1` https://github.com/LionWeb-io/specification/issues/412[#412]

xref:metametamodel/lioncore.json[lioncore.json] line 1484 mentions id `-id-Classifier-features-2024-1` as child.

[%linenums,json,highlight=1484,start=1476,indent=0]
----
include::metametamodel/lioncore.json[lines=1476..1487]
----

However, the intended child node id in line 1515 spells `-id-Classifier-feature-2024-1` (singular "feature").

[%linenums,json,highlight=1515,start=1514,indent=0]
----
include::metametamodel/lioncore.json[lines=1514..1520]
----

They both MUST be the same, i.e. `-id-Classifier-features-2024-1`.