[[errors-create-node]]
==== Create node errors

Reported by all <<group-create-node>> commands.

[[err-invalidAnchorNode]]
===== Invalid anchor node
A <<singleChunkType>> doesn't have exactly one <<anchorNode>>, or the anchor node's id or parent is invalid.

.Technical name
`invalidAnchorNode`


[[err-nodeAlreadyExists]]
===== Node already exists
Client tries to create a node with an id that already exists.

.Technical name
`nodeAlreadyExists`

.Additional infos
[horizontal]
[[nodeAlreadyExists.duplicate]]duplicate:: <<nodeIdType>>
of the already existing node.


[[err-parentContainmentMismatch]]
===== Parent / containment mismatch
A parent node `P` has a child (containment or annotation) node `C`, but `C` doesn't mention `P` as parent.

.Technical name
`parentContainmentMismatch`

.Additional infos
[horizontal]
[[parentContainmentMismatch.parent]]parent:: <<nodeIdType>>
of the parent node.
[[parentContainmentMismatch.child]]child:: <<nodeIdType>>
of the child node.
[[parentContainmentMismatch.parentId]]parentId:: <<nodeIdType>>
of the parent mentioned in the child.
[[parentContainmentMismatch.parameter]]parameter:: <<parameterType>>
Name of the parameter containing <<parentContainmentMismatch.child>>.


[[err-circularContainment]]
===== Circular containment
A parent node `P` contains a child (containment or annotation) node `C`, that directly or indirectly contains `P`.
Includes the edge case `P` contains `P`.

.Additional infos
[horizontal]
[[circularContainment.cycle]]cycle:: <<nodeIdType>>[]
Comma-separated list of all node ids that are part of the containment cycle.
MUST NOT contain any whitespace.

.Technical name
`circularContainment`
