[[errors-generic]]
==== Generic errors


[[err-invalidParticipation]]
===== Invalid participation
The <<participation>> the <<client>> uses to communicate with the repository is not valid.

Possible reasons:

* The participation never has been valid.
* The client <<qry-SignOff, signed off>>.
* The client <<participation, disconnected>>.

.Technical name
`invalidParticipation`

##TODO##: Do we have a separate "connection state" when the connection is technically established, but the client is not yet signed in?


[[err-messageSyntaxIncorrect]]
===== Message syntax incorrect
The delta message does not adhere to the syntax defined by this specification.

.Technical name
`messageSyntaxIncorrect`


[[err-messageKindUnknown]]
===== Message kind unknown
The repository does not recognize the message.

See also <<customMessages>>.

.Technical name
`messageKindUnknown`


[[err-missingRequiredMessageParameter]]
===== Missing required message parameter
A <<queries, query response>> or <<commands, command>> is missing a required parameter.

.Technical name
`missingRequiredMessageParameter`

.Additional infos
[horizontal]
[[missingRequiredMessageParameter.parameter]]parameter:: <<parameterType>>
Name of the missing parameter.


[[err-unknownNode]]
===== Unknown node
Client tries to operate on a node unknown to the repository.

See also <<errors-move>>.

.Technical name
`unknownNode`

.Additional infos
[horizontal]
[[unknownNode.node]]node:: <<nodeIdType>>
of the unknown node.
[[unknownNode.parameter]]parameter:: <<parameterType>>
Name of the parameter containing <<unknownNode.node>>.


[[err-unknownIndex]]
===== Unknown index
Client tries to operate on an index beyond the number of existing elements.

See also <<errors-move>>.

.Technical name
`unknownIndex`

.Additional infos
[horizontal]
[[unknownIndex.parent]]parent:: <<nodeIdType>>
of the parent containing the feature with unknown index.
[[unknownIndex.feature]]feature:: <<serializedMetaPointerType>>
of the feature with unknown index.
[[unknownIndex.size]]size:: <<indexType>>
The actual size of the feature.
[[unknownIndex.index]]index:: <<indexType>>
Unknown index.
[[unknownIndex.parameter]]parameter:: <<parameterType>>
Name of the parameter containing <<unknownIndex.index>>.


[[err-unknownProperty]]
===== Unknown property
Client tries to change or delete a property not present in the parent node.

.Technical name
`unknownProperty`

.Additional infos
[horizontal]
[[unknownProperty.parent]]parent:: <<nodeIdType>>
of the parent missing the requested property.
[[unknownProperty.property]]property:: <<serializedMetaPointerType>>
of the requested <<{m3}.adoc#Property, Property>>.


[[err-unknownReference]]
===== Unknown reference
Client tries to change or delete a reference not present in the parent node.

.Technical name
`unknownReference`

.Additional infos
[horizontal]
[[unknownReference.parent]]parent:: <<nodeIdType>>
of the parent missing the requested property.
[[unknownReference.reference]]reference:: <<serializedMetaPointerType>>
of the requested <<{m3}.adoc#Reference, Reference>>.


[[err-unknownContainment]]
===== Unknown containment
Client tries to change or delete a containment not present in the parent node.

.Technical name
`unknownContainment`

.Additional infos
[horizontal]
[[unknownContainment.parent]]parent:: <<nodeIdType>>
of the parent missing the requested property.
[[unknownContainment.containment]]containment:: <<serializedMetaPointerType>>
of the requested <<{m3}.adoc#Containment, Containment>>.


[[err-featureAlreadySet]]
===== Feature already set
A <<{m3}.adoc#Feature, Feature>> has already been set to a value, and cannot be set new with this command.
Use a <<group-value-change>> or <<group-node-replace>> command instead.

.Technical name
`featureAlreadySet`

.Additional infos
[horizontal]
[[featureAlreadySet.parent]]parent:: <<nodeIdType>>
of the parent containing the already set feature.
[[featureAlreadySet.feature]]feature:: <<serializedMetaPointerType>>
of the already set feature.
[[featureAlreadySet.value]]value:: <<featureValueType>>
Current value of the feature.


[[err-featureNotSet]]
===== Feature not set
A <<{m3}.adoc#Feature, Feature>> has no value, and cannot be changed with this command.
Use an <<group-value-add>> or <<group-node-replace>> command instead.

.Technical name
`featureNotSet`

.Additional infos
[horizontal]
[[featureNotSet.parent]]parent:: <<nodeIdType>>
of the parent containing the unset feature.
[[featureNotSet.feature]]feature:: <<serializedMetaPointerType>>
of the unset feature.