[[evnt-ChildMovedAndReplacedInSameContainment]]
[[evnt-ChildMovedAndReplacedInSameContainmentInSameParent]]
===== Child moved in same containment in same parent and replaced existing child
<<existing-nodes, Existing node>> <<ChildMovedAndReplacedInSameContainmentInSameParent.movedChild>>
that was initially at index <<ChildMovedAndReplacedInSameContainmentInSameParent.oldIndex>>
within the <<ChildMovedAndReplacedInSameContainmentInSameParent.containment>> inside <<ChildMovedAndReplacedInSameContainmentInSameParent.parent>>
was moved by <<ChildMovedAndReplacedInSameContainmentInSameParent.indexOffset>> positions
to index (<<ChildMovedAndReplacedInSameContainmentInSameParent.oldIndex>> + <<ChildMovedAndReplacedInSameContainmentInSameParent.indexOffset>>),
replacing <<existing-nodes, current child>> <<ChildMovedAndReplacedInSameContainmentInSameParent.replacedChild>>{fn-org371} at the target index.{fn-org469}
<<ChildMovedAndReplacedInSameContainmentInSameParent.replacedChild>> subsequently gets deleted, including all its descendants (including annotation instances).
This does NOT change references to any of the deleted nodes.{fn-org285}

This conforms to <<movingAndReplacingNodes, the action of moving a node and replacing another one in one specific list>> — see that section for more information, diagrams, and examples.

.Technical name
`ChildMovedAndReplacedInSameContainmentInSameParent`{fn-org514}

[horizontal]
.Parameters
[[ChildMovedAndReplacedInSameContainmentInSameParent.parent, `parent`]]parent:: <<nodeIdType>>
of the node the child was moved in.

[[ChildMovedAndReplacedInSameContainmentInSameParent.containment, `containment`]]containment:: <<metaPointerType>>
<<{m3}.adoc#Containment, Containment>> <<ChildMovedAndReplacedInSameContainmentInSameParent.movedChild>> was moved and <<ChildMovedAndReplacedInSameContainmentInSameParent.replacedChild>> was replaced in <<ChildMovedAndReplacedInSameContainmentInSameParent.parent>>.

[[ChildMovedAndReplacedInSameContainmentInSameParent.oldIndex, `oldIndex`]]oldIndex:: <<indexType>>
where <<ChildMovedAndReplacedInSameContainmentInSameParent.movedChild>> was moved from in <<ChildMovedAndReplacedInSameContainmentInSameParent.containment>> of <<ChildMovedAndReplacedInSameContainmentInSameParent.parent>>.

[[ChildMovedAndReplacedInSameContainmentInSameParent.indexOffset, `indexOffset`]]indexOffset:: <<indexOffsetType>>
how much <<ChildMovedAndReplacedInSameContainmentInSameParent.movedChild>> was moved in <<ChildMovedAndReplacedInSameContainmentInSameParent.containment>> of <<ChildMovedAndReplacedInSameContainmentInSameParent.parent>>.
+
(<<ChildMovedAndReplacedInSameContainmentInSameParent.oldIndex>> + <<ChildMovedAndReplacedInSameContainmentInSameParent.indexOffset>>)
MUST NOT be < 0,
or >= (the number of children inside <<ChildMovedAndReplacedInSameContainmentInSameParent.parent>>'s <<ChildMovedAndReplacedInSameContainmentInSameParent.containment>>).

[[ChildMovedAndReplacedInSameContainmentInSameParent.movedChild, `movedChild`]]movedChild:: <<nodeIdType>>
of the node that was moved in <<ChildMovedAndReplacedInSameContainmentInSameParent.containment>> in <<ChildMovedAndReplacedInSameContainmentInSameParent.parent>>.

[[ChildMovedAndReplacedInSameContainmentInSameParent.replacedChild, `replacedChild`]]replacedChild:: <<nodeIdType>>
of the node that was replaced in <<ChildMovedAndReplacedInSameContainmentInSameParent.containment>> in <<ChildMovedAndReplacedInSameContainmentInSameParent.parent>>.

[[ChildMovedAndReplacedInSameContainmentInSameParent.replacedDescendants, `replacedDescendants`]]replacedDescendants:: <<nodeIdType>>[]
List of all node ids that used to be descendants (including children and annotations) of <<ChildMovedAndReplacedInSameContainmentInSameParent.replacedChild>>.
Does not include <<ChildMovedAndReplacedInSameContainmentInSameParent.replacedChild>>.

[[ChildMovedAndReplacedInSameContainmentInSameParent.originCommands]]originCommands:: <<commandSourceType>>[]
List of `(participationId, commandId)` pairs this event is based on.

[[ChildMovedAndReplacedInSameContainmentInSameParent.sequenceNumber]]sequenceNumber:: <<eventSequenceType>>
Event sequence number of this event.

[[ChildMovedAndReplacedInSameContainmentInSameParent.additionalInfos]]additionalInfos:: <<additionalInfosType>>
Optionally empty list of <<additionalInfo>>s.

.Related command
<<cmd-MoveAndReplaceChildInSameContainmentInSameParent>>
