[[evnt-ChildMovedAndReplacedFromOtherContainment]]
[[evnt-ChildMovedAndReplacedFromContainmentInOtherParent]]
===== Child moved from containment in other parent and replaced existing child
<<existing-nodes, Existing node>> <<ChildMovedAndReplacedFromContainmentInOtherParent.movedChild>> (previously inside <<ChildMovedAndReplacedFromContainmentInOtherParent.oldParent>>'s <<ChildMovedAndReplacedFromContainmentInOtherParent.oldContainment>> at <<ChildMovedAndReplacedFromContainmentInOtherParent.oldIndex>>) has replaced the <<existing-nodes, existing>> <<ChildMovedAndReplacedFromContainmentInOtherParent.replacedChild>> inside <<ChildMovedAndReplacedFromContainmentInOtherParent.newParent>>'s <<ChildMovedAndReplacedFromContainmentInOtherParent.newContainment>> at <<ChildMovedAndReplacedFromContainmentInOtherParent.newIndex>>.
<<ChildMovedAndReplacedFromContainmentInOtherParent.replacedChild>>, and all its <<ChildMovedAndReplacedFromContainmentInOtherParent.replacedDescendants>>{fn-org370}, have been deleted.

All other children inside <<ChildMovedAndReplacedFromContainmentInOtherParent.oldParent>>'s <<ChildMovedAndReplacedFromContainmentInOtherParent.oldContainment>> with index > <<ChildMovedAndReplacedFromContainmentInOtherParent.oldIndex>> have been moved to next lower index.

No other children inside <<ChildMovedAndReplacedFromContainmentInOtherParent.newParent>>'s <<ChildMovedAndReplacedFromContainmentInOtherParent.newContainment>> have been moved.

.Technical name
`ChildMovedAndReplacedFromContainmentInOtherParent`{fn-org513}

[horizontal]
.Parameters
[[ChildMovedAndReplacedFromContainmentInOtherParent.newParent, `newParent`]]newParent:: <<nodeIdType>>
of the node <<ChildMovedAndReplacedFromContainmentInOtherParent.movedChild>> was moved to.

[[ChildMovedAndReplacedFromContainmentInOtherParent.newContainment, `newContainment`]]newContainment:: <<metaPointerType>>
<<{m3}.adoc#Containment, Containment>> <<ChildMovedAndReplacedFromContainmentInOtherParent.movedChild>> was moved to in <<ChildMovedAndReplacedFromContainmentInOtherParent.newParent>>.

[[ChildMovedAndReplacedFromContainmentInOtherParent.newIndex, `newIndex`]]newIndex:: <<indexType>>
where <<ChildMovedAndReplacedFromContainmentInOtherParent.movedChild>> was moved to in <<ChildMovedAndReplacedFromContainmentInOtherParent.newContainment>> of <<ChildMovedAndReplacedFromContainmentInOtherParent.newParent>>.

[[ChildMovedAndReplacedFromContainmentInOtherParent.movedChild, `movedChild`]]movedChild:: <<nodeIdType>>
of the node that was moved from <<ChildMovedAndReplacedFromContainmentInOtherParent.oldContainment>> in <<ChildMovedAndReplacedFromContainmentInOtherParent.oldParent>> to <<ChildMovedAndReplacedFromContainmentInOtherParent.newContainment>> in <<ChildMovedAndReplacedFromContainmentInOtherParent.newParent>>.

[[ChildMovedAndReplacedFromContainmentInOtherParent.oldParent, `oldParent`]]oldParent:: <<nodeIdType>>
of the node <<ChildMovedAndReplacedFromContainmentInOtherParent.movedChild>> was moved from.

[[ChildMovedAndReplacedFromContainmentInOtherParent.oldContainment, `oldContainment`]]oldContainment:: <<metaPointerType>>
<<{m3}.adoc#Containment, Containment>> <<ChildMovedAndReplacedFromContainmentInOtherParent.movedChild>> was moved from in <<ChildMovedAndReplacedFromContainmentInOtherParent.oldParent>>.

[[ChildMovedAndReplacedFromContainmentInOtherParent.oldIndex, `oldIndex`]]oldIndex:: <<indexType>>
where <<ChildMovedAndReplacedFromContainmentInOtherParent.movedChild>> was moved from in <<ChildMovedAndReplacedFromContainmentInOtherParent.oldContainment>> of <<ChildMovedAndReplacedFromContainmentInOtherParent.oldParent>>.

[[ChildMovedAndReplacedFromContainmentInOtherParent.replacedChild, `replacedChild`]]replacedChild:: <<nodeIdType>>
of the node that was replaced at <<ChildMovedAndReplacedFromContainmentInOtherParent.newIndex>> of <<ChildMovedAndReplacedFromContainmentInOtherParent.newContainment>> in <<ChildMovedAndReplacedFromContainmentInOtherParent.newParent>>.

[[ChildMovedAndReplacedFromContainmentInOtherParent.replacedDescendants, `replacedDescendants`]]replacedDescendants:: <<nodeIdType>>[]
List of all node ids that used to be descendants (including children and annotations) of <<ChildMovedAndReplacedFromContainmentInOtherParent.replacedChild>>.
Does not include <<ChildMovedAndReplacedFromContainmentInOtherParent.replacedChild>>.

[[ChildMovedAndReplacedFromContainmentInOtherParent.originCommands]]originCommands:: <<commandSourceType>>[]
List of `(participationId, commandId)` pairs this event is based on.

[[ChildMovedAndReplacedFromContainmentInOtherParent.sequenceNumber]]sequenceNumber:: <<eventSequenceType>>
Event sequence number of this event.

[[ChildMovedAndReplacedFromContainmentInOtherParent.additionalInfos]]additionalInfos:: <<additionalInfosType>>
Optionally empty list of <<additionalInfo>>s.

.Related command
<<cmd-MoveAndReplaceChildFromContainmentInOtherParent>>
