[[evnt-AnnotationMovedAndReplacedInSameParent]]
===== Annotation moved in same parent and replaced existing annotation
<<existing-nodes, Existing node>> <<AnnotationMovedAndReplacedInSameParent.movedAnnotation>>
that was initially at index <<AnnotationMovedAndReplacedInSameParent.oldIndex>>
in <<AnnotationMovedAndReplacedInSameParent.parent>>'s annotations
was moved by <<AnnotationMovedAndReplacedInSameParent.indexOffset>> positions
to index (<<AnnotationMovedAndReplacedInSameParent.oldIndex>> + <<AnnotationMovedAndReplacedInSameParent.indexOffset>>),
replacing <<existing-nodes, current node>> <<AnnotationMovedAndReplacedInSameParent.replacedAnnotation>>{fn-org371}.
This deletes <<AnnotationMovedAndReplacedInSameParent.replacedAnnotation>>, and all its descendants (including annotation instances).
Does NOT change references to any of the deleted nodes.{fn-org285}

This conforms to <<movingAndReplacingNodes, the action of moving a node and replacing another one in one specific list>> — see that section for more information, diagrams, and examples.

.Technical name
`AnnotationMovedAndReplacedInSameParent`

[horizontal]
.Parameters
[[AnnotationMovedAndReplacedInSameParent.parent, `parent`]]parent:: <<nodeIdType>>
of the node the annotation was moved in.

[[AnnotationMovedAndReplacedInSameParent.oldIndex, `oldIndex`]]oldIndex:: <<nodeIdType>>
where <<AnnotationMovedAndReplacedInSameParent.movedAnnotation>> was moved from in annotations of <<AnnotationMovedAndReplacedInSameParent.parent>>.

[[AnnotationMovedAndReplacedInSameParent.indexOffset, `indexOffset`]]indexOffset:: <<indexOffsetType>>
how much <<AnnotationMovedAndReplacedInSameParent.movedAnnotation>> was moved in annotations of <<AnnotationMovedAndReplacedInSameParent.parent>>.

[[AnnotationMovedAndReplacedInSameParent.movedAnnotation, `movedAnnotation`]]movedAnnotation:: <<nodeIdType>>
of the node that was moved in annotations in <<AnnotationMovedAndReplacedInSameParent.parent>>.

[[AnnotationMovedAndReplacedInSameParent.replacedAnnotation, `replacedAnnotation`]]replacedAnnotation:: <<nodeIdType>>
of the node that was replaced in annotations in <<AnnotationMovedAndReplacedInSameParent.parent>>.

[[AnnotationMovedAndReplacedInSameParent.replacedDescendants, `replacedDescendants`]]replacedDescendants:: <<nodeIdType>>[]
List of all node ids that used to be descendants (including children and annotations) of <<AnnotationMovedAndReplacedInSameParent.replacedAnnotation>>.
Does not include <<AnnotationMovedAndReplacedInSameParent.replacedAnnotation>>.

[[AnnotationMovedAndReplacedInSameParent.originCommands]]originCommands:: <<commandSourceType>>[]
List of `(participationId, commandId)` pairs this event is based on.

[[AnnotationMovedAndReplacedInSameParent.sequenceNumber]]sequenceNumber:: <<eventSequenceType>>
Event sequence number of this event.

[[AnnotationMovedAndReplacedInSameParent.additionalInfos]]additionalInfos:: <<additionalInfosType>>
Optionally empty list of <<additionalInfo>>s.

.Related command
<<cmd-MoveAndReplaceAnnotationInSameParent>>
