[[participation, participation]]
=== Participation characteristics
Each participation has a _[[participation-id, participation id]]participation id_, unique for all concurrent participations.
The repository assigns the participation id upon starting a new participation.
The participation id MUST follow the same format as <<{m3}.adoc#identifiers, identifier>>.
It serves as a technical identifier.

A participation is transparent for reconnecting network connections,i.e. one participation can survive potential technical reconnects.
A participation spans over time: if we would e.g. used REST, a participation spans over several REST requests/responses.

A participation <<qry-SignOn, starts>> by the client connecting to the repository via delta protocol.
A participation ends either by the <<qry-SignOff, client ending>> it, or if the client disconnects involuntarily (e.g. by crashing or a connection failure).

A client can try to <<qry-Reconnect, reconnect>> a participation if the client still knows a previously valid participation id, and the last <<event-sequence-number>> the client received.{fn-org349}
