[[cmd-MoveAndReplaceAnnotationInSameParent]]
===== Move annotation in same parent and replace existing annotation
Move <<existing-nodes, existing node>> <<MoveAnnotationInSameParent.movedAnnotation>>
that’s initially at index <<MoveAnnotationInSameParent.oldIndex>>
in <<MoveAnnotationInSameParent.parent>>'s annotations
by <<MoveAnnotationInSameParent.indexOffset>> positions
to index (<<MoveAnnotationInSameParent.oldIndex>> + <<MoveAnnotationInSameParent.indexOffset>>),
replacing <<existing-nodes, current node>> <<MoveAndReplaceAnnotationInSameParent.replacedAnnotation>>{fn-org371}.
This deletes <<MoveAndReplaceAnnotationInSameParent.replacedAnnotation>>, and all its descendants (including annotation instances).
Does NOT change references to any of the deleted nodes.{fn-org285}

This conforms to <<movingAndReplacingNodes, the action of moving a node and replacing another one in one specific list>> — see that section for more information, diagrams, and examples.

.Technical name
`MoveAndReplaceAnnotationInSameParent`

[horizontal]
.Parameters
[[MoveAndReplaceAnnotationInSameParent.parent, `parent`]]parent:: <<targetNodeType>>

[[MoveAndReplaceAnnotationInSameParent.oldIndex, `oldIndex`]]oldIndex:: <<targetNodeType>>

[[MoveAndReplaceAnnotationInSameParent.indexOffset, `indexOffset`]]indexOffset:: <<indexOffsetType>>
MUST NOT be 0.

[[MoveAndReplaceAnnotationInSameParent.movedAnnotation, `movedAnnotation`]]movedAnnotation:: <<targetNodeType>>

[[MoveAndReplaceAnnotationInSameParent.replacedAnnotation, `replacedAnnotation`]]replacedAnnotation:: <<targetNodeType>>

[[MoveAndReplaceAnnotationInSameParent.commandId]]commandId:: <<commandIdType>>

[[MoveAndReplaceAnnotationInSameParent.additionalInfos]]additionalInfos:: <<additionalInfosType>>

.Errors
* <<err-unknownNode>> for <<MoveAndReplaceAnnotationInSameParent.parent>>
* <<err-unknownIndex>> for <<MoveAndReplaceAnnotationInSameParent.oldIndex>>
is not an integer in the set [0..(the number of annotations on <<MoveAndReplaceAnnotationInSameParent.parent>> - 1)] — see <<integerRangeNotation>> for an explanation of the [`left`..`right`] notation
* <<err-invalidIndexOffset>> for <<MoveAndReplaceAnnotationInSameParent.indexOffset>>
if <<MoveAndReplaceAnnotationInSameParent.indexOffset>> equals 0, or if (<<MoveAndReplaceAnnotationInSameParent.oldIndex>> + <<MoveAndReplaceAnnotationInSameParent.indexOffset>>) is not in the set [0..(the number of annotations on <<MoveAnnotationInSameParent.parent>> - 1)]
* <<err-unknownNode>> for <<MoveAndReplaceAnnotationInSameParent.movedAnnotation>>
* <<err-indexEntryMismatch>> for <<MoveAndReplaceAnnotationInSameParent.oldIndex>> and <<MoveAndReplaceAnnotationInSameParent.movedAnnotation>>
if <<MoveAndReplaceAnnotationInSameParent.movedAnnotation>> is not at index <<MoveAndReplaceAnnotationInSameParent.oldIndex>> in the annotations on <<MoveAndReplaceAnnotationInSameParent.parent>>
* <<err-parentMismatch>> <<MoveAndReplaceAnnotationInSameParent.parent>>
is not the parent of <<MoveAndReplaceAnnotationInSameParent.movedAnnotation>>
* <<err-moveWithoutParent>> for <<MoveAndReplaceAnnotationInSameParent.movedAnnotation>>
* <<err-unknownNode>> for <<MoveAndReplaceAnnotationInSameParent.replacedAnnotation>>
* <<err-indexEntryMismatch>> for <<MoveAndReplaceAnnotationInSameParent.oldIndex>>/<<MoveAndReplaceAnnotationInSameParent.indexOffset>> and <<MoveAndReplaceAnnotationInSameParent.replacedAnnotation>>
if <<MoveAndReplaceAnnotationInSameParent.replacedAnnotation>> is not at index (<<MoveAndReplaceAnnotationInSameParent.oldIndex>> + <<MoveAndReplaceAnnotationInSameParent.indexOffset>>) in the annotations on <<MoveAndReplaceAnnotationInSameParent.parent>>
* <<err-parentMismatch>> <<MoveAndReplaceAnnotationInSameParent.parent>> is not the parent of <<MoveAndReplaceAnnotationInSameParent.replacedAnnotation>>
* <<err-moveWithoutParent>> for <<MoveAndReplaceAnnotationInSameParent.replacedAnnotation>>
* <<err-invalidParticipation>>

.Related event
<<evnt-AnnotationMovedAndReplacedInSameParent>>
