include::../shared/issue-footnotes.adoc[]

:m3: metametamodel/metametamodel
:serialization: serialization/serialization

:emquad: &#x2001;

= LionWeb Version 2023.1

Stable xref:{serialization}.adoc[serialization format] (including JSON schema)
and xref:{m3}.adoc[meta-metamodel] describing
xref:{m3}.adoc#Language[Languages],
xref:{m3}.adoc#Concept[Concepts],
xref:{m3}.adoc#Interface[Interfaces],
xref:{m3}.adoc#Annotation[Annotations],
xref:{m3}.adoc#Enumeration[Enumerations],
xref:{m3}.adoc#PrimitiveType[PrimitiveTypes],
xref:{m3}.adoc#Property[Properties],
xref:{m3}.adoc#Containment[Containments],
and xref:{m3}.adoc#Reference[References].

The standard library contains classifiers xref:{m3}.adoc#Node[Node]
and xref:{m3}.adoc#INamed[INamed],
and primitive types xref:{m3}.adoc#Boolean[Boolean],
xref:{m3}.adoc#String[String],
xref:{m3}.adoc#Integer[Integer],
and xref:{m3}.adoc#JSON[JSON].

== Contents

* Serialization format{emquad}xref:{serialization}.adoc[html]{emquad}link:metametamodel/metametamodel.pdf[pdf]

* Meta-metamodel{emquad}xref:{m3}.adoc[html]{emquad}link:serialization/serialization.pdf[pdf]

== Example implementations

* Java
  {emquad}https://github.com/LionWeb-io/lionweb-java/releases/tag/0.2.1[repo]
** Core
   {emquad}https://mvnrepository.com/artifact/io.lionweb.lionweb-java/lionweb-java-2023.1-core[Maven]
** EMF
   {emquad}https://mvnrepository.com/artifact/io.lionweb.lionweb-java/lionweb-java-2023.1-emf[Maven]
** EMF Builtins (required by EMF)
   {emquad}https://mvnrepository.com/artifact/io.lionweb.lionweb-java/lionweb-java-2023.1-emf-builtins[Maven]

* MPS
** MPS 2021.1
   {emquad}https://github.com/LionWeb-io/lionweb-mps/releases/tag/2021.1-lw2023.1-0.2.1[repo]
   {emquad}https://mvnrepository.com/artifact/io.lionweb.lionweb-mps/lionweb-mps-2021.1-lw2023.1[Maven]
** MPS 2021.2
   {emquad}https://github.com/LionWeb-io/lionweb-mps/releases/tag/2021.2-lw2023.1-0.2.1[repo]
   {emquad}https://mvnrepository.com/artifact/io.lionweb.lionweb-mps/lionweb-mps-2021.2-lw2023.1[Maven]
** MPS 2021.3
   {emquad}https://github.com/LionWeb-io/lionweb-mps/releases/tag/2021.3-lw2023.1-0.2.1[repo]
   {emquad}https://mvnrepository.com/artifact/io.lionweb.lionweb-mps/lionweb-mps-2021.3-lw2023.1[Maven]

* TypeScript
  {emquad}https://github.com/LionWeb-io/lionweb-typescript[repo]
  {emquad}https://www.npmjs.com/org/lionweb[NPM org with 4 packages]

* Freon
  {emquad}https://github.com/LionWeb-io/lioncore-freon[repo]
  {emquad}npm

== Example usages

* PROPS Properties Language
  {emquad}https://github.com/LionWeb-io/property-demo/releases/tag/LangDev2023[repo]
