@startuml
hide empty members
hide circles

skinparam class<<h>> {
  borderColor Transparent
  backgroundColor Transparent
  stereotypeFontColor Transparent
}

skinparam package<<h>> {
  borderColor Transparent
  backgroundColor Transparent
  fontColor Transparent
  stereotypeFontColor Transparent
}
@enduml