=== Client changes known node with local update
[plantuml,changeKnownNodeLocalUpdate,svg]
----
hide footbox
autonumber

box "Client A"
  participant Editor as editor
  participant Events as clientEvent
  participant Commands as clientCmd
end box

box "Repository"
  participant Commands as repoCmd
  participant Events as repoEvent
  participant Core as core
end box

== Client A connected with participation id "client-a"\nsubscribed to "partition-id"\nknows about nodeA (part of "partition-id") ==

[->> editor ++
editor -> editor: update(nodeA.age = 23)
editor ->> clientCmd
deactivate editor
activate clientCmd
clientCmd -> repoCmd ++: addProperty("nodeA", age, "23", "cmd-1")

repoCmd ->> core
activate core
clientCmd <-- repoCmd: received("cmd-1")
deactivate repoCmd

clientCmd -> clientEvent: registerProcessedCmd("cmd-1")
activate clientEvent
deactivate clientCmd
deactivate clientEvent

core -> core: update()

core -> repoEvent
deactivate core

activate repoEvent
clientEvent <<- repoEvent: propertyAdded("nodeA", age, "23", [("client-a", "cmd-1")], 1)
deactivate repoEvent

activate clientEvent
clientEvent -> clientEvent: checkForProcessedCmd()
clientEvent -> clientEvent: removeProcessedCmd("cmd-1")
deactivate clientEvent

core <<-]: addProperty(..., "cmd-x")
activate core
core -> core: update()

core -> repoEvent
deactivate core

activate repoEvent
clientEvent <<- repoEvent: propertyAdded(... [("other-client", "cmd-x")], 2)
deactivate repoEvent

activate clientEvent
clientEvent -> clientEvent: checkForProcessedCmd()
clientEvent -> editor
deactivate clientEvent

activate editor
editor -> editor: update()
----
1. User enters new property value.
2. Client updates `nodeA` with new property value.
3. Client editor forwards user action into command.
4. Client sends <<cmd-AddProperty>> command with `nodeA` node id, `age` property (details omitted), `23` value and command id `cmd-1`.
5. Repository registers command for processing.
6. Repository acknowledges reception of command with id `cmd-1`.
7. Client registers processed command id `cmd-1`.
8. Repository updates internal representation.
9. Repository creates event for update.
10. Repository emits event <<evnt-PropertyAdded>> with `nodeA` node id, `age` property (details omitted), `23` value and sequence number `1`.
It includes one <<commandSourceType>> with value `(client-a, cmd-1)`
11. Client found a matching registered processed command id.
12. Client unregisters processed command id `cmd-1`, and does NOT forward information to editor -- the event originates from this client, thus has already been processed.
13. Another client sends <<cmd-AddProperty>> command with command id `cmd-x` (other parameters omitted).
14. Repository updates internal representation.
15. Repository creates event for update.
16. Repository emits event <<evnt-PropertyAdded>> with sequence number `2` (other parameters omitted).
It includes one <<commandSourceType>> with value `(other-client, cmd-x)`
17. Client did not find any matching registered processed command id.
18. Client forwards information to editor.
19. Client updates with new property value.
