=== Client changes known node with local update
[plantuml,changeKnownNodeLocalUpdate,svg]
----
hide footbox
autonumber

box "Client A"
  participant Editor as editor
  participant Events as clientEvent
  participant Commands as clientCmd
end box

box "Server"
  participant Commands as repoCmd
  participant Events as repoEvent
  participant Core as core
end box

== Client A connected with participation id "participation-a"\nsubscribed to "partition-id"\nknows about nodeA (part of "partition-id") ==

[->> editor ++
editor -> editor: update(nodeA.age = 23)
editor ->> clientCmd
deactivate editor
activate clientCmd
clientCmd ->> repoCmd ++: addProperty("nodeA", age, "23", "cmd-1")

repoCmd ->> core
activate core
deactivate repoCmd

clientCmd -> clientEvent: registerProcessedCmd("cmd-1")
activate clientEvent
deactivate clientCmd
deactivate clientEvent

core -> core: update()

core -> repoEvent
deactivate core

activate repoEvent
clientEvent <<- repoEvent: propertyAdded("nodeA", age, "23", [("participation-a", "cmd-1")], 1)
deactivate repoEvent

activate clientEvent
clientEvent -> clientEvent: checkForProcessedCmd()
clientEvent -> clientEvent: removeProcessedCmd("cmd-1")
deactivate clientEvent

core <<-]: addProperty(..., "cmd-x")
activate core
core -> core: update()

core -> repoEvent
deactivate core

activate repoEvent
clientEvent <<- repoEvent: propertyAdded(... [("other-client", "cmd-x")], 2)
deactivate repoEvent

activate clientEvent
clientEvent -> clientEvent: checkForProcessedCmd()
clientEvent -> editor
deactivate clientEvent

activate editor
editor -> editor: update()
----
1. User enters new property value.
2. Client updates `nodeA` with new property value.
3. Client editor forwards user action into command.
4. Client sends <<cmd-AddProperty>> command with `nodeA` node id, `age` property (details omitted), `23` value and command id `cmd-1`.
5. Server registers command for processing.
6. Client registers processed command id `cmd-1`.
7. Server updates internal representation.
8. Server creates event for update.
9. Server emits event <<evnt-PropertyAdded>> with `nodeA` node id, `age` property (details omitted), `23` value and sequence number `1`.
It includes one <<commandSourceType>> with value `(participation-a, cmd-1)`
10. Client found a matching registered processed command id.
11. Client unregisters processed command id `cmd-1`, and does NOT forward information to editor -- the event originates from this client, thus has already been processed.
12. Another client sends <<cmd-AddProperty>> command with command id `cmd-x` (other parameters omitted).
13. Server updates internal representation.
14. Server creates event for update.
15. Server emits event <<evnt-PropertyAdded>> with sequence number `2` (other parameters omitted).
It includes one <<commandSourceType>> with value `(other-client, cmd-x)`
16. Client did not find any matching registered processed command id.
17. Client forwards information to editor.
18. Client updates with new property value.
