=== Client tries to change invalid node id
[plantuml,changeUnknownNodeFailedCommand,svg]
----
hide footbox
autonumber

box "Client A"
  participant Editor as editor
  participant Events as clientEvent
  participant Commands as clientCmd
end box

box "Repository"
  participant Commands as repoCmd
  participant Events as repoEvent
  participant Core as core
end box

== Client A connected with participation id "participation-a"\nsubscribed to "partition-id"\nassumes invalid nodeA (part of "partition-id") ==

[->> editor ++
editor -> clientCmd ++
clientCmd ->> repoCmd ++: addProperty("node with spaces", age, "23", "cmd-1")
repoCmd ->> core: checkNodeId("node with spaces")
activate core
deactivate repoCmd
clientCmd -> clientEvent: registerProcessedCmd("cmd-1")
activate clientEvent
deactivate clientEvent
deactivate repoCmd
editor <-- clientCmd
deactivate clientCmd
deactivate editor

core -> repoEvent: false
deactivate core

activate repoEvent
clientEvent <<- repoEvent: error("invalidNodeId", "invalid node id 'node with spaces'"  [("participation-a", "cmd-1")], 1)
deactivate repoEvent

activate clientEvent
clientEvent -> clientEvent: removeProcessedCmd("cmd-1")

clientEvent ->> editor
deactivate clientEvent

activate editor
[<<- editor: DisplayError()
----
1. User enters new property value on node `node with spaces` that's known to the editor.
2. Client editor forwards user action into command.
3. Client sends <<cmd-AddProperty>> command with `node with spaces` node id, `age` property (details omitted), `23` value and command id `cmd-1`.
4. Repository checks whether node id `node with spaces` is valid.
5. Client registers processed command id `cmd-1`.
6. Client informs editor of command submission.
7. Repository rejects invalid node id.
8. Repository sends <<evnt-Error>> event only to this participation with `invalidNodeId` error code, `invalid node id 'node with spaces'` message and sequence number `1`.
It includes one <<commandSourceType>> with value `(participation-a, cmd-1)`.
9. Client removes `cmd-1` from open commands list.
10. Client informs editor of failed command.
11. Client informs user.