=== Concurrent changes to known node with remote update
[plantuml,concurrentChangeRemoteUpdate,svg]
----
hide footbox
autonumber

box "Client A"
  participant Editor as editor
  participant Events as clientEvent
  participant Commands as clientCmd
end box

box "Server"
  participant Commands as repoCmd
  participant Events as repoEvent
  participant Core as core
end box

== Client A connected with participation id "participation-a"\nsubscribed to "partition-id"\nknows about nodeA (part of "partition-id") ==

[->> editor ++
editor -> clientCmd ++
clientCmd ->> repoCmd ++: addProperty("nodeA", age, "23", "cmd-1")
repoCmd ->> core
activate core
deactivate repoCmd
editor <-- clientCmd
deactivate clientCmd
deactivate editor

core <<-]: addProperty("nodeA",\n  age, "42", "cmd-x")

core -> core: resolveConcurrentUpdates()

core -> repoEvent
deactivate core

activate repoEvent
clientEvent <<- repoEvent: propertyAdded("nodeA", age, "42", [("participation-a", "cmd-1"), ("other-client", "cmd-x")], 1)
deactivate repoEvent

activate clientEvent
clientEvent -> editor
deactivate clientEvent

activate editor
editor -> editor: update(nodeA)
----
1. User enters new property value.
2. Client editor forwards user action into command.
3. Client sends <<cmd-AddProperty>> command with `nodeA` node id, `age` property (details omitted), `23` value and command id `cmd-1`.
4. Server registers command for processing.
5. Client informs editor of command submission.
6. Another client sends <<cmd-AddProperty>> command `nodeA` node id, `age` property (details omitted), `42` value and command id `cmd-x`.
7. Server resolves concurrent updates t `nodeA`, `age` property with "last write wins" strategy.
Server updates internal representation with value `42`.
8. Server creates event for update.
9. Server emits event <<evnt-PropertyAdded>> with `nodeA` node id, `age` property (details omitted), `23` value and sequence number `1`.
It includes one <<commandSourceType>> with values `(participation-a, cmd-1)` and `(other-client, cmd-x)`.
10. Client receives event and forwards information to editor.
11. Client updates `nodeA` with new property value.
