=== Concurrent changes to known node with local update
[plantuml,concurrentChangeLocalUpdate,svg]
----
hide footbox
autonumber

box "Client A"
  participant Editor as editor
  participant Events as clientEvent
  participant Commands as clientCmd
end box

box "Server"
  participant Commands as repoCmd
  participant Events as repoEvent
  participant Core as core
end box

== Client A connected with participation id "participation-a"\nsubscribed to "partition-id"\nknows about nodeA (part of "partition-id") ==

[->> editor ++
editor -> editor: update(nodeA.age = 23)
editor ->> clientCmd
deactivate editor
activate clientCmd
clientCmd ->> repoCmd ++: addProperty("nodeA",\n  age, "23", "cmd-1")
repoCmd ->> core
activate core
deactivate repoCmd
clientCmd -> clientEvent: registerProcessedCmd("cmd-1")
activate clientEvent
deactivate clientEvent
deactivate clientCmd

core <<-]: addProperty("nodeA",\n  age, "42", "cmd-x")

core -> core: resolveConcurrentUpdates()

core -> repoEvent
deactivate core

activate repoEvent
clientEvent <<- repoEvent: propertyAdded("nodeA", age, "42", [("participation-a", "cmd-1"), ("other-client", "cmd-x")], 1)
deactivate repoEvent

activate clientEvent
clientEvent -> clientEvent: checkForProcessedCmd()
clientEvent -> clientEvent: removeProcessedCmd("cmd-1")
clientEvent -> editor
deactivate clientEvent

activate editor
editor -> editor: update(nodeA.age = 42)
----
1. User enters new property value.
2. Client updates `nodeA` with new property value.
3. Client editor forwards user action into command.
4. Client sends <<cmd-AddProperty>> command with `nodeA` node id, `age` property (details omitted), `23` value and command id `cmd-1`.
5. Server registers command for processing.
6. Client registers processed command id `cmd-1`.
7. Another client sends <<cmd-AddProperty>> command `nodeA` node id, `age` property (details omitted), `42` value and command id `cmd-x`.
8. Server resolves concurrent updates `nodeA`, `age` property with "last write wins" strategy.
Server updates internal representation with value `42`.
9. Server creates event for update.
10. Server emits event <<evnt-PropertyAdded>> with `nodeA` node id, `age` property (details omitted), `23` value and sequence number `1`.
It includes one <<commandSourceType>> with values `(participation-a, cmd-1)` and `(other-client, cmd-x)`.
11. Client found a matching registered processed command id.
12. Client unregisters processed command id `cmd-1`.
13. Not all command sources could be matched against registered processed command ids.
Client forwards information to editor.
14. Client updates with new property value.
