=== Concurrent changes to known node with remote update
[plantuml,concurrentChangeRemoteUpdate,svg]
----
hide footbox
autonumber

box "Client A"
  participant Editor as editor
  participant Events as clientEvent
  participant Commands as clientCmd
end box

box "Repository"
  participant Commands as repoCmd
  participant Events as repoEvent
  participant Core as core
end box

== Client A connected with client id "client-a"\nsubscribed to "partition-id"\nknows about nodeA (part of "partition-id") ==

[->> editor ++
editor -> clientCmd ++
clientCmd -> repoCmd ++: addProperty("nodeA", age, "23", "cmd-1")
repoCmd ->> core
activate core
clientCmd <-- repoCmd: received("cmd-1")
deactivate repoCmd
editor <-- clientCmd
deactivate clientCmd
deactivate editor

core <<-]: addProperty("nodeA",\n  age, "42", "cmd-x")

core -> core: resolveConcurrentUpdates()

core -> repoEvent
deactivate core

activate repoEvent
clientEvent <<- repoEvent: propertyAdded("nodeA", age, "42",\n  ["ZWUzN2Q0YTcwZjM4YzhjYzU3NmQ5YThk\n    NjczNTU0ODBmMDI4YTE0MjE4ZDU2MTRh\n    NGRjNTA3NmE1MTk3Y2U3ZiAgLQo",\n  "ZjJlM2FhMTVkZTllZjA1MmRiMzdjMzZj\n    YWE5YjVkYmUxMTI3ZmIzM2I0NDM3NTE1\n    MzgzNGYwMTczMTRkMDU5ZSAgLQo\n  "])
deactivate repoEvent

activate clientEvent
clientEvent -> editor
deactivate clientEvent

activate editor
editor -> editor: update(nodeA)
----
1. User enters new property value.
2. Client editor forwards user action into command.
3. Client sends <<cmd-addProperty>> command with `nodeA` node id, `age` property (details omitted), `23` value and command id `cmd-1`.
4. Repository registers command for processing.
5. Repository acknowledges reception of command with id `cmd-1`.
6. Client informs editor of command submission.
7. Another client sends <<cmd-addProperty>> command `nodeA` node id, `age` property (details omitted), `42` value and command id `cmd-x`.
8. Repository resolves concurrent updates t `nodeA`, `age` property with "last write wins" strategy.
Repository updates internal representation with value `42`.
9. Repository creates event for update.
10. Repository emits event <<evnt-propertyAdded>> with `nodeA` node id, `age` property (details omitted) and `23` value.
It includes one <<commandSourceType>> with values `base64url(sha256("client-acmd-1"))` and `base64url(sha256("client-acmd-x"))`.
11. Client receives event and forwards information to editor.
12. Client updates `nodeA` with new property value.
