[[cmd-Composite]]
[[cmd-CompositeCommand]]
===== Composite
Groups several commands into a logical group.{fn-org281}
The parts are ordered.

Command groups don't guarantee anything; the repository MAY take the group as a hint to resolve conflicts in a different manner.

We can nest composite commands arbitrarily.{fn-org360}

Semantics:{fn-org420}

* One <<cmd-CompositeCommand>> SHOULD be processed as one <<evnt-CompositeEvent>>.
* **No** transactional semantics: all <<CompositeCommand.parts>> are processed in order and independent of the outcome of previous ones.
** The repo MUST be in valid state after having processed each command.
** For client implementations: nodes detached and re-attached during a composite command SHOULD keep their identity in clients.
* Node ids can only be reused after the outermost <<cmd-CompositeCommand>> has been processed.
* If several <<cmd-CompositeCommand>>s overlap due to repository handling (e.g. conflict resolution), the behavior is **UNDEFINED**.

.Technical name
`CompositeCommand` footnote:[
This command is the only one to have a `Command` suffix, which is necessary to distinguish it from its <<evnt-CompositeEvent, `CompositeEvent`>> counterpart.
All other commands can be distinguished from their event counterparts by looking at whether the technical name reads as an imperative (“add child” — for commands), or in past perfect tense (”child [has been\] added” — for events).
]

[horizontal]
.Parameters
[[CompositeCommand.parts, `parts`]]parts:: <<commandType>>[]

[[CompositeCommand.commandId]]commandId:: <<commandIdType>>
Composite commands have their own command id, separate from the command ids of its <<CompositeCommand.parts>>.{fn-org353}

[[CompositeCommand.additionalInfos]]additionalInfos:: <<additionalInfosType>>

.Errors
* accumulation of all errors of <<CompositeCommand.parts>>
* <<err-invalidParticipation>>

.Related event
<<evnt-CompositeEvent>>
