[[cmd-Composite]]
[[cmd-CompositeCommand]]
===== Composite
Groups several commands into a logical group.{fn-org281}
The parts are ordered.

Command groups don't guarantee anything; the repository MAY take the group as a hint to resolve conflicts in a different manner.

Whenever a composite command is syntactically incorrect in one of its <<CompositeCommand.parts>>, the repository MUST reject the complete composite command – as if the composite command didn’t even start executing – as the command as a whole is (deemed) syntactically incorrect.{fn-org454}

We can nest composite commands arbitrarily.{fn-org360}

Semantics:{fn-org420}

* The repository SHOULD process one <<cmd-CompositeCommand>> as one <<evnt-CompositeEvent>>.
* **No** transactional semantics: the repository MUST process all <<CompositeCommand.parts>> in order and independent of the outcome of previous ones.
The repository MUST be in valid state after having processed each command.
* If several <<cmd-CompositeCommand>>s overlap due to repository handling (e.g. conflict resolution), the behavior is **UNDEFINED**.

.Technical name
`CompositeCommand` footnote:[
This command is the only one to have a `Command` suffix, which is necessary to distinguish it from its <<evnt-CompositeEvent, `CompositeEvent`>> counterpart.
All other commands can be distinguished from their event counterparts by looking at whether the technical name reads as an imperative (“add child” — for commands), or in past perfect tense (”child [has been\] added” — for events).
]

[horizontal]
.Parameters
[[CompositeCommand.parts, `parts`]]parts:: <<commandType>>[]

[[CompositeCommand.commandId]]commandId:: <<commandIdType>>
Composite commands have their own command id, separate from the command ids of its <<CompositeCommand.parts>>.{fn-org353}

[[CompositeCommand.additionalInfos]]additionalInfos:: <<additionalInfosType>>

.Errors
* accumulation of all errors of <<CompositeCommand.parts>>
* <<err-invalidParticipation>>

.Related event
<<evnt-CompositeEvent>>
