[[cmd-Composite]]
[[cmd-CompositeCommand]]
===== Composite
Groups several commands into a logical group.{fn-org281}
The parts are ordered.

Command groups don't guarantee anything; the repository MAY take the group as a hint to resolve conflicts in a different manner.

Composite commands have a command id on their own.{fn-org353}
We can nest composite commands arbitrarily.{fn-org360}

.Technical name
`CompositeCommand` footnote:[
This command is the only one to have a `Command` suffix, which is necessary to distinguish it from its <<evnt-CompositeEvent, `CompositeEvent`>> counterpart.
All other commands can be distinguished from their event counterparts by looking at whether the technical name reads as an imperative (“add child” — for commands), or in past perfect tense (”child [has been\] added” — for events).
]

[horizontal]
.Parameters
[[CompositeCommand.parts, `parts`]]parts:: <<commandType>>[]

[[CompositeCommand.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Errors
* accumulation of all errors of <<CompositeCommand.parts>>
* <<err-invalidParticipation>>

.Related event
<<evnt-CompositeEvent>>
