include::../shared/issue-footnotes.adoc[]
:serialization: ../serialization/serialization
:m3: ../metametamodel/metametamodel
= Bulk Language API
:toc: preamble
:toclevels: 3

The bulk Language API is used retrieve languages in batches at the moment of invocation.{fn-org25}{fn-org205}{fn-org215}
It is intended for #CRUD?# operations on languages.
it is *not* intended as a delta-oriented API that takes "modification commands" as arguments.

== Use Cases
We describe the use cases from a client's perspective.

* "You've sent me a chunk referring to languages x and y. Give me the details about these languages", i.e. language reflection.
* "List all languages you know", i.e. language enumeration.

== APIs

[[languages, languages]]
=== languages: Get languages from repository

Retrieves languages of the repository based on the listed <<{serialization}.adoc#UsedLanguage, UsedLanguages>>.

Calling this API MUST NOT change repository contents.

NOTE: We might add advanced filtering capabilities in the future, or introduce an additional querying API.

.Parameters
[[languages.languages]]
`languages`:: List of UsedLanguages we want to retrieve from the repository.
Optional parameter, defaults to _all languages_.

[[languages.mode]]
`mode`:: Set of languages included for each element of `languages` parameter.
Optional parameter, defaults to `closure`.
[[languages.mode.direct]]
`direct`::: Only include the elements of `languages` themselves.
[[languages.mode.closure]]
`closure`:::

-> Remove parameter

.Result
<<{serialization}.adoc#SerializationChunk, SerializationChunk>> containing the transitive closure of all elements of `languages` as instances of <<{m3}.adoc#Language, M3 Language>>.
"Transitive closure" means the languages themselves and all (directly or indirectly) <<{m3}.adoc#Language.dependsOn, dependsOn>> languages.

.Example request: List all languages known to the repository
[source, httprequest]
----
GET /bulk/languages

[]
----

.Example request: Get details on two languages and their dependencies
[source, httprequest]
----
GET /bulk/languages

[
  {
    "key": "my-great-language",
    "version": "1"
  },
  {
    "key": "someThing_ELSE",
    "version": "v34sdvlnq22-cc_1"
  }
]
----

.Example request: Get all languages I need to understand an instance of `my-great-language`
[source, httprequest]
----
GET /bulk/languages

[
  {
    "key": "my-great-language",
    "version": "1"
  }
]
----

// .Example response
// [source, json]
// ----
// include::partitions.json[]
// ----
