include::../shared/issue-footnotes.adoc[]
:serialization: ../serialization/serialization
:m3: ../metametamodel/metametamodel
:trash: trash-api
:arch: ../reference-architecture/reference-architecture
:chunk: <<{serialization}.adoc#SerializationChunk, SerializationChunk>>

[[bulk]]
= Bulk Repository Access API
:toc: preamble
:toclevels: 2

The bulk API *version 2025.1* is used to store and retrieve nodes in batches at the moment of invocation.{fn-org25}
It is intended for CRUD operations on (larger) sets of nodes.
it is *not* intended as a delta-oriented API that takes "modification commands" as arguments.

== Conventions used in this document
* ALL-CAPS key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in https://datatracker.ietf.org/doc/html/bcp14[BCP14] (https://datatracker.ietf.org/doc/html/rfc2119[RFC2119], https://datatracker.ietf.org/doc/html/rfc8174[RFC8174]) when, and only when, they appear in all capitals, as shown here.
* Footnotes refer to more discussions and rationale, but are non-normative.

[[use-cases]]
== Use Cases
We describe the use cases from a client's perspective.

* "I'm starting up, which partitions do you know about?", i.e. <<listPartitions, list possible contents>>.
* "Let's have a new slate, add a new partition", i.e. <<createPartitions, partition creation>>.
* "This part is not needed any more, remove the partition", i.e. <<deletePartitions, partition deletion>>.
* "Give me the whole subtree under this node", i.e. actual <<retrieve, bulk data retrieval>>
* "Here is a node forest, store it as I hand it to you", i.e. actual <<store, bulk data storage>>.
** Sub-case with same behavior: "I'm a very simple client who only knows load and save (like a file), so whatever I send you is the truth", i.e. <<store, click-save-button>>.
* "I'm starting up, get me the current partition contents", i.e. <<retrieve, initial load>>.
* "I want to create a guaranteed new node, which id to use?", i.e. retrieval of <<ids, unused ids>>.

[[validity]]
== Validity assumptions
We don't need to know anything about languages for this API.{fn-org203}

We never sent partial nodes or features.{fn-org211}
Thus, we can only update or receive a complete node with all its features.
We cannot update only some of the features, or part of a feature (e.g. start of a string property value).

We assume transactional semantics for each modifying command.{fn-org229}
A command either succeeds completely, or fails completely and does not change the repository's content.

We do support invalid models w.r.t.{fn-org226}

* Violations of metamodel constraints, e.g. whether a Concept instance without parent is a partition, a feature instance can be part of its node instance, or a node mentioned as annotation is an Annotation instance.
* Unresolvable references, i.e. a <<{serialization}.adoc#reference, reference target node id>> unknown to the repository.

We enforce conformance to{fn-org223}

* Tree structure (i.e. at most one parent for each node)
* Symmetry between containment/annotation and parent
* No unresolvable containment/annotation ids
* No unresolvable parent ids
* A child node id MUST appear exactly once in all of its parent's containments
* An annotation node id MUST appear exactly once in all of its parent's annotations
* Every node MUST (directly or indirectly) be contained in a partition, except partitions themselves
* Partitions MUST NOT have a parent

[[out-of-scope]]
== Out of scope
We assume mapping API is separate from bulk API{fn-org94}.

For now, we do not support paging, as paging tree nodes is non-trivial.{fn-org204}

For now, we don't include any specific protections agains denial-of-service attacks.{fn-org237}

We don't describe the binding to any specific protocol (e.g. HTTP) as part of this specification; We only describe the semantics.{fn-org148}

[[deleted-nodes]]
== Deleted nodes
We don't have an explicit delete command for non-root nodes.{fn-org221}
We delete non-root nodes indirectly by sending their parent without the deleted node mentioned as child.
We can <<deletePartitions>> via explicit command.

We don't support [[orphan, orphans]]_orphans_ for now.
They are immediately deleted.{fn-org219}

Deleted nodes don't exist anymore in the repository from the client's point of view.
They might still exist in other contexts (e.g. another branch), or physically within the repository for internal reasons (e.g. storage optimization, concurrent editing support).
A deleted node MUST NOT appear in any responses according to this API.{fn-org220}

A repository MAY consider the deleted node's id to be _unused_, and thus allow to re-use it.
A repository also MAY disallow re-using previously deleted node ids.

[[client-ids]]
== Client ids
Each <<{arch}.adoc#client, client>> MUST  provide a unique _client id_ when connecting to the repository.{fn-org241}
The client id is an <<{m3}.adoc#identifiers, identifier>>-compatible string.
A client MAY connect more than once to the same repository at the same time with the same client id.
It is out of scope of LionWeb to guarantee the uniqueness of the client id.
The repository does not apply any uniqueness checks.

[[unknown-node-ids]]
== Unknown node ids
An _unknown node id_ is a node id that's not the node id of any node present in the repository.
An unknown node id can be present as a reference target (as we support unresolvable references).

How to handle unknown node ids in <<createPartitions>> and <<store>> commands?{fn-org94}{fn-org70}

Scenarios:

[cols="4,1,2,1,1,2"]
|===
|Description: Node id ... |Valid format |Format fits repo |Present in repo | Reserved |Repo action

|already present in repository
|✔️
|✔️ (repo accepted it)
|✔️
|✔️
|error (<<createPartitions>>) / update node (<<store>>)

|<<ids, requested>> by this client
|✔️
|✔️ (repo handed it out)
|❌
|✔️
|create node

|<<ids, requested>> by other client
|✔️
|✔️ (repo handed it out)
|❌
|✔️
|error

|used previously by deleted node, repo disallows re-use
|✔️
|✔️ (repo handed it out)
|❌
|✔️
|error

|used previously by deleted node, repo supports re-use
|✔️
|✔️ (repo handed it out)
|❌
|❌
|create node

|invented by this client, requested by other client
|✔️
|✔️ (repo handed it out)
|❌
|✔️
|error

|invented by client, matches repo format +
Example: `123` for repo with internal long ids
|✔️
|✔️
|❌
|❌
|create node

|invented by client, violates repo format +
Example: `ab123` for repo with internal long ids
|✔️
|❌️
|❌
|❌
|create node

|invented by client, invalid  +
Example: `he!!o`
|❌️️
|❌️
|❌
|❌
|error

|===

[[responses]]
== Responses
The repository

Besides the main response, the repository can reply each command with zero or more additional

[[parameter-syntax]]
=== Parameter syntax
* Parameters suffixed with `?` CAN be omitted, or CAN have a value of `null`.
Both representations express the parameter to be unset.{fn-org427}

* Parameters suffixed with `[]` are ordered lists with zero or more elements.

[[parameter-types]]
== Parameter types
[horizontal]
[[chunkType]]chunk:: A {chunk} of nodes.

[[nodeIdType]]nodeId:: A <<{m3}.adoc#identifiers, valid node id>>.

[[integerType]]integer:: An integer.

[[commandIdType]]commandId:: Each _modifying_ command MUST contain a _[[commandId, commmand id]]command id_.{fn-org313}
It has the same format as <<{m3}.adoc#identifiers, node ids>> and must be unique for all changes of this client.
+
Modifying commands are <<createPartitions>>, <<deletePartitions>>, and <<store>>.

[[successType]]success:: A boolean flag signalling _success_ or _failure_ with each response.

[[additionalInfosType]]additionalInfos:: Optionally empty{fn-org402} list of [[additionalInfo]] _additional infos_ in either request or response.{fn-org236}{fn-org375}{fn-org430}
Each additional info consists of:

* [[additionalInfo.kind]]`kind` is an <<{m3}.adoc#identifiers, identifier>>-compatible string identifying the additional info type.
Some kinds are pre-defined in this specification.
A repository MAY reply with other, additional kinds.
* [[additionalInfo.distribute]]`distribute`? is an optional <<booleanType>> flag with default value `false`.
It is only valid in <<createPartitions>>, <<deletePartitions>>, and <<store>>, i.e. MUST NOT be used for <<listPartitions>>, <<retrieve>> or <<ids>>.
If present and set to `true`, the repository MUST copy the additional info to all <<{delta}.adoc#events, delta protocol events>> that result from the command, and distribute the additional info to all participants receiving the event.

* [[additionalInfo.message]]`message` is a human-readable string describing the additional info.
* [[additionalInfo.data]]`data` is a flat map with 0 or more arbitrary keys and values.
All keys MUST be <<{m3}.adoc#identifiers, identifier>>-compatible and MUST be unique within the same additional info.
All values MUST be strings.
A _kind_ might imply presence of specific keys in `data`.

+
[[additionalInfo-kinds-global]]
.Additional info kinds for all commands
[cols="3h,3,1,7a"]
|===
|Kind |Description |Success |Implied data

|`` #TODO#
|Invalid node id
|false
|
[horizontal]
`invalidNodeId`:: Id of non-partition node.

|`` #TODO#
|Node with same id sent more than once
|false
|#TODO#

|`` #TODO#
|Invalid tree due to concurrent update{fn-org238}
|false
|#TODO#

|===

+
This additional info is symmetric to <<{delta}.adoc#additionalInfo, additional infos in delta API>>.


[[commands]]
[[apis]]
== Commands



[[listPartitions, listPartitions]]
[[partitions, listPartitions]]
=== listPartitions: List available partitions
Lists all non-language partitions accessible in the repository.

Calling this command MUST NOT change repository contents.

NOTE: We might add filter capabilities in the future.

.Request parameters
[horizontal]
[[listPartitions.commandId]]commandId:: <<commandIdType>>? Optional as this is not a modifying command.
[[listPartitions.requestAdditionalInfos]]additionalInfos:: <<additionalInfosType>>[]

.Response parameters
[horizontal]
[[listPartitions.chunk]]chunk:: <<chunkType>> with all accessible <<{m3}.adoc#partition, Partitions>> in the Repository.
The partitions are sent as complete nodes.{fn-org202}
Does NOT include any children or annotations of the root partition nodes.
Does NOT include <<{m3}.adoc#Language, Languages>> or partition children/annotations.
[[listPartitions.success]]success:: <<successType>>
[[listPartitions.responseAdditionalInfos]]additionalInfos:: <<additionalInfosType>>[] with no special additional info kinds.

[[createPartitions, createPartitions]]
=== createPartitions: Create new partitions
Creates new partitions in the repository.{fn-org216}

Each sent node with no parent node id is its own partition.
All other nodes MUST NOT exist in the repository, and they MUST be descendants of on of the partition nodes.
We cannot use <<store.semantics, move semantics>>.
We MAY reference nodes already existing in the repository.{fn-org369}

Nodes MUST use <<unknown-node-ids>>.

.Request parameters
[horizontal]
[[createPartitions.nodes]] nodes:: <<chunkType>> containing all nodes we want to add as new partitions.
[[createPartitions.commandId]]commandId:: <<commandIdType>>
[[createPartitions.requestAdditionalInfos]]additionalInfos:: <<additionalInfosType>>[]

.Response parameters
[horizontal]
[[createPartitions.success]]success:: <<successType>>
[[createPartitions.responseAdditionalInfos]]additionalInfos:: <<additionalInfosType>>[]
+
[cols="3h,3,1,7a"]
|===
|Kind |Description |Success |Implied data

|`PartitionHasParent`
|Partition node states parent id
|false
|
[horizontal]
`nodeId`:: node id of requested partition that has a parent.

|`PartitionAlreadyExists`
|Partition node id already exists
|false
|
[horizontal]
`nodeId`:: Id of already existing node.

|`` #TODO#
|Partition node id not reserved for this client
|false
| #TODO#

|`PartitionHasChildren`
`PartitionHasAnnotations` #TODO#
|Partition node lists contained or annotated nodes
|false
|
[horizontal]
`nodeId`:: node id of requested partition that has children or annotations.

|`EmptyChunk`
|Empty Request
|true
|None

|===

[[deletePartitions, deletePartitions]]
=== deletePartitions: Delete partitions and all their contents
Deletes all mentioned partitions, including all (transitive) annotations and children.

All mentioned node ids MUST be ids of partition nodes.

All (transitive) annotations and children become <<orphan, orphans>>.

.Request parameters
[horizontal]
[[deletePartitions.nodeIds]]nodeIds:: <<nodeIdType>>[] List of node ids to delete.
[[deletePartitions.commandId]]commandId:: <<commandIdType>>
[[deletePartitions.requestAdditionalInfos]]additionalInfos:: <<additionalInfosType>>[]

.Response parameters
[horizontal]
[[deletePartitions.success]]success:: <<successType>>
[[deletePartitions.responseAdditionalInfos]]additionalInfos:: <<additionalInfosType>>[]
+
[cols="3h,3,1,7a"]
|===
|Kind |Description |Success |Implied data

|`NodeIsNotPartition`
|Node with that id is not a partition
|false
|
[horizontal]
`nodeId`:: Id of non-partition node.
`parentNodeId`:: Id of the parent node.

|`` #TODO#
|Node with that id does not exist
|true
|#TODO#

|===


[[retrieve, retrieve]]
=== retrieve: Get nodes from repository
Retrieves subtrees nested in the listed node ids.{fn-org201}

Calling this command MUST NOT change repository contents.

NOTE: We might add advanced filtering capabilities in the future, or introduce an additional querying API.

.Request parameters
[horizontal]
[[retrieve.nodeIds, `nodeIds`]]nodeIds:: <<nodeIdType>>[] List of node ids we want to retrieve from the repository.
Can be partition node ids and/or nested node ids.
[[retrieve.depthLimit, `depthLimit`]]depthLimit:: <<integerType>>? Limit the depth of retrieved subtrees.
Optional parameter, defaults to _infinite_.
If present, MUST be an integer >= 0, with
+
--
* 0 meaning "return only the nodes with ids listed in <<retrieve.nodeIds>> parameter",
* 1 meaning "return the nodes with id listed in the <<retrieve.nodeIds>> parameter and their direct children/annotations",
* 2 meaning "return the nodes with id listed in the <<retrieve.nodeIds>> parameter, their direct children/annotations, and the direct children/annotations of these",
* etc.
--
+
NOTE: There's no _magic value_ of <<retrieve.depthLimit>> to express _infinite_ depth.
We need to omit the parameter if we don't want to limit the depth.
[[retrieve.commandId]]commandId:: <<commandIdType>>? Optional as this is not a modifying command.
[[retrieve.requestAdditionalInfos]]additionalInfos:: <<additionalInfosType>>[]

.Response parameters
[horizontal]
[[retrieve.chunk]]chunk:: <<chunkType>> containing all nodes according to <<retrieve.nodeIds>> and <<retrieve.depthLimit>> parameters.
Does NOT include the definition of <<{serialization}.adoc#UsedLanguage, UsedLanguages>>, only their <<{serialization}.adoc#MetaPointer, MetaPointers>>.
[[retrieve.success]]success:: <<successType>>
[[retrieve.responseAdditionalInfos]]additionalInfos:: <<additionalInfosType>>[]
+
[cols="3h,3,1,7a"]
|===
|Kind |Description |Success |Implied data

|`IdNotFound`
|Node with requested id does not exist
|true
|
[horizontal]
`nodeId`:: Id of non-existent node

|`EmptyIdList`
|Empty id list
|true
|None

|`IdsIncorrect`
|Invalid ids parameter
|false
|
[horizontal]
`nodeIds`:: The invalid `nodeIds` parameter

|`DepthLimitIncorrect`
|Invalid depthLimit parameter
|false
|
[horizontal]
`depthLimit`:: The invalid `depthLimit` parameter.

|===


[[store, store]]
=== store: Put nodes into repository
Creates new nodes, or updates existing nodes in the repository.

We always process one node in its entirety, i.e. we cannot update parts of the node with this command.{fn-org211}

A node id referenced as parent, containment, reference, or annotation _can_ be mentioned in the same request, but _can_ be omitted if a node with that id already exists in the repository.
This way, we can move subtrees and add arbitrary references without sending unchanged nodes.

We consider that node to be _new_ if it has an <<unknown-node-ids, unknown node id>>.
Otherwise, we consider the node to be _updated_ (i.e. if a node with the same id already exists in the repository).

We do not support different modes.{fn-org230}

[[store.semantics]]
.Semantics
After completing this call, all sent nodes MUST have exactly the sent contents in the repository.
We must send containments/annotations from the parent's view, because we need to know the containment and index of the contained node/annotation within its parent.

If we move a contained/annotation node `C` from its previous parent `A` to its new parent `B`, we MUST send `B`, and MAY omit `A`.{fn-org227}
This means we can have implicit changes in `A`.

The whole call fails, without any changes to the repository, if it would lead to a <<validity, malformed model>>.{fn-org223}
The repository MUST NOT validate the metamodel constraints of the sent nodes.{fn-org226}

The repository MUST support changing <<{serialization}.adoc#meta-pointer, meta-pointers>>, e.g.  a node's `classifier.language`, a property's `property.version` or an enumeration literal's `key`.{fn-org69}

.Request parameters
[horizontal]
[[store.nodes, `nodes`]]nodes:: <<chunkType>> containing all nodes to store to the repository.
[[store.commandId, `commandId`]]commandId:: <<commandIdType>>
[[store.requestAdditionalInfos]]additionalInfos:: <<additionalInfosType>>[]

.Response parameters
[horizontal]
[[store.success]]success:: <<successType>>
[[store.responseAdditionalInfos]]additionalInfos:: <<additionalInfosType>>[]
+
[cols="3h,3,1,7a"]
|===
|Kind |Description |Success |Implied data

|`NullChunk`
|Chunk missing
|false
|None

|`` #TODO#
|Node id mentioned as annotation/child in more than one parent
|false
|#TODO#

|`` #TODO#
|Move would create loop in tree
|false
|#TODO#

|`ParentMissing`
|Parent / child / annotation node id unknown
|false
|
[horizontal]
`nodeId`:: Id of node that doesn't have a parent.

|`` #TODO#
|Parent doesn't match child/annotation
|false
|#TODO#

|`` #TODO#
|New node id not reserved for this client
|false
|#TODO#

|===


[[ids, ids]]
=== ids: Get available ids
Provides unused <<{m3}.adoc#identifiers, valid node ids>>.

The repository

* MUST NOT hand out the same unused ids to any other client.
* MAY hand out the same unused ids to the same client more than once.
* MUST NOT contain any node with any of the provided ids.

The ids MUST exclude the <<{m3}.adoc#predefined-builtins-keys, built-in ids>>.

Calling this command MUST NOT change repository contents themselves (besides the internal knowledge of reserved ids).

We don't assume leases, i.e. ids handed out to one client are "owned" by that client forever.
Rationale: Otherwise, the repository must track sessions, and run housekeeping on leases.
This would exclude simple repository implementations.

We assume infinite id space.

.Request parameters
[horizontal]
[[ids.count]]count:: <<integerType>> Number of ids requested.
The repository MUST return between one (inclusive) and `count` (inclusive) ids.
It MAY return less than `count` ids.
[[ids.commandId, `commandId`]]commandId:: <<commandIdType>>? Optional as this is not a modifying command.
[[ids.requestAdditionalInfos]]additionalInfos:: <<additionalInfosType>>[]

.Response parameters
[horizontal]
[[ids.ids]]ids:: <<nodeIdType>>[] List of ids guaranteed to be free.
[[ids.success]]success:: <<successType>>
[[ids.responseAdditionalInfos]]additionalInfos:: <<additionalInfosType>>[] with no special additional info kinds.


[[crud-mapping]]
== Mapping CRUD operations

list:: <<listPartitions>> for partitions, <<retrieve>> for descendants.

read:: <<retrieve, retrieve call>> with requested node ids (both partitions and other nodes).

create:: <<createPartitions>> for partitions, <<store, store call>> that sends a node with a <<ids, _new id_>>, including all its features.

update:: <<store, store call>> that sends a node (both partitions and other nodes) with an _existing id_, including all its features (both updated and unchanged).

delete:: <<deletePartitions>> for partitions (including all descendants), for others <<store>> of the parent node without mentioning the deleted node.

move:: Assume we want to move node `N` from its current parent `S` to its new parent `T`.
+
<<store, store call>> that sends `T` with all its features, including `N` in the children.
+
NOTE: We cannot move partitions, as we cannot nest them.{fn-org29}
