include::../shared/issue-footnotes.adoc[]
:serialization: ../serialization/serialization
:m3: ../metametamodel/metametamodel
:bulk: repo-access-api

= Bulk Trash API
:toc: preamble
:toclevels: 3

<<{bulk}.adoc#orphan, Orphans>> are nodes that fall out of the original model tree.
Instead of just forgetting about them, a repository can optionally move them into a special place called _trash_.
Orphans can be _recovered_ from there by re-inserting them into the original model tree.

== Trash lifetime
The repository MAY delete nodes in _trash_ according to its own _garbage collection_ rules (e.g. after some time, or on memory pressure).

[horizontal]
Jos:: Trash? Didn't see this before.  Doesn't thip open up manu additional questions
- What happens if I create a node with an id of a trahsed node?
Jos:: I don't like the idea that trashed nodes can just be found as any other node.
I would expect an explicit recovery call of some kind.
Jos:: This might be something to postpone, it makes everything more complex

== Adjustments to Bulk Repository Access API

[[partitions]]
=== partitions
The <<{bulk}.adoc#partitions, partitions>> command MUST NOT return any nodes from _trash_.

[[retrieve]]
=== retrieve
The <<{bulk}.adoc#retrieve, retrieve>> command MUST return nodes from _trash_.
#TODO correct?#
This can only happen if the client "remembers" the id of an orphan node, as there is no regular way to access them.

[[store]]
=== store
The <<{bulk}.adoc#store, store>> command SHOULD move orphans to _trash_.
The repository MAY choose to directly delete an orphan on some criteria, e.g. low resources.

Changing nodes within _trash_ fails the whole call without changes to the repository, except if we _recover_ the node.
_Recovering_ means to re-add the orphan node as containment/annotation to a regular node.

[[delete]]
=== delete
The <<{bulk}.adoc#store, store>> command MUST delete orphans from _trash_, if an orphan node id is submitted.
After deletion, an orphan is removed from _trash_.

[[ids]]
=== ids
The <<{bulk}.adoc#store, store>> command MUST NOT return the ids of any orphan as unused.
