[[cmd-MoveAndReplaceChildInSameContainment]]
===== Move child in same containment and replace existing child
Move <<existing-nodes, existing node>> <<MoveAndReplaceChildInSameContainment.movedChild>>
that’s initially at index <<MoveAndReplaceChildInSameContainment.oldIndex>>
within the <<MoveAndReplaceChildInSameContainment.containment>> inside <<MoveAndReplaceChildInSameContainment.parent>>
to the target index (<<MoveAndReplaceChildInSameContainment.oldIndex>> + <<MoveAndReplaceChildInSameContainment.indexOffset>>),
replacing <<existing-nodes, current child>> <<MoveAndReplaceChildInSameContainment.replacedChild>>{fn-org371} at the target index.{fn-org469}
<<MoveAndReplaceChildInSameContainment.replacedChild>> subsequently gets deleted, including all its descendants (including annotation instances).
This does NOT change references to any of the deleted nodes.{fn-org285}

This conforms to <<movingAndReplacingNodes, the action of moving a node and replacing another one in one specific list>> — see that section for more information, diagrams, and examples.

.Technical name
`MoveAndReplaceChildInSameContainment`

[horizontal]
.Parameters
[[MoveAndReplaceChildInSameContainment.parent, `parent`]]parent:: <<targetNodeType>>

[[MoveAndReplaceChildInSameContainment.containment, `containment`]]containment:: <<metaPointerType>>

[[MoveAndReplaceChildInSameContainment.oldIndex, `oldIndex`]]oldIndex:: <<indexType>>

[[MoveAndReplaceChildInSameContainment.indexOffset, `indexOffset`]]indexOffset:: <<indexOffsetType>>
MUST NOT be 0.

[[MoveAndReplaceChildInSameContainment.movedChild, `movedChild`]]movedChild:: <<targetNodeType>>

[[MoveAndReplaceChildInSameContainment.replacedChild, `replacedChild`]]replacedChild:: <<targetNodeType>>

[[MoveAndReplaceChildInSameContainment.commandId]]commandId:: <<commandIdType>>

[[MoveAndReplaceChildInSameContainment.additionalInfos]]additionalInfos:: <<additionalInfosType>>

.Errors
* <<err-unknownNode>> for <<MoveAndReplaceChildInSameContainment.parent>>
* <<err-unknownIndex>> for <<MoveAndReplaceChildInSameContainment.oldIndex>>
is not an integer in the range [0..(the number of containment entries in <<MoveAndReplaceChildInSameContainment.containment>> of <<MoveAndReplaceChildInSameContainment.parent>> - 1)] — see <<integerRangeNotation>> for an explanation of the [`left`..`right`] notation
* <<err-invalidIndexOffset>> for <<MoveAndReplaceChildInSameContainment.indexOffset>>
if <<MoveAndReplaceChildInSameContainment.indexOffset>> equals 0, or if (<<MoveAndReplaceChildInSameContainment.oldIndex>> + <<MoveAndReplaceChildInSameContainment.indexOffset>>) is not in the range [0..(the number of containment entries in <<MoveAndReplaceChildInSameContainment.containment>> of <<MoveAndReplaceChildInSameContainment.parent>> - 1)]
* <<err-unknownNode>> for <<MoveAndReplaceChildInSameContainment.movedChild>>
* <<err-parentMismatch>> <<MoveAndReplaceChildInSameContainment.parent>> is not the parent of <<MoveAndReplaceChildInSameContainment.movedChild>>
* <<err-indexEntryMismatch>> for <<MoveAndReplaceChildInSameContainment.oldIndex>> and <<MoveAndReplaceChildInSameContainment.movedChild>>
if <<MoveAndReplaceChildInSameContainment.movedChild>> is not at index <<MoveAndReplaceChildInSameContainment.oldIndex>> of the containment entries in <<MoveAndReplaceChildInSameContainment.containment>> of <<MoveAndReplaceChildInSameContainment.parent>>
* <<err-moveWithoutParent>> for <<MoveAndReplaceChildInSameContainment.movedChild>>
* <<err-unknownNode>> for <<MoveAndReplaceChildInSameContainment.replacedChild>>
* <<err-parentMismatch>> <<MoveAndReplaceChildInSameContainment.parent>> is not the parent of <<MoveAndReplaceChildInSameContainment.replacedChild>>
* <<err-indexEntryMismatch>> for <<MoveAndReplaceChildInSameContainment.containment>>/(<<MoveAndReplaceChildInSameContainment.oldIndex>> + <<MoveAndReplaceChildInSameContainment.indexOffset>>)
and <<MoveAndReplaceChildInSameContainment.replacedChild>>
if <<MoveAndReplaceChildInSameContainment.replacedChild>> is not at index (<<MoveAndReplaceChildInSameContainment.oldIndex>> + <<MoveAndReplaceChildInSameContainment.indexOffset>>) of the containment entries in <<MoveAndReplaceChildInSameContainment.containment>> of <<MoveAndReplaceChildInSameContainment.parent>>
* <<err-moveWithoutParent>> for <<MoveAndReplaceChildInSameContainment.movedChild>>
* <<err-invalidParticipation>>

.Related event
<<evnt-ChildMovedAndReplacedInSameContainment>>
