[[cmd-MoveAndReplaceChildInSameContainment]]
===== Move child in same containment and replace existing child
Move <<existing-nodes, existing node>> <<MoveAndReplaceChildInSameContainment.movedChild>> within <<MoveAndReplaceChildInSameContainment.containment>>
from index <<MoveAndReplaceChildInSameContainment.oldIndex>> to the target index (<<MoveAndReplaceChildInSameContainment.oldIndex>> + <<MoveAndReplaceChildInSameContainment.indexOffset>>),
replacing <<existing-nodes, current child>> <<MoveAndReplaceChildInSameContainment.replacedChild>>{fn-org371} inside <<MoveAndReplaceChildInSameContainment.containment>> at the target index,
including all its descendants (including annotation instances).{fn-org469}
<<MoveAndReplaceChildInSameContainment.replacedChild>> subsequently gets deleted.
This does NOT change references to any of the deleted nodes.{fn-org285}
The containment is inside <<MoveAndReplaceChildInSameContainment.parent>>.

The corresponding manipulation of a list of – implementation-level! – references to contained nodes can be described as a two-step process:

Set `targetIndex =` <<MoveAndReplaceChildInSameContainment.oldIndex>> + <<MoveAndReplaceChildInSameContainment.indexOffset>>.

1. The list’s entry with index `targetIndex` is set to the child to move (at index <<MoveAndReplaceChildInSameContainment.oldIndex>>), overwriting and effectively replacing the child to replace, which gets deleted as a result.
Now, the list contains the same number of elements as before, just with two references to <<MoveAndReplaceChildInSameContainment.movedChild>>, namely at indices <<MoveAndReplaceChildInSameContainment.oldIndex>> and `targetIndex`.
2. The entry with index `oldIndex` is removed from the list, with elements after being moved to the next lower index — this includes the moved child itself if <<MoveAndReplaceChildInSameContainment.indexOffset>> > 0.
Now, the list contains one less element than before.

This leaves two distinct scenarios depending on whether <<MoveAndReplaceChildInSameContainment.indexOffset>> is positive or negative.

In the scenario with <<MoveAndReplaceChildInSameContainment.indexOffset>> > 0:

[cols="a,a"]
|===
|Before |After
include::MoveAndReplaceChildInSameContainment-diagram-offset-positive.adoc[]
|===

The new index of the moved child can be calculated as follows: `newIndex` = `oldIndex` + `indexOffset` - 1.

In the scenario with <<MoveAndReplaceChildInSameContainment.indexOffset>> < 0:

[cols="a,a"]
|===
|Before |After
include::MoveAndReplaceChildInSameContainment-diagram-offset-negative.adoc[]
|===

The new index of the moved child can be calculated as follows: `newIndex` = `oldIndex` + `indexOffset`.

.Technical name
`MoveAndReplaceChildInSameContainment`

[horizontal]
.Parameters
[[MoveAndReplaceChildInSameContainment.parent, `parent`]]parent:: <<targetNodeType>>

[[MoveAndReplaceChildInSameContainment.containment, `containment`]]containment:: <<metaPointerType>>

[[MoveAndReplaceChildInSameContainment.oldIndex, `oldIndex`]]oldIndex:: <<indexType>>

[[MoveAndReplaceChildInSameContainment.movedChild, `movedChild`]]movedChild:: <<targetNodeType>>

[[MoveAndReplaceChildInSameContainment.indexOffset, `indexOffset`]]indexOffset:: <<relativeIndexType>>
MUST NOT be 0.

[[MoveAndReplaceChildInSameContainment.replacedChild, `replacedChild`]]replacedChild:: <<targetNodeType>>


[[MoveAndReplaceChildInSameContainment.commandId]]commandId:: <<commandIdType>>

[[MoveAndReplaceChildInSameContainment.additionalInfos]]additionalInfos:: <<additionalInfosType>>

.Errors
* <<err-unknownIndex>> for <<MoveAndReplaceChildInSameContainment.oldIndex>> + <<MoveAndReplaceChildInSameContainment.indexOffset>> is smaller than 0 or greater than (the number of entries in <<MoveAndReplaceChildInSameContainment.containment>> in <<MoveAndReplaceChildInSameContainment.parent>> - 1)
* <<err-parentMismatch>> <<MoveAndReplaceChildInSameContainment.parent>> does not have <<MoveAndReplaceChildInSameContainment.movedChild>> as child.
* <<err-unknownNode>> for <<MoveAndReplaceChildInSameContainment.movedChild>>
* <<err-unknownNode>> for <<MoveAndReplaceChildInSameContainment.replacedChild>>
* <<err-unknownNode>> for <<MoveAndReplaceChildInSameContainment.parent>>
* <<err-parentMismatch>> The node <<MoveAndReplaceChildInSameContainment.parent>> does not have <<MoveAndReplaceChildInSameContainment.movedChild>> as a child.
* <<err-moveWithoutParent>> for <<MoveAndReplaceChildInSameContainment.movedChild>>
* <<err-indexEntryMismatch>> for <<MoveAndReplaceChildInSameContainment.containment>>/<<MoveAndReplaceChildInSameContainment.oldIndex>> 
and <<MoveAndReplaceChildInSameContainment.movedChild>>
* <<err-indexEntryMismatch>> for <<MoveAndReplaceChildInSameContainment.containment>>/(<<MoveAndReplaceChildInSameContainment.oldIndex>> + <<MoveAndReplaceChildInSameContainment.indexOffset>>)
and <<MoveAndReplaceChildInSameContainment.replacedChild>>
* <<err-invalidMove>> <<MoveAndReplaceChildInSameContainment.indexOffset>> = 0
* <<err-invalidParticipation>>

.Related event
<<evnt-ChildMovedAndReplacedInSameContainment>>
