[[cmd-AddChild]]
===== Add child
Add new node <<AddChild.newChild>> to <<AddChild.parent>> in <<AddChild.containment>> at <<AddChild.index>>.
<<AddChild.newChild>> might be a single node or an arbitrary complex subtree.
All nodes in that subtree MUST be new, i.e. their id MUST NOT exist in the repository.
Nodes in that subtree MAY have references to already existing nodes, and already existing nodes MAY have references to nodes in that subtree.{fn-org327}

The list of nodes in <<AddChild.newChild>> must form a proper tree, meaning that

- There must be exactly one node (let's call it `child`) within  with `node.parent` equal to <<AddChild.parent>>. This is the node that will be added at <<AddChild.index>> to the <<AddChild.containment>> of  <<AddChild.parent>>
- each other node must be in the subtree of `child`.


[cols="a,a"]
|===
|Before |After

include::AddChild-diagram.adoc[]
|===

.Technical name
`AddChild`

[horizontal]
.Parameters
[[AddChild.parent, `parent`]]parent:: <<targetNodeType>>

[[AddChild.newChild, `newChild`]]newChild:: <<chunkType>>

[[AddChild.containment, `containment`]]containment:: <<metaPointerType>>

[[AddChild.index, `index`]]index:: <<indexType>>

[[AddChild.commandId]]commandId:: <<commandIdType>>

[[AddChild.additionalInfos]]additionalInfos:: <<additionalInfosType>>

.Errors
* <<err-unknownNode>> for <<AddChild.parent>>
* <<err-nodeAlreadyExists>> for any node in <<AddChild.newChild>>
* <<err-notAProperTree>> the nodes in <<AddChild.newChild>> do not form a proper tree
* <<err-childNotFound>> there is no node in <<AddChild.newChild>> with parent <<AddChild.parent>>
* <<err-unknownIndex>> for <<AddChild.index>> (is beyond the number of <<AddChild.containment>> entries in <<AddChild.parent>>)
* <<err-invalidParticipation>>

.Related event
<<evnt-ChildAdded>>
