[[description]]
== Description
[[client, client]]
=== Client characteristics
A client is a program connecting to a repository.
Each client has exactly one <<participation>> with one repository at one point in time.
The same client can have several consecutive participations with the same repository, but never at the same time.
A client might interact with several repositories, but they are completely independent (i.e. same as two clients connecting to two repositories).{fn-org337}

The client has the responsibility to guarantee uniqueness of <<queryIdType, query>> and <<commandIdType, command ids>> within the same participation.

Authentication and authorization are out of scope of this API.

[[channel, channel]]
=== Channel characteristics
Logically, the channel has independent parts for each <<introduction, kind>> of message;
in practice, we might transmit some or all of them through a shared channel.

This protocol is agnostic of its underlying technical implementation.
We can use any (e.g. stateless, stateful) protocol, as long as it fulfills request/response characteristics for client-initiated query, command, and participation messages, and repository-initiated broadcast characteristics for event messages.

We assume the underlying protocol handles quality of service concerns (i.e. guaranteed one-time complete delivery of messages), they are out of scope of this API.

[[participation, participation]]
=== Participation characteristics
Each participation has a _[[participation-id, participation id]]participation id_, unique for all concurrent participations.
The repository assigns the participation id upon starting a new participation.
The participation id MUST follow the same format as <<{m3}.adoc#identifiers, identifier>>.
It serves as a technical identifier.

A participation is transparent for reconnecting network connections,i.e. one participation can survive potential technical reconnects.
A participation spans over time: if we would e.g. used REST, a participation spans over several REST requests/responses.

A participation <<qry-SignOn, starts>> by the client connecting to the repository via delta protocol.
A participation ends either by the <<qry-SignOff, client ending>> it, or if the client disconnects involuntarily (e.g. by crashing or a connection failure).

A client can try to <<qry-Reconnect, reconnect>> a participation if the client still knows a previously valid participation id, and the last <<event-sequence-number>> the client received.{fn-org349}

[[event-sequence-number, event sequence number]]
=== Event sequence numbers
Each event contains a sequence number.{fn-org341}
This number is a positive integer that increments by one for each consecutive event.
It is unique per participation.{fn-org343}

A <<client>> SHOULD use this number to order incoming events, and check whether the client missed any event.

[[subscription, subscription]]
=== Subscription characteristics
The subscription, or subscription scope, is the set of partitions a <<participation>> gets events for.
A subscription does not have an identity on its own; it is bound to one participation.

Scope is defined by the node id of a <<{m3}.adoc#partition, partition>>; it includes all changes to the partition and all its descendants (including annotation instances).{fn-org269}

At the start of a participation, the subscription scope is empty.
A client can change its subscription scope by <<qry-SubscribeToChangingPartitions, subscribing to newly created partitions>>, or <<qry-SubscribeToPartitionContents, subscribe>> / <<qry-UnsubscribeFromPartitionContents, unsubscribe>> a specific partition.
A client can change the subscription scope at any time during a participation.

A client can send commands for any node id, independent of the client's subscription.
Assume a client sends a command for a node that's part of a partition that client is not subscribed to.
The repository treats that command the same as from a client that was subscribed to the containing partition, i.e. applies it in accordance with the repository's policy.
The repository also sends out the same events to subscribed clients, thus _not_ to the sending client.{fn-org352}

[[message, message]]
=== Message characteristics
Each message is atomic; it cannot be split.

Each message has some id unique to the <<participation>>:

* Queries have a _query id_.
* Commands have a _command id_.{fn-org305}
* Events have _command sources_.{fn-org306}

Every kind of message has a unique _technical name_.
The technical name is a valid programming language identifier as described for <<{m3}.adoc#IKeyed, IKeyed>>.
Each binding to a specific protocol might use the technical name in a different way.
For example, a JSON binding might have a member containing the technical name of the message, or a Protobuf binding might use the technical name as type name.

Each message optionally can have one or more _[[protocolMessage, protocol message]]protocol message_ consisting of:{fn-org331}{fn-org332}

* [[protocolMessage.kind]]`kind` is an <<{m3}.adoc#identifiers, identifier>>-compatible string identifying the message type.
Some message kinds are pre-defined in this specification.
A repository MAY reply with other, additional message kinds.
* [[protocolMessage.message]]`message` is a human-readable string describing the message.
* [[protocolMessage.data]]`data` is a flat map with arbitrary keys and values.
All values MUST be strings, the keys MUST be <<{m3}.adoc#identifiers, identifier>>-compatible.
A _kind_ might imply presence of specific keys in `data`.

This protocol message is symmetric to <<{bulk}.adoc#Response.messages, messages in bulk API>>.
