[[description]]
== Description

[[repository, repository]]
=== Repository characteristics
A repository is a set of partitions, and a set of APIs, amongst them this delta API.
The repository has an ID that must be unique for all repositories in the same context.
LionWeb doesn't specify the scope of the context.{fn-org401}

A repository is “its own universe”: nodes within it can't reference nodes, or be referenced from nodes from other repositories.
All nodes within the same repository MUST have unique IDs.
Nodes can refer to nodes from the LionCore and built-in languages.

[[client, client]]
=== Client characteristics
A client is a program connecting to a <<repository>>.
Each client has exactly one <<participation>> with one repository at one point in time.
The same client can have several consecutive participations with the same repository, but never at the same time.
A client might interact with several repositories, but they are completely independent (i.e. same as two clients connecting to two repositories).{fn-org337}

The client has the responsibility to guarantee uniqueness of <<queryIdType, query ids>> and <<commandIdType, command ids>> within the same participation.

Authentication and authorization are out of scope of this API.

[[channel, channel]]
=== Channel characteristics
Logically, the channel has independent parts for each <<category>> of message;
in practice, we might transmit some or all of them through a shared channel.

This protocol is agnostic of its underlying transport or technical implementation.
By default, this protocol uses JSON encoding over a text-based, single channel, stateful, bi-directional, asynchronous, reliable, and trustworthy transport.{fn-org429}
Any transport that fits these criteria (e.g. WebSocketfootnote:[https://websockets.spec.whatwg.org/]) MUST use the same encoding and MUST adhere to the <<deltaJsonSchema>>.{fn-org428}

We assume the underlying protocol handles quality of service concerns (i.e. guaranteed one-time complete delivery of messages), they are out of scope of this API.

[[participation, participation]]
=== Participation characteristics
Each participation has a _[[participation-id, participation id]]participation id_, unique for all concurrent participations.
The repository assigns the participation id upon starting a new participation.
The participation id MUST follow the same format as <<{m3}.adoc#identifiers, identifier>>.
It serves as a technical identifier.

A participation is transparent for reconnecting network connections,i.e. one participation can survive potential technical reconnects.
A participation spans over time: if we would e.g. used REST, a participation spans over several REST requests/responses.

A participation <<qry-SignOn, starts>> by the client connecting to the repository via delta protocol.
A participation ends either by the <<qry-SignOff, client ending>> it, or if the client disconnects involuntarily (e.g. by crashing or a connection failure).

A client can try to <<qry-Reconnect, reconnect>> a participation if the client still knows a previously valid participation id, and the last <<event-sequence-number>> the client received.{fn-org349}

[[event-sequence-number, event sequence number]]
=== Event sequence numbers
Each event contains a sequence number.{fn-org341}
This number is a positive integer that increments by one for each consecutive event.
It is unique per participation.{fn-org343}
Events SHOULD be sent across the <<channel>> in increasing order of sequence number.

A <<client>> SHOULD use this number to order incoming events, and check whether the client missed any event.

[[subscription, subscription]]
=== Subscription characteristics
The subscription, or subscription scope, is the set of partitions a <<participation>> gets events for.
A subscription does not have an identity on its own; it is bound to one participation.

Scope is defined by the node id of a <<{m3}.adoc#partition, partition>>; it includes all changes to the partition and all its descendants (including annotation instances).{fn-org269}

At the start of a participation, the subscription scope is empty.
A client can change its subscription scope by

* <<qry-ListAndSubscribePartitions, requesting and subscribing to all existing partitions>>,
* <<qry-InformAboutChangingPartitions, being informed about newly created partitions>>,
* <<qry-SubscribeToChangingPartitions, subscribing to newly created partitions>>,
* <<qry-SubscribeToPartitionContents, subscribe>> / <<qry-UnsubscribeFromPartitionContents, unsubscribe>> to a specific partition, or
* <<cmd-AddPartition, adding a new partition>>.

A client can change the subscription scope at any time during a participation.

A client can send commands for any node id, independent of the client's subscription.
Assume a client sends a command for a node that's part of a partition that client is not subscribed to.
The repository treats that command the same as from a client that was subscribed to the containing partition, i.e. applies it in accordance with the repository's policy.
The repository also sends out the same events to subscribed clients, thus _not_ to the sending client.{fn-org352}

[[compositeEvents, composite events]]
==== Composite events
For a <<evnt-CompositeEvent, composite event>>, arising from a <<cmd-CompositeCommand, composite command>>, the following MUST hold:

* Every client gets a composite event with only the events it's subscribed to.
* No client gets an empty composite event.
* The client that sent the composite command always gets the complete composite event, modulo repo changes, e.g. conflict resolutions.

[[message, message]]
=== Message characteristics

[[messageAtomicity]]
.Atomicity
Most messages are atomic; they cannot be split.
The exceptions are <<splittableMessage, splittable messages>>.

[[messageIdentity, message identity]]
.Message identity
Each message has some id unique to the <<participation>> and <<category>>:

* Queries have a <<queryIdType>> (for <<qry-ContinuedQueryResponse>> together with its <<continuedChunkSequenceNumberType>>).
* Commands have a <<commandIdType>> (for <<cmd-ContinuedCommand>> together with its <<continuedChunkSequenceNumberType>>).{fn-org305}
* Events have <<eventSequenceType>> (for <<evnt-ContinuedEvent>> together with its <<continuedChunkSequenceNumberType>>).{fn-org423}{fn-org475}

[[technicalName, technical name]]
.Technical name
Every defined message has a unique _technical name_.
The technical name is a valid programming language identifier as described for <<{m3}.adoc#IKeyed, IKeyed>>.
Each binding to a specific protocol might use the technical name in a different way.
For example, a JSON binding might have a member containing the technical name of the message, or a Protobuf binding might use the technical name as type name.

[[splittableMessage, splittable message]]
==== Splittable messages
All messages containing a <<deltaChunkType>>.

A client or repository CAN decide to split up a _splittable message_ if that message would exceed the acceptable message size.
LionWeb does not define the acceptable message size, it SHOULD be a parameter for each implementation.

All _splittable messages_ MAY contain a <<splitFlagType>> — typically named `split`.
If the flag is unset or `false`, the splittable message is self-contained.
If the flag is `true`, one or more <<continuedChunk>> messages will follow.{fn-org425}

_Splittable messages_ include:

Queries::
* <<qry-SubscribeToPartitionContents>> response <<SubscribeToPartitionContents.contents>>
* <<qry-ListPartitions>> response <<ListPartitions.partitions>>
* <<qry-ListAndSubscribePartitions>> response <<ListAndSubscribePartitions.partitions>>

Commands::
* <<cmd-AddPartition>> <<AddPartition.newPartition>>
* <<cmd-AddChild>> <<AddChild.newChild>>
* <<cmd-ReplaceChild>> <<ReplaceChild.newChild>>
* <<cmd-AddAnnotation>> <<AddAnnotation.parent>>
* <<cmd-ReplaceAnnotation>> <<ReplaceAnnotation.newAnnotation>>

Events::
* <<evnt-PartitionAdded>> <<PartitionAdded.newPartition>>
* <<evnt-ChildAdded>> <<ChildAdded.newChild>>
* <<evnt-ChildReplaced>> <<ChildReplaced.newChild>>
* <<evnt-AnnotationAdded>> <<AnnotationAdded.newAnnotation>>
* <<evnt-AnnotationReplaced>> <<AnnotationReplaced.newAnnotation>>

[[continuedChunk, continued chunk]]
.Continued chunks
_Continued chunks_ continue the chunk from the related <<splittableMessage>>.
Each _continued chunk_ refers to the <<splittableMessage>> it belongs to.
The _continued chunk_ contains a <<deltaChunkType>>, a <<continuedChunkSequenceNumberType>>, and a <<continuedChunkCompletedFlagType>> to signal whether it is the last _continued chunk_, or more will follow.
If the flag is `true`, this is the last _continued chunk_.
If the flag is `false`, one or more _continued chunk_ messages will follow.{fn-org425}
A <<deltaChunkType>> from a continued chunk is to be “merged” into the chunk from the related <<splittableMessage>> simply by appending the contents of its top-level `nodes` field to the `nodes` field of the chunk of the related <<splittableMessage>>.{fn-org473}

There MUST NOT be any message in the same <<channel>> between the _split message_ and all related _continued chunks_.
The continued chunks SHOULD be sent across the <<channel>> in increasing order of <<continuedChunkSequenceNumberType>>.

A continued chunk MUST NOT appear as part of a <<cmd-CompositeCommand>> or <<evnt-CompositeEvent>>.
(That also implies that the <<splitFlagType>> of a <<splittableMessage>> appearing inside a composite MUST either be unset or set to `false`.){fn-org462}

_Continued chunks_ include:

* <<qry-ContinuedQueryResponse>>
* <<cmd-ContinuedCommand>>
* <<evnt-ContinuedEvent>>

.Errors
* Split message already completed: continued chunk received with a higher <<continuedChunkSequenceNumberType>> than a previous one for which the <<continuedChunkSequenceNumberType>> was `true`.
* <<continuedChunkSequenceNumberType>> declared complete more than once: multiple continued chunks (with different <<continuedChunkSequenceNumberType>>s) had their <<continuedChunkCompletedFlagType>> set to `true`.
* Received continued chunk with <<continuedChunkSequenceNumberType>> that was already seen.
* Continued chunk refers to a non-existent query/command/event.
* Continued chunk refers to a query/command/event that’s not splittable or doesn’t have its <<splitFlagType>> set to `true`.
* Received message on this <<channel>> before the sequence of continued chunks had finished.

[[additionalInfo, additional info]]
==== Additional Info
Each message has zero or more _additional infos_ – i.e., these appear as an optionally empty list – consisting of:{fn-org331}{fn-org332}{fn-org430}

* [[additionalInfo.kind]]`kind` is an <<{m3}.adoc#identifiers, identifier>>-compatible string identifying the additional info type.
Some kinds are pre-defined in this specification.
A repository MAY reply with other, additional kinds.
* [[additionalInfo.distribute]]`distribute`? is an optional <<booleanType>> flag with default value `false`.
It is only valid in <<commands>>, i.e. MUST NOT be used for <<events>> or <<queries>>.
If present and set to `true`, the repository MUST copy the additional info to all events that result from the command, and distribute the additional info to all participants receiving the event.

* [[additionalInfo.message]]`message` is a human-readable string describing the additional info.
* [[additionalInfo.data]]`data` is a map with 0 or more arbitrary keys and values.{fn-org471}
All keys MUST be <<{m3}.adoc#identifiers, identifier>>-compatible and MUST be unique within the same additional info.
All values MUST be strings.
A _kind_ might imply the presence of specific keys in `data`.

This additional info is symmetric to <<{bulk}.adoc#additionalInfo, additional infos in bulk API>>.


[[manipulationInsideSingleList, manipulation inside a single list]]
=== Characteristics of manipulation inside a single list

There are two scenarios that involve manipulating a single list, and which benefit from some clarification with regard to how they work index-wise:

1. Moving an item to a different index – the _target_ index – in a list, moving other list items aside as necessary.
2. Moving an item to a different index – the _target_ index – in a list, *and* replacing the list item at that target index.

For both scenarios, assume we have a list of _n_ > 1 items of some type.
In our context, the items would be nodes, and the type one declared by a classifier’s feature.
We also have an _old index_ `oldIndex`, which is an integer from 0 upto n-1.

.Notation/shorthand
We write _l_..._r_ for the set of integers _l_, (_l_ + 1), (_l_ + 2), ..., _r_; which includes _l_ and _r_ themselves.
In effect: `oldIndex` MUST be in 0...(_n_ - 1).


[[justMovingAnItem, moving an item (without replacing)]]
==== Moving an item (without replacing)

In addition to an `oldIndex`, we get passed a `newIndex`: an integer from 0...(_n_ - 1), that is NOT equal to `oldIndex` (as that would mean an idempotent action).
The result of moving the item that’s initially at index `oldIndex` is at index `newIndex` afterwards, with other items moved out of the way, as necessary.

Example (with `newIndex` > `oldIndex`): +
`oldIndex=3`: `A[0] B[1] C[2] *D[3]* E[4] F[5] G[6] H[7]` -> +
`newIndex=5`: `A[0] B[1] C[2] _E[3] F[4]_ *D[5]* _G[6]_ H[7]` +

Example (with `newIndex` < `oldIndex`): +
`oldIndex=3`: `A[0] B[1] C[2] *D[3]* E[4] F[5] G[6] H[7]` -> +
`newIndex=1`: `A[0] *D[1]* _B[2] C[3]_ E[4] F[5] D[5] G[6] H[7]` +

In both cases, only the items with initial indices in min(`oldIndex`, `newIndex`)...max(`oldIndex`, `newIndex`) are affected.
If `newIndex` > `oldIndex`, then the items with initial indices in (`oldIndex` + 1)...`newIndex` are moved to the next lower index.
If `newIndex` < `oldIndex`, then the items with initial indices in `newIndex`..(`oldIndex` - 1) are moved to the next higher index.

// .Pathological cases
//
// `oldIndex=0`: `*A[0]* B[1] C[2] D[3] E[4] F[5] G[6] H[7]` -> +
// `newIndex=7`: `_B[0] C[1] D[2] E[3] F[4] G[5] H[6]_ *A[7]*` +
//
// `oldIndex=7`: `A[0] B[1] C[2] D[3] E[4] F[5] G[6] *H[7]*` -> +
// `newIndex=0`: `*H[0]* _A[1] B[2] C[3] D[4] E[5] F[6] G[7]_` +

// The item at index `oldIndex` is moved `indexOffset` indices forward/down/to the right (if `indexOffset` > 0) or backward/up/to the left (if `indexOffset` < 0), shifting other items out of way.
// The result of moving the item at index `oldIndex` by `indexOffset` indices is the same as moving that item `indexOffset` times 1 index forward/down/to the right (if `indexOffset` > 0), or (-`indexOffset`) times 1 index backward/up/to the left (if `indexOffset` < 0).


[[movingAndReplacing, moving an item and replacing another item]]
==== Moving an item and replacing another item

To avoid any potential ambiguities and misunderstanding, we decided to describe this scenario on the basis of an initial (“old”) situation and an _index offset_ that determines the target index.
So, in addition to an `oldIndex`, we get passed an _index offset_ `indexOffset`, which is an integer unequal to 0, and such that (`oldIndex` + `indexOffset`) is an integer from 0 upto n-1.
Set `targetIndex` = (`oldIndex` + `indexOffset`).

We describe this scenario as a two-step process:

1. The list’s item with index `targetIndex` is set to item with initial index `oldIndex`, overwriting and effectively replacing the item to replace, which gets deleted as a result.
Now, the list contains the same number of items as before, just with two occurrences of the item with initial inde `oldIndex`, namely at indices `oldIndex` and `targetIndex`.
2. The item with index `oldIndex` is removed from the list, with the items after it being moved to the next lower index — this includes the item moved in step 1 itself if (`indexOffset` > 0).
Now, the list contains one less item than before.

For clarity, we can discuss two distinct “sub” scenarios depending on whether `indexOffset` is positive or negative.

*TODO*

