[[events]]
=== Events

[[evnt-partitions]]
==== Partitions

[[evnt-PartitionAdded]]
===== Partition added
Partition <<PartitionAdded.newPartition>> has been added to the repository.

This client is now subscribed to any changes to <<PartitionAdded.newPartition>> or any of its descendants.

[horizontal]
.Parameters
[[PartitionAdded.newPartition, `newPartition`]]newPartition:: <<chunkType>>
[[PartitionAdded.originCommands]]originCommands:: <<commandSourceType>>[]
[[PartitionAdded.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[PartitionAdded.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`PartitionAdded`

.Related command
<<cmd-AddPartition>>

[[evnt-PartitionDeleted]]
===== Partition deleted
Partition <<PartitionDeleted.deletedPartition>>, and all its <<PartitionDeleted.deletedDescendants>>{fn-org370}, have been deleted from the repository.

This client is now unsubscribed from any changes to <<PartitionDeleted.deletedPartition>> or any of its descendants.

[horizontal]
.Parameters
[[PartitionDeleted.deletedPartition, `deletedPartition`]]deletedPartition:: <<targetNodeType>>
[[PartitionDeleted.deletedDescendants, `deletedDescendants`]]deletedDescendants:: <<targetNodeType>>[]
[[PartitionDeleted.originCommands]]originCommands:: <<commandSourceType>>[]
[[PartitionDeleted.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[PartitionDeleted.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`PartitionDeleted`

.Related command
<<cmd-DeletePartition>>

[[evnt-nodes]]
==== Nodes

[[evnt-ClassifierChanged]]
===== Classifier changed
Classifier of <<ClassifierChanged.node>> has been changed from <<ClassifierChanged.oldClassifier>> to <<ClassifierChanged.newClassifier>>.

[horizontal]
.Parameters
[[ClassifierChanged.node, `node`]]node:: <<targetNodeType>>
[[ClassifierChanged.newClassifier, `newClassifier`]]newClassifier:: <<metaPointerType>>
[[ClassifierChanged.oldClassifier, `oldClassifier`]]oldClassifier:: <<metaPointerType>>
[[ClassifierChanged.originCommands]]originCommands:: <<commandSourceType>>[]
[[ClassifierChanged.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[ClassifierChanged.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`ClassifierChanged`

.Related command
<<cmd-ChangeClassifier>>

[[evnt-properties]]
==== Properties

[[evnt-PropertyAdded]]
===== Property added
<<PropertyAdded.property>> of <<PropertyAdded.node>> has been set to <<PropertyAdded.newValue>>.

[horizontal]
.Parameters
[[PropertyAdded.node, `node`]]node:: <<targetNodeType>>
[[PropertyAdded.property, `property`]]property:: <<metaPointerType>>
[[PropertyAdded.newValue, `newValue`]]newValue:: <<propertyValueType>>
[[PropertyAdded.originCommands]]originCommands:: <<commandSourceType>>[]
[[PropertyAdded.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[PropertyAdded.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`PropertyAdded`

.Related command
<<cmd-AddProperty>>

[[evnt-PropertyDeleted]]
===== Property deleted
Existing <<PropertyDeleted.property>> of <<PropertyDeleted.node>> with <<PropertyDeleted.oldValue>> has been deleted.

[horizontal]
.Parameters
[[PropertyDeleted.node, `node`]]node:: <<targetNodeType>>
[[PropertyDeleted.property, `property`]]property:: <<metaPointerType>>
[[PropertyDeleted.oldValue, `oldValue`]]oldValue:: <<propertyValueType>>
[[PropertyDeleted.originCommands]]originCommands:: <<commandSourceType>>[]
[[PropertyDeleted.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[PropertyDeleted.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`PropertyDeleted`

.Related command
<<cmd-DeleteProperty>>

[[evnt-PropertyChanged]]
===== Property changed
Existing <<PropertyChanged.property>> of <<PropertyChanged.node>> has been changed from <<PropertyChanged.oldValue>> to <<PropertyChanged.newValue>>.

[horizontal]
.Parameters
[[PropertyChanged.node, `node`]]node:: <<targetNodeType>>
[[PropertyChanged.property, `property`]]property:: <<metaPointerType>>
[[PropertyChanged.newValue, `newValue`]]newValue:: <<propertyValueType>>
[[PropertyChanged.oldValue, `oldValue`]]oldValue:: <<propertyValueType>>
[[PropertyChanged.originCommands]]originCommands:: <<commandSourceType>>[]
[[PropertyChanged.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[PropertyChanged.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`PropertyChanged`

.Related command
<<cmd-ChangeProperty>>

[[evnt-children]]
==== Children

[[evnt-ChildAdded]]
===== Child added
New node <<ChildAdded.newChild>> has been added to <<ChildAdded.parent>>'s  <<ChildAdded.containment>> at <<ChildAdded.index>>.
<<ChildAdded.newChild>> might be a single node or an arbitrary complex subtree.
All nodes in that subtree MUST be new, i.e. their id MUST NOT exist in the repository.
Nodes in that subtree MAY have references to already existing nodes, and already existing nodes MAY have references to nodes in that subtree.{fn-org326}

All other children inside <<ChildAdded.parent>>'s <<ChildAdded.containment>> with index >= <<ChildAdded.index>> have been moved to next higher index.

[horizontal]
.Parameters
[[ChildAdded.parent, `parent`]]parent:: <<targetNodeType>>
[[ChildAdded.newChild, `newChild`]]newChild:: <<chunkType>>
[[ChildAdded.containment, `containment`]]containment:: <<metaPointerType>>
[[ChildAdded.index, `index`]]index:: <<indexType>>
[[ChildAdded.originCommands]]originCommands:: <<commandSourceType>>[]
[[ChildAdded.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[ChildAdded.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`ChildAdded`

.Related command
<<cmd-AddChild>>

[[evnt-ChildDeleted]]
===== Child deleted
Existing node <<ChildDeleted.deletedChild>>, and all its <<ChildDeleted.deletedDescendants>>{fn-org370}, have been deleted from <<ChildDeleted.parent>>'s <<ChildDeleted.containment>> at <<ChildDeleted.index>>.{fn-org286}
All other children inside <<ChildDeleted.parent>>'s <<ChildDeleted.containment>> with index > <<ChildDeleted.index>> have been moved to next lower index.

[horizontal]
.Parameters
[[ChildDeleted.deletedChild, `deletedChild`]]deletedChild:: <<targetNodeType>>
[[ChildDeleted.deletedDescendants, `deletedDescendants`]]deletedDescendants:: <<targetNodeType>>[]
[[ChildDeleted.parent, `parent`]]parent:: <<targetNodeType>>
[[ChildDeleted.containment, `containment`]]containment:: <<metaPointerType>>
[[ChildDeleted.index, `index`]]index:: <<indexType>>
[[ChildDeleted.originCommands]]originCommands:: <<commandSourceType>>[]
[[ChildDeleted.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[ChildDeleted.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`ChildDeleted`

.Related command
<<cmd-DeleteChild>>

[[evnt-ChildReplaced]]
===== Child replaced
Existing node <<ChildReplaced.replacedChild>>, and all its <<ChildReplaced.replacedDescendants>>{fn-org370}, inside <<ChildReplaced.parent>>'s <<ChildReplaced.containment>> at <<ChildReplaced.index>> has been replaced with new node <<ChildReplaced.newChild>>.
<<ChildReplaced.newChild>> might be a single node or an arbitrary complex subtree.
All nodes in that subtree MUST be new, i.e. their id MUST NOT exist in the repository.
Nodes in that subtree MAY have references to already existing nodes, and already existing nodes MAY have references to nodes in that subtree.{fn-org326}


<<ChildReplaced.replacedChild>>, and all its descendants, have been deleted.

[horizontal]
.Parameters
[[ChildReplaced.newChild, `newChild`]]newChild:: <<chunkType>>
[[ChildReplaced.replacedChild, `replacedChild`]]replacedChild:: <<targetNodeType>>
[[ChildReplaced.replacedDescendants, `replacedDescendants`]]replacedDescendants:: <<targetNodeType>>[]
[[ChildReplaced.parent, `parent`]]parent:: <<targetNodeType>>
[[ChildReplaced.containment, `containment`]]containment:: <<metaPointerType>>
[[ChildReplaced.index, `index`]]index:: <<indexType>>
[[ChildReplaced.originCommands]]originCommands:: <<commandSourceType>>[]
[[ChildReplaced.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[ChildReplaced.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`ChildReplaced`

.Related command
<<cmd-ReplaceChild>>

[[evnt-ChildMovedFromOtherContainment]]
===== Child moved from other containment
Existing node <<ChildMovedFromOtherContainment.movedChild>> (previously inside <<ChildMovedFromOtherContainment.oldParent>>'s <<ChildMovedFromOtherContainment.oldContainment>> at <<ChildMovedFromOtherContainment.oldIndex>>) has been moved
inside <<ChildMovedFromOtherContainment.newParent>>'s <<ChildMovedFromOtherContainment.newContainment>> at <<ChildMovedFromOtherContainment.newIndex>>.

All other children inside <<ChildMovedFromOtherContainment.oldParent>>'s <<ChildMovedFromOtherContainment.oldContainment>> with index > <<ChildMovedFromOtherContainment.oldIndex>> have been moved to next lower index.

All other children inside <<ChildMovedFromOtherContainment.newParent>>'s <<ChildMovedFromOtherContainment.newContainment>> with index >= <<ChildMovedFromOtherContainment.newIndex>> have been moved to next higher index.

[horizontal]
.Parameters
[[ChildMovedFromOtherContainment.newParent, `newParent`]]newParent:: <<targetNodeType>>
[[ChildMovedFromOtherContainment.newContainment, `newContainment`]]newContainment:: <<metaPointerType>>
[[ChildMovedFromOtherContainment.newIndex, `newIndex`]]newIndex:: <<indexType>>
[[ChildMovedFromOtherContainment.movedChild, `movedChild`]]movedChild:: <<targetNodeType>>
[[ChildMovedFromOtherContainment.oldParent, `oldParent`]]oldParent:: <<targetNodeType>>
[[ChildMovedFromOtherContainment.oldContainment, `oldContainment`]]oldContainment:: <<metaPointerType>>
[[ChildMovedFromOtherContainment.oldIndex, `oldIndex`]]oldIndex:: <<indexType>>
[[ChildMovedFromOtherContainment.originCommands]]originCommands:: <<commandSourceType>>[]
[[ChildMovedFromOtherContainment.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[ChildMovedFromOtherContainment.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`ChildMovedFromOtherContainment`

.Related command
<<cmd-MoveChildFromOtherContainment>>

[[evnt-ChildMovedFromOtherContainmentInSameParent]]
===== Child moved from other containment in same parent
Existing node <<ChildMovedFromOtherContainmentInSameParent.movedChild>> (previously inside <<ChildMovedFromOtherContainmentInSameParent.parent>>'s <<ChildMovedFromOtherContainmentInSameParent.oldContainment>> at <<ChildMovedFromOtherContainmentInSameParent.oldIndex>>) has been moved
inside <<ChildMovedFromOtherContainmentInSameParent.parent>>'s <<ChildMovedFromOtherContainmentInSameParent.newContainment>> at <<ChildMovedFromOtherContainmentInSameParent.newIndex>>.

All other children inside <<ChildMovedFromOtherContainmentInSameParent.parent>>'s <<ChildMovedFromOtherContainmentInSameParent.oldContainment>> with index > <<ChildMovedFromOtherContainmentInSameParent.oldIndex>> have been moved to next lower index.

All other children inside <<ChildMovedFromOtherContainmentInSameParent.parent>>'s <<ChildMovedFromOtherContainmentInSameParent.newContainment>> with index >= <<ChildMovedFromOtherContainmentInSameParent.newIndex>> have been moved to next higher index.

[horizontal]
.Parameters
[[ChildMovedFromOtherContainmentInSameParent.newContainment, `newContainment`]]newContainment:: <<metaPointerType>>
[[ChildMovedFromOtherContainmentInSameParent.newIndex, `newIndex`]]newIndex:: <<indexType>>
[[ChildMovedFromOtherContainmentInSameParent.movedChild, `movedChild`]]movedChild:: <<targetNodeType>>
[[ChildMovedFromOtherContainmentInSameParent.parent, `parent`]]parent:: <<targetNodeType>>
[[ChildMovedFromOtherContainmentInSameParent.oldContainment, `oldContainment`]]oldContainment:: <<metaPointerType>>
[[ChildMovedFromOtherContainmentInSameParent.oldIndex, `oldIndex`]]oldIndex:: <<indexType>>
[[ChildMovedFromOtherContainmentInSameParent.originCommands]]originCommands:: <<commandSourceType>>[]
[[ChildMovedFromOtherContainmentInSameParent.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[ChildMovedFromOtherContainmentInSameParent.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`ChildMovedFromOtherContainmentInSameParent`

.Related command
<<cmd-MoveChildFromOtherContainmentInSameParent>>

[[evnt-ChildMovedInSameContainment]]
===== Child moved in same containment
Existing node <<ChildMovedInSameContainment.movedChild>> (previously inside <<ChildMovedInSameContainment.parent>>'s <<ChildMovedInSameContainment.containment>> at <<ChildMovedInSameContainment.oldIndex>>) has been moved
inside <<ChildMovedInSameContainment.parent>>'s <<ChildMovedInSameContainment.containment>> at <<ChildMovedInSameContainment.newIndex>>.

If <<ChildMovedInSameContainment.oldIndex>> < <<ChildMovedInSameContainment.newIndex>>: All other children inside <<ChildMovedInSameContainment.parent>>'s <<ChildMovedInSameContainment.containment>> with previous index > <<ChildMovedInSameContainment.oldIndex>> and previous index <= <<ChildMovedInSameContainment.newIndex>> have been moved to next lower index.
Example: +
`oldIndex=3`: `A[0] B[1] C[2] *X[3]* D[4] E[5] F[6]` -> +
`newIndex=5`: `A[0] B[1] C[2] _D[3] E[4]_ *X[5]* F[6]`

If <<ChildMovedInSameContainment.oldIndex>> > <<ChildMovedInSameContainment.newIndex>>: All other children inside <<ChildMovedInSameContainment.parent>>'s <<ChildMovedInSameContainment.containment>> with previous index >= <<ChildMovedInSameContainment.newIndex>> and previous index < <<ChildMovedInSameContainment.oldIndex>> have been moved to next lower index.
Example: +
`oldIndex=3`: `A[0] B[1] C[2] *X[3]* D[4] E[5] F[6]` -> +
`newIndex=1`: `A[0] *X[1]* _B[2] C[3]_ D[4] E[5] F[6]`

<<ChildMovedInSameContainment.oldIndex>> MUST NOT be equal to <<ChildMovedInSameContainment.newIndex>>.

[horizontal]
.Parameters
[[ChildMovedInSameContainment.newIndex, `newIndex`]]newIndex:: <<indexType>>
[[ChildMovedInSameContainment.movedChild, `movedChild`]]movedChild:: <<targetNodeType>>
[[ChildMovedInSameContainment.parent, `parent`]]parent:: <<targetNodeType>>
[[ChildMovedInSameContainment.containment, `containment`]]containment:: <<metaPointerType>>
[[ChildMovedInSameContainment.oldIndex, `oldIndex`]]oldIndex:: <<indexType>>
[[ChildMovedInSameContainment.originCommands]]originCommands:: <<commandSourceType>>[]
[[ChildMovedInSameContainment.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[ChildMovedInSameContainment.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`ChildMovedInSameContainment`

.Related command
<<cmd-MoveChildInSameContainment>>

[[evnt-ChildMovedAndReplacedFromOtherContainment]]
===== Child moved from other containment and replaced existing child
Existing node <<ChildMovedAndReplacedFromOtherContainment.movedChild>> (previously inside <<ChildMovedAndReplacedFromOtherContainment.oldParent>>'s <<ChildMovedAndReplacedFromOtherContainment.oldContainment>> at <<ChildMovedAndReplacedFromOtherContainment.oldIndex>>) has replaced the existing <<ChildMovedAndReplacedFromOtherContainment.replacedChild>> inside <<ChildMovedAndReplacedFromOtherContainment.newParent>>'s <<ChildMovedAndReplacedFromOtherContainment.newContainment>> at <<ChildMovedAndReplacedFromOtherContainment.newIndex>>.
<<ChildMovedAndReplacedFromOtherContainment.replacedChild>>, and all its <<ChildMovedAndReplacedFromOtherContainment.replacedDescendants>>{fn-org370}, have been deleted.

All other children inside <<ChildMovedAndReplacedFromOtherContainment.oldParent>>'s <<ChildMovedAndReplacedFromOtherContainment.oldContainment>> with index > <<ChildMovedAndReplacedFromOtherContainment.oldIndex>> have been moved to next lower index.

No other children inside <<ChildMovedAndReplacedFromOtherContainment.newParent>>'s <<ChildMovedAndReplacedFromOtherContainment.newContainment>> have been moved.

[horizontal]
.Parameters
[[ChildMovedAndReplacedFromOtherContainment.newParent, `newParent`]]newParent:: <<targetNodeType>>
[[ChildMovedAndReplacedFromOtherContainment.newContainment, `newContainment`]]newContainment:: <<metaPointerType>>
[[ChildMovedAndReplacedFromOtherContainment.newIndex, `newIndex`]]newIndex:: <<indexType>>
[[ChildMovedAndReplacedFromOtherContainment.movedChild, `movedChild`]]movedChild:: <<targetNodeType>>
[[ChildMovedAndReplacedFromOtherContainment.oldParent, `oldParent`]]oldParent:: <<targetNodeType>>
[[ChildMovedAndReplacedFromOtherContainment.oldContainment, `oldContainment`]]oldContainment:: <<metaPointerType>>
[[ChildMovedAndReplacedFromOtherContainment.oldIndex, `oldIndex`]]oldIndex:: <<indexType>>
[[ChildMovedAndReplacedFromOtherContainment.replacedChild, `replacedChild`]]replacedChild:: <<targetNodeType>>
[[ChildMovedAndReplacedFromOtherContainment.replacedDescendants, `replacedDescendants`]]replacedDescendants:: <<targetNodeType>>[]
[[ChildMovedAndReplacedFromOtherContainment.originCommands]]originCommands:: <<commandSourceType>>[]
[[ChildMovedAndReplacedFromOtherContainment.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[ChildMovedAndReplacedFromOtherContainment.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`ChildMovedAndReplacedFromOtherContainment`

.Related command
<<cmd-MoveAndReplaceChildFromOtherContainment>>

[[evnt-ChildMovedAndReplacedFromOtherContainmentInSameParent]]
===== Child moved from other containment in same parent and replaced existing child
Existing node <<ChildMovedAndReplacedFromOtherContainmentInSameParent.movedChild>> (previously inside <<ChildMovedAndReplacedFromOtherContainmentInSameParent.parent>>'s <<ChildMovedAndReplacedFromOtherContainmentInSameParent.oldContainment>> at <<ChildMovedAndReplacedFromOtherContainmentInSameParent.oldIndex>>) has replaced the existing <<ChildMovedAndReplacedFromOtherContainmentInSameParent.replacedChild>> inside <<ChildMovedAndReplacedFromOtherContainmentInSameParent.parent>>'s <<ChildMovedAndReplacedFromOtherContainmentInSameParent.newContainment>> at <<ChildMovedAndReplacedFromOtherContainmentInSameParent.newIndex>>.
<<ChildMovedAndReplacedFromOtherContainmentInSameParent.replacedChild>>, and all its <<ChildMovedAndReplacedFromOtherContainmentInSameParent.replacedDescendants>>{fn-org370}, have been deleted.

All other children inside <<ChildMovedAndReplacedFromOtherContainmentInSameParent.parent>>'s <<ChildMovedAndReplacedFromOtherContainmentInSameParent.oldContainment>> with index > <<ChildMovedAndReplacedFromOtherContainmentInSameParent.oldIndex>> have been moved to next lower index.

No other children inside <<ChildMovedAndReplacedFromOtherContainmentInSameParent.parent>>'s <<ChildMovedAndReplacedFromOtherContainmentInSameParent.newContainment>> have been moved.

[horizontal]
.Parameters
[[ChildMovedAndReplacedFromOtherContainmentInSameParent.newContainment, `newContainment`]]newContainment:: <<metaPointerType>>
[[ChildMovedAndReplacedFromOtherContainmentInSameParent.newIndex, `newIndex`]]newIndex:: <<indexType>>
[[ChildMovedAndReplacedFromOtherContainmentInSameParent.movedChild, `movedChild`]]movedChild:: <<targetNodeType>>
[[ChildMovedAndReplacedFromOtherContainmentInSameParent.parent, `parent`]]parent:: <<targetNodeType>>
[[ChildMovedAndReplacedFromOtherContainmentInSameParent.oldContainment, `oldContainment`]]oldContainment:: <<metaPointerType>>
[[ChildMovedAndReplacedFromOtherContainmentInSameParent.oldIndex, `oldIndex`]]oldIndex:: <<indexType>>
[[ChildMovedAndReplacedFromOtherContainmentInSameParent.replacedChild, `replacedChild`]]replacedChild:: <<targetNodeType>>
[[ChildMovedAndReplacedFromOtherContainmentInSameParent.replacedDescendants, `replacedDescendants`]]replacedDescendants:: <<targetNodeType>>[]
[[ChildMovedAndReplacedFromOtherContainmentInSameParent.originCommands]]originCommands:: <<commandSourceType>>[]
[[ChildMovedAndReplacedFromOtherContainmentInSameParent.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[ChildMovedAndReplacedFromOtherContainmentInSameParent.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`ChildMovedAndReplacedFromOtherContainmentInSameParent`

.Related command
<<cmd-MoveAndReplaceChildFromOtherContainmentInSameParent>>

[[evnt-ChildMovedAndReplacedInSameContainment]]
===== Child moved in same containment and replaced existing child
Existing node <<ChildMovedAndReplacedInSameContainment.movedChild>> (previously inside <<ChildMovedAndReplacedInSameContainment.parent>>'s <<ChildMovedAndReplacedInSameContainment.containment>> at <<ChildMovedAndReplacedInSameContainment.oldIndex>>) has replaced the existing <<ChildMovedAndReplacedInSameContainment.replacedChild>> inside <<ChildMovedAndReplacedInSameContainment.parent>>'s <<ChildMovedAndReplacedInSameContainment.containment>> at <<ChildMovedAndReplacedInSameContainment.newIndex>>.
<<ChildMovedAndReplacedInSameContainment.replacedChild>>, and all its <<ChildMovedAndReplacedInSameContainment.replacedDescendants>>{fn-org370}, have been deleted.

If <<ChildMovedAndReplacedInSameContainment.oldIndex>> < <<ChildMovedAndReplacedInSameContainment.newIndex>>: All other children inside <<ChildMovedAndReplacedInSameContainment.parent>>'s <<ChildMovedAndReplacedInSameContainment.containment>> with previous index > <<ChildMovedAndReplacedInSameContainment.oldIndex>> have been moved to next lower index.
Example: +
`oldIndex=3`: `A[0] B[1] C[2] *X[3]* D[4] E[5] F[6] G[7]` -> +
`newIndex=5`: `A[0] B[1] C[2] _D[3] E[4]_ *X[5]* _G[6]_`

If <<ChildMovedAndReplacedInSameContainment.oldIndex>> > <<ChildMovedAndReplacedInSameContainment.newIndex>>: All other children inside <<ChildMovedAndReplacedInSameContainment.parent>>'s <<ChildMovedAndReplacedInSameContainment.containment>> with previous index >= <<ChildMovedAndReplacedInSameContainment.oldIndex>> have been moved to next lower index.
Example: +
`oldIndex=4`: `A[0] B[1] C[2] D[3] *X[4]* E[5] F[6]` -> +
`newIndex=1`: `A[0] *X[1]* C[2] D[3] _E[4] F[5]_`

<<ChildMovedAndReplacedInSameContainment.oldIndex>> MUST NOT be equal to <<ChildMovedAndReplacedInSameContainment.newIndex>>.

[horizontal]
.Parameters
[[ChildMovedAndReplacedInSameContainment.newIndex, `newIndex`]]newIndex:: <<indexType>>
[[ChildMovedAndReplacedInSameContainment.movedChild, `movedChild`]]movedChild:: <<targetNodeType>>
[[ChildMovedAndReplacedInSameContainment.parent, `parent`]]parent:: <<targetNodeType>>
[[ChildMovedAndReplacedInSameContainment.containment, `containment`]]containment:: <<metaPointerType>>
[[ChildMovedAndReplacedInSameContainment.oldIndex, `oldIndex`]]oldIndex:: <<indexType>>
[[ChildMovedAndReplacedInSameContainment.replacedChild, `replacedChild`]]replacedChild:: <<targetNodeType>>
[[ChildMovedAndReplacedInSameContainment.replacedDescendants, `replacedDescendants`]]replacedDescendants:: <<targetNodeType>>[]
[[ChildMovedAndReplacedInSameContainment.originCommands]]originCommands:: <<commandSourceType>>[]
[[ChildMovedAndReplacedInSameContainment.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[ChildMovedAndReplacedInSameContainment.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`ChildMovedAndReplacedInSameContainment`

.Related command
<<cmd-MoveAndReplaceChildInSameContainment>>

[[evnt-annotations]]
==== Annotations

[[evnt-AnnotationAdded]]
===== Annotation added
New node <<AnnotationAdded.newAnnotation>> has been added to <<AnnotationAdded.parent>>'s annotations at <<AnnotationAdded.index>>.
<<AnnotationAdded.newAnnotation>> might be a single node or an arbitrary complex subtree.
All nodes in that subtree MUST be new, i.e. their id MUST NOT exist in the repository.
Nodes in that subtree MAY have references to already existing nodes, and already existing nodes MAY have references to nodes in that subtree.{fn-org326}

All other annotations inside <<AnnotationAdded.parent>>'s annotations with index >= <<AnnotationAdded.index>> have been moved to next higher index.

[horizontal]
.Parameters
[[AnnotationAdded.parent, `parent`]]parent:: <<targetNodeType>>
[[AnnotationAdded.newAnnotation, `newAnnotation`]]newAnnotation:: <<chunkType>>
[[AnnotationAdded.index, `index`]]index:: <<indexType>>
[[AnnotationAdded.originCommands]]originCommands:: <<commandSourceType>>[]
[[AnnotationAdded.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[AnnotationAdded.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`AnnotationAdded`

.Related command
<<cmd-AddAnnotation>>

[[evnt-AnnotationDeleted]]
===== Annotation deleted
Existing node <<AnnotationDeleted.deletedAnnotation>>, and all its <<AnnotationDeleted.deletedDescendants>>{fn-org370}, have been deleted from <<AnnotationDeleted.parent>>'s annotations at <<AnnotationDeleted.index>>.{fn-org286}
All other annotations inside <<AnnotationDeleted.parent>>'s annotations with index > <<AnnotationDeleted.index>> have been moved to next lower index.

[horizontal]
.Parameters
[[AnnotationDeleted.deletedAnnotation, `deletedAnnotation`]]deletedAnnotation:: <<targetNodeType>>
[[AnnotationDeleted.deletedDescendants, `deletedDescendants`]]deletedDescendants:: <<targetNodeType>>[]
[[AnnotationDeleted.parent, `parent`]]parent:: <<targetNodeType>>
[[AnnotationDeleted.index, `index`]]index:: <<indexType>>
[[AnnotationDeleted.originCommands]]originCommands:: <<commandSourceType>>[]
[[AnnotationDeleted.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[AnnotationDeleted.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`AnnotationDeleted`

.Related command
<<cmd-DeleteAnnotation>>

[[evnt-AnnotationReplaced]]
===== Annotation replaced
Existing node <<AnnotationReplaced.replacedAnnotation>>, and all its <<AnnotationReplaced.replacedDescendants>>{fn-org370}, inside <<AnnotationReplaced.parent>>'s annotations at <<AnnotationReplaced.index>> has been replaced with new node <<AnnotationReplaced.newAnnotation>>.
<<AnnotationReplaced.newAnnotation>> might be a single node or an arbitrary complex subtree.
All nodes in that subtree MUST be new, i.e. their id MUST NOT exist in the repository.
Nodes in that subtree MAY have references to already existing nodes, and already existing nodes MAY have references to nodes in that subtree.{fn-org326}

<<AnnotationReplaced.replacedAnnotation>>, and all its descendants, have been deleted.

[horizontal]
.Parameters
[[AnnotationReplaced.newAnnotation, `newAnnotation`]]newAnnotation:: <<chunkType>>
[[AnnotationReplaced.replacedAnnotation, `replacedAnnotation`]]replacedAnnotation:: <<targetNodeType>>
[[AnnotationReplaced.replacedDescendants, `replacedDescendants`]]replacedDescendants:: <<targetNodeType>>[]
[[AnnotationReplaced.parent, `parent`]]parent:: <<targetNodeType>>
[[AnnotationReplaced.index, `index`]]index:: <<indexType>>
[[AnnotationReplaced.originCommands]]originCommands:: <<commandSourceType>>[]
[[AnnotationReplaced.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[AnnotationReplaced.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`AnnotationReplaced`

.Related command
<<cmd-ReplaceAnnotation>>

[[evnt-AnnotationMovedFromOtherParent]]
===== Annotation moved from other parent
Existing node <<AnnotationMovedFromOtherParent.movedAnnotation>> (previously inside <<AnnotationMovedFromOtherParent.oldParent>>'s annotations at <<AnnotationMovedFromOtherParent.oldIndex>>) has been moved
inside <<AnnotationMovedFromOtherParent.newParent>>'s annotations at <<AnnotationMovedFromOtherParent.newIndex>>.

All other annotations inside <<AnnotationMovedFromOtherParent.oldParent>>'s annotations with index > <<AnnotationMovedFromOtherParent.oldIndex>> have been moved to next lower index.

All other annotations inside <<AnnotationMovedFromOtherParent.newParent>>'s annotations with index >= <<AnnotationMovedFromOtherParent.newIndex>> have been moved to next higher index.

[horizontal]
.Parameters
[[AnnotationMovedFromOtherParent.newParent, `newParent`]]newParent:: <<targetNodeType>>
[[AnnotationMovedFromOtherParent.newIndex, `newIndex`]]newIndex:: <<indexType>>
[[AnnotationMovedFromOtherParent.movedAnnotation, `movedAnnotation`]]movedAnnotation:: <<targetNodeType>>
[[AnnotationMovedFromOtherParent.oldParent, `oldParent`]]oldParent:: <<targetNodeType>>
[[AnnotationMovedFromOtherParent.oldIndex, `oldIndex`]]oldIndex:: <<indexType>>
[[AnnotationMovedFromOtherParent.originCommands]]originCommands:: <<commandSourceType>>[]
[[AnnotationMovedFromOtherParent.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[AnnotationMovedFromOtherParent.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`AnnotationMovedFromOtherParent`

.Related command
<<cmd-MoveAnnotationFromOtherParent>>

[[evnt-AnnotationMovedInSameParent]]
===== Annotation moved in same parent
Existing node <<AnnotationMovedInSameParent.movedAnnotation>> (previously inside <<AnnotationMovedInSameParent.parent>>'s annotations at <<AnnotationMovedInSameParent.oldIndex>>) has been moved inside <<AnnotationMovedInSameParent.parent>>'s annotations at <<AnnotationMovedInSameParent.newIndex>>.

If <<AnnotationMovedInSameParent.oldIndex>> < <<AnnotationMovedInSameParent.newIndex>>: All other annotations inside <<AnnotationMovedInSameParent.parent>>'s annotations with previous index > <<AnnotationMovedInSameParent.oldIndex>> and previous index <= <<AnnotationMovedInSameParent.newIndex>> have been moved to next lower index.
Example: +
`oldIndex=3`: `A[0] B[1] C[2] *X[3]* D[4] E[5] F[6]` -> +
`newIndex=5`: `A[0] B[1] C[2] _D[3] E[4]_ *X[5]* F[6]`

If <<AnnotationMovedInSameParent.oldIndex>> > <<AnnotationMovedInSameParent.newIndex>>: All other annotations inside <<AnnotationMovedInSameParent.parent>>'s annotations with previous index >= <<AnnotationMovedInSameParent.newIndex>> and previous index < <<AnnotationMovedInSameParent.oldIndex>> have been moved to next lower index.
Example: +
`oldIndex=3`: `A[0] B[1] C[2] *X[3]* D[4] E[5] F[6]` -> +
`newIndex=1`: `A[0] *X[1]* _B[2] C[3]_ D[4] E[5] F[6]`

<<AnnotationMovedInSameParent.oldIndex>> MUST NOT be equal to <<AnnotationMovedInSameParent.newIndex>>.

[horizontal]
.Parameters
[[AnnotationMovedInSameParent.newIndex, `newIndex`]]newIndex:: <<indexType>>
[[AnnotationMovedInSameParent.movedAnnotation, `movedAnnotation`]]movedAnnotation:: <<targetNodeType>>
[[AnnotationMovedInSameParent.parent, `parent`]]parent:: <<targetNodeType>>
[[AnnotationMovedInSameParent.oldIndex, `oldIndex`]]oldIndex:: <<targetNodeType>>
[[AnnotationMovedInSameParent.originCommands]]originCommands:: <<commandSourceType>>[]
[[AnnotationMovedInSameParent.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[AnnotationMovedInSameParent.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`AnnotationMovedInSameParent`

.Related command
<<cmd-MoveAnnotationInSameParent>>

[[evnt-AnnotationMovedAndReplacedFromOtherParent]]
===== Annotation moved from other parent and replaced existing annotation
Existing node <<AnnotationMovedAndReplacedFromOtherParent.movedAnnotation>> (previously inside <<AnnotationMovedAndReplacedFromOtherParent.oldParent>>'s annotations at <<AnnotationMovedAndReplacedFromOtherParent.oldIndex>>) has replaced the existing <<AnnotationMovedAndReplacedFromOtherParent.replacedAnnotation>> inside <<AnnotationMovedAndReplacedFromOtherParent.newParent>>'s annotations at <<AnnotationMovedAndReplacedFromOtherParent.newIndex>>.
<<AnnotationMovedAndReplacedFromOtherParent.replacedAnnotation>>, and all its <<AnnotationMovedAndReplacedFromOtherParent.replacedDescendants>>{fn-org370}, have been deleted.

All other annotations inside <<AnnotationMovedAndReplacedFromOtherParent.oldParent>>'s annotations with index > <<AnnotationMovedAndReplacedFromOtherParent.oldIndex>> have been moved to next lower index.

No other annotations inside <<AnnotationMovedAndReplacedFromOtherParent.newParent>>'s annotations have been moved.

[horizontal]
.Parameters
[[AnnotationMovedAndReplacedFromOtherParent.newParent, `newParent`]]newParent:: <<targetNodeType>>
[[AnnotationMovedAndReplacedFromOtherParent.newIndex, `newIndex`]]newIndex:: <<indexType>>
[[AnnotationMovedAndReplacedFromOtherParent.movedAnnotation, `movedAnnotation`]]movedAnnotation:: <<targetNodeType>>
[[AnnotationMovedAndReplacedFromOtherParent.oldParent, `oldParent`]]oldParent:: <<targetNodeType>>
[[AnnotationMovedAndReplacedFromOtherParent.oldIndex, `oldIndex`]]oldIndex:: <<indexType>>
[[AnnotationMovedAndReplacedFromOtherParent.replacedAnnotation, `replacedAnnotation`]]replacedAnnotation:: <<targetNodeType>>
[[AnnotationMovedAndReplacedFromOtherParent.replacedDescendants, `replacedDescendants`]]replacedDescendants:: <<targetNodeType>>[]
[[AnnotationMovedAndReplacedFromOtherParent.originCommands]]originCommands:: <<commandSourceType>>[]
[[AnnotationMovedAndReplacedFromOtherParent.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[AnnotationMovedAndReplacedFromOtherParent.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`AnnotationMovedAndReplacedFromOtherParent`

.Related command
<<cmd-MoveAndReplaceAnnotationFromOtherParent>>

[[evnt-AnnotationMovedAndReplacedInSameParent]]
===== Annotation moved in same parent and replaced existing annotation
Existing node <<AnnotationMovedAndReplacedInSameParent.movedAnnotation>> (previously inside <<AnnotationMovedAndReplacedInSameParent.parent>>'s annotations at <<AnnotationMovedAndReplacedInSameParent.oldIndex>>) has replaced the existing <<AnnotationMovedAndReplacedInSameParent.replacedAnnotation>> inside <<AnnotationMovedAndReplacedInSameParent.parent>>'s annotations at <<AnnotationMovedAndReplacedInSameParent.newIndex>>.
<<AnnotationMovedAndReplacedInSameParent.replacedAnnotation>>, and all its <<AnnotationMovedAndReplacedInSameParent.replacedDescendants>>{fn-org370}, have been deleted.

If <<AnnotationMovedAndReplacedInSameParent.oldIndex>> < <<AnnotationMovedAndReplacedInSameParent.newIndex>>: All other annotations inside <<AnnotationMovedAndReplacedInSameParent.parent>>'s annotations with previous index > <<AnnotationMovedAndReplacedInSameParent.oldIndex>> have been moved to next lower index.
Example: +
`oldIndex=3`: `A[0] B[1] C[2] *X[3]* D[4] E[5] F[6] G[7]` -> +
`newIndex=5`: `A[0] B[1] C[2] _D[3] E[4]_ *X[5]* _G[6]_`

If <<AnnotationMovedAndReplacedInSameParent.oldIndex>> > <<AnnotationMovedAndReplacedInSameParent.newIndex>>: All other annotations inside <<AnnotationMovedAndReplacedInSameParent.parent>>'s annotations with previous index >= <<AnnotationMovedAndReplacedInSameParent.oldIndex>> have been moved to next lower index.
Example: +
`oldIndex=4`: `A[0] B[1] C[2] D[3] *X[4]* E[5] F[6]` -> +
`newIndex=1`: `A[0] *X[1]* C[2] D[3] _E[4] F[5]_`

<<AnnotationMovedAndReplacedInSameParent.oldIndex>> MUST NOT be equal to <<AnnotationMovedAndReplacedInSameParent.newIndex>>.

[horizontal]
.Parameters
[[AnnotationMovedAndReplacedInSameParent.newIndex, `newIndex`]]newIndex:: <<indexType>>
[[AnnotationMovedAndReplacedInSameParent.movedAnnotation, `movedAnnotation`]]movedAnnotation:: <<targetNodeType>>
[[AnnotationMovedAndReplacedInSameParent.parent, `parent`]]parent:: <<targetNodeType>>
[[AnnotationMovedAndReplacedInSameParent.oldIndex, `oldIndex`]]oldIndex:: <<targetNodeType>>
[[AnnotationMovedAndReplacedInSameParent.replacedAnnotation, `replacedAnnotation`]]replacedAnnotation:: <<targetNodeType>>
[[AnnotationMovedAndReplacedInSameParent.replacedDescendants, `replacedDescendants`]]replacedDescendants:: <<targetNodeType>>[]
[[AnnotationMovedAndReplacedInSameParent.originCommands]]originCommands:: <<commandSourceType>>[]
[[AnnotationMovedAndReplacedInSameParent.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[AnnotationMovedAndReplacedInSameParent.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`AnnotationMovedAndReplacedInSameParent`

.Related command
<<cmd-MoveAndReplaceAnnotationInSameParent>>

[[evnt-references]]
==== References

[[evnt-ReferenceAdded]]
===== Reference added
Reference with <<ReferenceAdded.newTarget>>/<<ReferenceAdded.newResolveInfo>> has been added to <<ReferenceAdded.parent>>'s <<ReferenceAdded.reference>> at <<ReferenceAdded.index>>.
All other entries inside <<ReferenceAdded.parent>>'s <<ReferenceAdded.reference>> with index >= <<ReferenceAdded.index>> have been moved to next higher index.

[horizontal]
.Parameters
[[ReferenceAdded.parent, `parent`]]parent:: <<targetNodeType>>
[[ReferenceAdded.reference, `reference`]]reference:: <<metaPointerType>>
[[ReferenceAdded.index, `index`]]index:: <<indexType>>
[[ReferenceAdded.newTarget, `newTarget`]]newTarget:: <<targetNodeType>>?
[[ReferenceAdded.newResolveInfo, `newResolveInfo`]]newResolveInfo:: <<resolveInfoType>>?
[[ReferenceAdded.originCommands]]originCommands:: <<commandSourceType>>[]
[[ReferenceAdded.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[ReferenceAdded.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`ReferenceAdded`

.Related command
<<cmd-AddReference>>

[[evnt-ReferenceDeleted]]
===== Reference deleted
Existing reference with <<ReferenceDeleted.deletedTarget>>/<<ReferenceDeleted.deletedResolveInfo>> has been deleted from <<ReferenceDeleted.parent>>'s <<ReferenceDeleted.reference>> at <<ReferenceDeleted.index>>.
All other entries inside <<ReferenceDeleted.parent>>'s <<ReferenceDeleted.reference>> with index > <<ReferenceDeleted.index>> have been moved to next lower index.

[horizontal]
.Parameters
[[ReferenceDeleted.parent, `parent`]]parent:: <<targetNodeType>>
[[ReferenceDeleted.reference, `reference`]]reference:: <<metaPointerType>>
[[ReferenceDeleted.index, `index`]]index:: <<indexType>>
[[ReferenceDeleted.deletedTarget, `deletedTarget`]]deletedTarget:: <<targetNodeType>>?
[[ReferenceDeleted.deletedResolveInfo, `deletedResolveInfo`]]deletedResolveInfo:: <<resolveInfoType>>?
[[ReferenceDeleted.originCommands]]originCommands:: <<commandSourceType>>[]
[[ReferenceDeleted.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[ReferenceDeleted.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`ReferenceDeleted`

.Related command
<<cmd-DeleteReference>>

[[evnt-ReferenceChanged]]
===== Reference changed
Existing reference with <<ReferenceChanged.replacedTarget>>/<<ReferenceChanged.replacedResolveInfo>> inside <<ReferenceChanged.parent>>'s annotations at <<ReferenceChanged.index>> has been replaced with <<ReferenceChanged.newTarget>>/<<ReferenceChanged.newResolveInfo>>.

[horizontal]
.Parameters
[[ReferenceChanged.parent, `parent`]]parent:: <<targetNodeType>>
[[ReferenceChanged.reference, `reference`]]reference:: <<metaPointerType>>
[[ReferenceChanged.index, `index`]]index:: <<indexType>>
[[ReferenceChanged.newTarget, `newTarget`]]newTarget:: <<targetNodeType>>?
[[ReferenceChanged.newResolveInfo, `newResolveInfo`]]newResolveInfo:: <<targetNodeType>>?
[[ReferenceChanged.replacedTarget, `replacedTarget`]]replacedTarget:: <<targetNodeType>>?
[[ReferenceChanged.replacedResolveInfo, `replacedResolveInfo`]]replacedResolveInfo:: <<resolveInfoType>>?
[[ReferenceChanged.originCommands]]originCommands:: <<commandSourceType>>[]
[[ReferenceChanged.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[ReferenceChanged.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`ReferenceChanged`

.Related command
<<cmd-ChangeReference>>

[[evnt-EntryMovedFromOtherReference]]
===== Entry moved from other reference
Existing reference <<EntryMovedFromOtherReference.target>>/<<EntryMovedFromOtherReference.resolveInfo>> (previously inside <<EntryMovedFromOtherReference.oldParent>>'s <<EntryMovedFromOtherReference.oldReference>> at <<EntryMovedFromOtherReference.oldIndex>>) has been moved
to <<EntryMovedFromOtherReference.newParent>>'s <<EntryMovedFromOtherReference.newReference>> at <<EntryMovedFromOtherReference.newIndex>>.

All other entries inside <<EntryMovedFromOtherReference.oldParent>>'s <<EntryMovedFromOtherReference.oldReference>> with index > <<EntryMovedFromOtherReference.oldIndex>> have been moved to next lower index.

All other entries inside <<EntryMovedFromOtherReference.newParent>>'s <<EntryMovedFromOtherReference.newReference>> with index >= <<EntryMovedFromOtherReference.newIndex>> have been moved to next higher index.

[horizontal]
.Parameters
[[EntryMovedFromOtherReference.newParent, `newParent`]]newParent:: <<targetNodeType>>
[[EntryMovedFromOtherReference.newReference, `newReference`]]newReference:: <<metaPointerType>>
[[EntryMovedFromOtherReference.newIndex, `newIndex`]]newIndex:: <<indexType>>
[[EntryMovedFromOtherReference.oldParent, `oldParent`]]oldParent:: <<targetNodeType>>
[[EntryMovedFromOtherReference.oldReference, `oldReference`]]oldReference:: <<metaPointerType>>
[[EntryMovedFromOtherReference.oldIndex, `oldIndex`]]oldIndex:: <<indexType>>
[[EntryMovedFromOtherReference.target, `target`]]target:: <<targetNodeType>>?
[[EntryMovedFromOtherReference.resolveInfo, `resolveInfo`]]resolveInfo:: <<resolveInfoType>>?
[[EntryMovedFromOtherReference.originCommands]]originCommands:: <<commandSourceType>>[]
[[EntryMovedFromOtherReference.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[EntryMovedFromOtherReference.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`EntryMovedFromOtherReference`

.Related command
<<cmd-MoveEntryFromOtherReference>>

[[evnt-EntryMovedFromOtherReferenceInSameParent]]
===== Entry moved from other reference in same parent
Existing reference <<EntryMovedFromOtherReferenceInSameParent.target>>/<<EntryMovedFromOtherReferenceInSameParent.resolveInfo>> (previously inside <<EntryMovedFromOtherReferenceInSameParent.parent>>'s <<EntryMovedFromOtherReferenceInSameParent.oldReference>> at <<EntryMovedFromOtherReferenceInSameParent.oldIndex>>) has been moved
to <<EntryMovedFromOtherReferenceInSameParent.parent>>'s <<EntryMovedFromOtherReferenceInSameParent.newReference>> at <<EntryMovedFromOtherReferenceInSameParent.newIndex>>.

All other entries inside <<EntryMovedFromOtherReferenceInSameParent.parent>>'s <<EntryMovedFromOtherReferenceInSameParent.oldReference>> with index > <<EntryMovedFromOtherReferenceInSameParent.oldIndex>> have been moved to next lower index.

All other entries inside <<EntryMovedFromOtherReferenceInSameParent.parent>>'s <<EntryMovedFromOtherReferenceInSameParent.newReference>> with index >= <<EntryMovedFromOtherReferenceInSameParent.newIndex>> have been moved to next higher index.

[horizontal]
.Parameters
[[EntryMovedFromOtherReferenceInSameParent.parent, `parent`]]parent:: <<targetNodeType>>
[[EntryMovedFromOtherReferenceInSameParent.newReference, `newReference`]]newReference:: <<metaPointerType>>
[[EntryMovedFromOtherReferenceInSameParent.newIndex, `newIndex`]]newIndex:: <<indexType>>
[[EntryMovedFromOtherReferenceInSameParent.oldReference, `oldReference`]]oldReference:: <<metaPointerType>>
[[EntryMovedFromOtherReferenceInSameParent.oldIndex, `oldIndex`]]oldIndex:: <<indexType>>
[[EntryMovedFromOtherReferenceInSameParent.target, `target`]]target:: <<targetNodeType>>?
[[EntryMovedFromOtherReferenceInSameParent.resolveInfo, `resolveInfo`]]resolveInfo:: <<resolveInfoType>>?
[[EntryMovedFromOtherReferenceInSameParent.originCommands]]originCommands:: <<commandSourceType>>[]
[[EntryMovedFromOtherReferenceInSameParent.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[EntryMovedFromOtherReferenceInSameParent.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`EntryMovedFromOtherReferenceInSameParent`

.Related command
<<cmd-MoveEntryFromOtherReferenceInSameParent>>

[[evnt-EntryMovedInSameReference]]
===== Entry moved in same reference
Existing reference <<EntryMovedInSameReference.target>>/<<EntryMovedInSameReference.resolveInfo>> (previously inside <<EntryMovedInSameReference.parent>>'s <<EntryMovedInSameReference.reference>> at <<EntryMovedInSameReference.oldIndex>>) has been moved
to <<EntryMovedInSameReference.parent>>'s <<EntryMovedInSameReference.reference>> at <<EntryMovedInSameReference.newIndex>>.

If <<EntryMovedInSameReference.oldIndex>> < <<EntryMovedInSameReference.newIndex>>: All other entries inside <<EntryMovedInSameReference.parent>>'s <<EntryMovedInSameReference.reference>> with previous index > <<EntryMovedInSameReference.oldIndex>> and previous index <= <<EntryMovedInSameReference.newIndex>> have been moved to next lower index.
Example: +
`oldIndex=3`: `A[0] B[1] C[2] *X[3]* D[4] E[5] F[6]` -> +
`newIndex=5`: `A[0] B[1] C[2] _D[3] E[4]_ *X[5]* F[6]`

If <<EntryMovedInSameReference.oldIndex>> > <<EntryMovedInSameReference.newIndex>>: All other entries inside <<EntryMovedInSameReference.parent>>'s <<EntryMovedInSameReference.reference>> with previous index >= <<EntryMovedInSameReference.newIndex>> and previous index < <<EntryMovedInSameReference.oldIndex>> have been moved to next lower index.
Example: +
`oldIndex=3`: `A[0] B[1] C[2] *X[3]* D[4] E[5] F[6]` -> +
`newIndex=1`: `A[0] *X[1]* _B[2] C[3]_ D[4] E[5] F[6]`

<<EntryMovedInSameReference.oldIndex>> MUST NOT be equal to <<EntryMovedInSameReference.newIndex>>.

[horizontal]
.Parameters
[[EntryMovedInSameReference.parent, `parent`]]parent:: <<targetNodeType>>
[[EntryMovedInSameReference.reference, `reference`]]reference:: <<metaPointerType>>
[[EntryMovedInSameReference.oldIndex, `oldIndex`]]oldIndex:: <<indexType>>
[[EntryMovedInSameReference.newIndex, `newIndex`]]newIndex:: <<indexType>>
[[EntryMovedInSameReference.target, `target`]]target:: <<targetNodeType>>?
[[EntryMovedInSameReference.resolveInfo, `resolveInfo`]]resolveInfo:: <<resolveInfoType>>?
[[EntryMovedInSameReference.originCommands]]originCommands:: <<commandSourceType>>[]
[[EntryMovedInSameReference.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[EntryMovedInSameReference.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`EntryMovedInSameReference`

.Related command
<<cmd-MoveEntryInSameReference>>

[[evnt-EntryMovedAndReplacedFromOtherReference]]
===== Entry moved from other reference and replaced existing entry
Existing reference <<EntryMovedAndReplacedFromOtherReference.movedTarget>>/<<EntryMovedAndReplacedFromOtherReference.movedResolveInfo>> (previously inside <<EntryMovedAndReplacedFromOtherReference.oldParent>>'s <<EntryMovedAndReplacedFromOtherReference.oldReference>> at <<EntryMovedAndReplacedFromOtherReference.oldIndex>>) has replaced existing <<EntryMovedAndReplacedFromOtherReference.replacedTarget>>/<<EntryMovedAndReplacedFromOtherReference.replacedResolveInfo>> at <<EntryMovedAndReplacedFromOtherReference.newParent>>'s <<EntryMovedAndReplacedFromOtherReference.newReference>> at <<EntryMovedAndReplacedFromOtherReference.newIndex>>.

All other entries inside <<EntryMovedAndReplacedFromOtherReference.oldParent>>'s <<EntryMovedAndReplacedFromOtherReference.oldReference>> with index > <<EntryMovedAndReplacedFromOtherReference.oldIndex>> have been moved to next lower index.

No other entries inside <<EntryMovedAndReplacedFromOtherReference.newParent>>'s <<EntryMovedAndReplacedFromOtherReference.newReference>> have been moved.

[horizontal]
.Parameters
[[EntryMovedAndReplacedFromOtherReference.newParent, `newParent`]]newParent:: <<targetNodeType>>
[[EntryMovedAndReplacedFromOtherReference.newReference, `newReference`]]newReference:: <<metaPointerType>>
[[EntryMovedAndReplacedFromOtherReference.newIndex, `newIndex`]]newIndex:: <<indexType>>
[[EntryMovedAndReplacedFromOtherReference.movedTarget, `movedTarget`]]movedTarget:: <<targetNodeType>>?
[[EntryMovedAndReplacedFromOtherReference.movedResolveInfo, `movedResolveInfo`]]movedResolveInfo:: <<resolveInfoType>>?
[[EntryMovedAndReplacedFromOtherReference.oldParent, `oldParent`]]oldParent:: <<targetNodeType>>
[[EntryMovedAndReplacedFromOtherReference.oldReference, `oldReference`]]oldReference:: <<metaPointerType>>
[[EntryMovedAndReplacedFromOtherReference.oldIndex, `oldIndex`]]oldIndex:: <<indexType>>
[[EntryMovedAndReplacedFromOtherReference.replacedTarget, `replacedTarget`]]replacedTarget:: <<targetNodeType>>?
[[EntryMovedAndReplacedFromOtherReference.replacedResolveInfo, `replacedResolveInfo`]]replacedResolveInfo:: <<resolveInfoType>>?
[[EntryMovedAndReplacedFromOtherReference.originCommands]]originCommands:: <<commandSourceType>>[]
[[EntryMovedAndReplacedFromOtherReference.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[EntryMovedAndReplacedFromOtherReference.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`EntryMovedAndReplacedFromOtherReference`

.Related command
<<cmd-MoveAndReplaceEntryFromOtherReference>>

[[evnt-EntryMovedAndReplacedFromOtherReferenceInSameParent]]
===== Entry moved from other reference in same parent and replaced existing entry
Existing reference <<EntryMovedAndReplacedFromOtherReferenceInSameParent.movedTarget>>/<<EntryMovedAndReplacedFromOtherReferenceInSameParent.movedResolveInfo>> (previously inside <<EntryMovedAndReplacedFromOtherReferenceInSameParent.parent>>'s <<EntryMovedAndReplacedFromOtherReferenceInSameParent.oldReference>> at <<EntryMovedAndReplacedFromOtherReferenceInSameParent.oldIndex>>) has replaced existing <<EntryMovedAndReplacedFromOtherReferenceInSameParent.replacedTarget>>/<<EntryMovedAndReplacedFromOtherReferenceInSameParent.replacedResolveInfo>> at <<EntryMovedAndReplacedFromOtherReferenceInSameParent.parent>>'s <<EntryMovedAndReplacedFromOtherReferenceInSameParent.newReference>> at <<EntryMovedAndReplacedFromOtherReferenceInSameParent.newIndex>>.

All other entries inside <<EntryMovedAndReplacedFromOtherReferenceInSameParent.parent>>'s <<EntryMovedAndReplacedFromOtherReferenceInSameParent.oldReference>> with index > <<EntryMovedAndReplacedFromOtherReferenceInSameParent.oldIndex>> have been moved to next lower index.

No other entries inside <<EntryMovedAndReplacedFromOtherReferenceInSameParent.parent>>'s <<EntryMovedAndReplacedFromOtherReferenceInSameParent.newReference>> have been moved.

[horizontal]
.Parameters
[[EntryMovedAndReplacedFromOtherReferenceInSameParent.parent, `parent`]]parent:: <<targetNodeType>>
[[EntryMovedAndReplacedFromOtherReferenceInSameParent.newReference, `newReference`]]newReference:: <<metaPointerType>>
[[EntryMovedAndReplacedFromOtherReferenceInSameParent.newIndex, `newIndex`]]newIndex:: <<indexType>>
[[EntryMovedAndReplacedFromOtherReferenceInSameParent.movedTarget, `movedTarget`]]movedTarget:: <<targetNodeType>>?
[[EntryMovedAndReplacedFromOtherReferenceInSameParent.movedResolveInfo, `movedResolveInfo`]]movedResolveInfo:: <<resolveInfoType>>?
[[EntryMovedAndReplacedFromOtherReferenceInSameParent.oldReference, `oldReference`]]oldReference:: <<metaPointerType>>
[[EntryMovedAndReplacedFromOtherReferenceInSameParent.oldIndex, `oldIndex`]]oldIndex:: <<indexType>>
[[EntryMovedAndReplacedFromOtherReferenceInSameParent.replacedTarget, `replacedTarget`]]replacedTarget:: <<targetNodeType>>?
[[EntryMovedAndReplacedFromOtherReferenceInSameParent.replacedResolveInfo, `replacedResolveInfo`]]replacedResolveInfo:: <<resolveInfoType>>?
[[EntryMovedAndReplacedFromOtherReferenceInSameParent.originCommands]]originCommands:: <<commandSourceType>>[]
[[EntryMovedAndReplacedFromOtherReferenceInSameParent.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[EntryMovedAndReplacedFromOtherReferenceInSameParent.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`EntryMovedAndReplacedFromOtherReferenceInSameParent`

.Related command
<<cmd-MoveAndReplaceEntryFromOtherReferenceInSameParent>>

[[evnt-EntryMovedAndReplacedInSameReference]]
===== Entry moved in same reference and replaced existing entry
Existing reference <<EntryMovedAndReplacedInSameReference.movedTarget>>/<<EntryMovedAndReplacedInSameReference.movedResolveInfo>> (previously inside <<EntryMovedAndReplacedInSameReference.parent>>'s <<EntryMovedAndReplacedInSameReference.reference>> at <<EntryMovedAndReplacedInSameReference.oldIndex>>) has replaced existing <<EntryMovedAndReplacedInSameReference.replacedTarget>>/<<EntryMovedAndReplacedInSameReference.replacedResolveInfo>> at <<EntryMovedAndReplacedInSameReference.parent>>'s <<EntryMovedAndReplacedInSameReference.reference>> at <<EntryMovedAndReplacedInSameReference.newIndex>>.

If <<EntryMovedAndReplacedInSameReference.oldIndex>> < <<EntryMovedAndReplacedInSameReference.newIndex>>: All other entries inside <<EntryMovedAndReplacedInSameReference.parent>>'s <<EntryMovedAndReplacedInSameReference.reference>> with previous index > <<EntryMovedAndReplacedInSameReference.oldIndex>> have been moved to next lower index.
Example: +
`oldIndex=3`: `A[0] B[1] C[2] *X[3]* D[4] E[5] F[6] G[7]` -> +
`newIndex=5`: `A[0] B[1] C[2] _D[3] E[4]_ *X[5]* _G[6]_`

If <<EntryMovedAndReplacedInSameReference.oldIndex>> > <<EntryMovedAndReplacedInSameReference.newIndex>>: All other entries inside <<EntryMovedAndReplacedInSameReference.parent>>'s <<EntryMovedAndReplacedInSameReference.reference>> with previous index >= <<EntryMovedAndReplacedInSameReference.oldIndex>> have been moved to next lower index.
Example: +
`oldIndex=4`: `A[0] B[1] C[2] D[3] *X[4]* E[5] F[6]` -> +
`newIndex=1`: `A[0] *X[1]* C[2] D[3] _E[4] F[5]_`

<<EntryMovedAndReplacedInSameReference.oldIndex>> MUST NOT be equal to <<EntryMovedAndReplacedInSameReference.newIndex>>.

[horizontal]
.Parameters
[[EntryMovedAndReplacedInSameReference.parent, `parent`]]parent:: <<targetNodeType>>
[[EntryMovedAndReplacedInSameReference.reference, `reference`]]reference:: <<metaPointerType>>
[[EntryMovedAndReplacedInSameReference.newIndex, `newIndex`]]newIndex:: <<indexType>>
[[EntryMovedAndReplacedInSameReference.movedTarget, `movedTarget`]]movedTarget:: <<targetNodeType>>?
[[EntryMovedAndReplacedInSameReference.movedResolveInfo, `movedResolveInfo`]]movedResolveInfo:: <<resolveInfoType>>?
[[EntryMovedAndReplacedInSameReference.oldIndex, `oldIndex`]]oldIndex:: <<indexType>>
[[EntryMovedAndReplacedInSameReference.replacedTarget, `replacedTarget`]]replacedTarget:: <<targetNodeType>>?
[[EntryMovedAndReplacedInSameReference.replacedResolveInfo, `replacedResolveInfo`]]replacedResolveInfo:: <<resolveInfoType>>?
[[EntryMovedAndReplacedInSameReference.originCommands]]originCommands:: <<commandSourceType>>[]
[[EntryMovedAndReplacedInSameReference.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[EntryMovedAndReplacedInSameReference.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`EntryMovedAndReplacedInSameReference`

.Related command
<<cmd-MoveAndReplaceEntryInSameReference>>

[[evnt-ReferenceResolveInfoAdded]]
===== Reference ResolveInfo added
<<ReferenceResolveInfoAdded.newResolveInfo>> has been added as ResolveInfo to existing entry inside <<ReferenceResolveInfoAdded.parent>>'s <<ReferenceResolveInfoAdded.reference>> at <<ReferenceResolveInfoAdded.index>> with <<ReferenceResolveInfoAdded.target>>.

[horizontal]
.Parameters
[[ReferenceResolveInfoAdded.parent, `parent`]]parent:: <<targetNodeType>>
[[ReferenceResolveInfoAdded.reference, `reference`]]reference:: <<metaPointerType>>
[[ReferenceResolveInfoAdded.index, `index`]]index:: <<indexType>>
[[ReferenceResolveInfoAdded.newResolveInfo, `newResolveInfo`]]newResolveInfo:: <<resolveInfoType>>
[[ReferenceResolveInfoAdded.target, `target`]]target:: <<targetNodeType>>
[[ReferenceResolveInfoAdded.originCommands]]originCommands:: <<commandSourceType>>[]
[[ReferenceResolveInfoAdded.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[ReferenceResolveInfoAdded.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`ReferenceResolveInfoAdded`

.Related command
<<cmd-AddReferenceResolveInfo>>

[[evnt-ReferenceResolveInfoDeleted]]
===== Reference ResolveInfo deleted
ResolveInfo <<ReferenceResolveInfoDeleted.deletedResolveInfo>> has been deleted from existing entry inside <<ReferenceResolveInfoDeleted.parent>>'s <<ReferenceResolveInfoDeleted.reference>> at <<ReferenceResolveInfoDeleted.index>> with <<ReferenceResolveInfoDeleted.target>>.

[horizontal]
.Parameters
[[ReferenceResolveInfoDeleted.parent, `parent`]]parent:: <<targetNodeType>>
[[ReferenceResolveInfoDeleted.reference, `reference`]]reference:: <<metaPointerType>>
[[ReferenceResolveInfoDeleted.index, `index`]]index:: <<indexType>>
[[ReferenceResolveInfoDeleted.target, `target`]]target:: <<targetNodeType>>
[[ReferenceResolveInfoDeleted.deletedResolveInfo, `deletedResolveInfo`]]deletedResolveInfo:: <<resolveInfoType>>
[[ReferenceResolveInfoDeleted.originCommands]]originCommands:: <<commandSourceType>>[]
[[ReferenceResolveInfoDeleted.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[ReferenceResolveInfoDeleted.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`ReferenceResolveInfoDeleted`

.Related command
<<cmd-DeleteReferenceResolveInfo>>

[[evnt-ReferenceResolveInfoChanged]]
===== Reference ResolveInfo changed
ResolveInfo of existing entry inside <<ReferenceResolveInfoChanged.parent>>'s <<ReferenceResolveInfoChanged.reference>> at <<ReferenceResolveInfoChanged.index>> with <<ReferenceResolveInfoChanged.target>> has been changed from <<ReferenceResolveInfoChanged.replacedResolveInfo>> to <<ReferenceResolveInfoChanged.newResolveInfo>>.

[horizontal]
.Parameters
[[ReferenceResolveInfoChanged.parent, `parent`]]parent:: <<targetNodeType>>
[[ReferenceResolveInfoChanged.reference, `reference`]]reference:: <<metaPointerType>>
[[ReferenceResolveInfoChanged.index, `index`]]index:: <<indexType>>
[[ReferenceResolveInfoChanged.newResolveInfo, `newResolveInfo`]]newResolveInfo:: <<resolveInfoType>>
[[ReferenceResolveInfoChanged.target, `target`]]target:: <<targetNodeType>>?
[[ReferenceResolveInfoChanged.replacedResolveInfo, `replacedResolveInfo`]]replacedResolveInfo:: <<resolveInfoType>>
[[ReferenceResolveInfoChanged.originCommands]]originCommands:: <<commandSourceType>>[]
[[ReferenceResolveInfoChanged.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[ReferenceResolveInfoChanged.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`ReferenceResolveInfoChanged`

.Related command
<<cmd-ChangeReferenceResolveInfo>>

[[evnt-ReferenceTargetAdded]]
===== Reference target added
<<ReferenceTargetAdded.newTarget>> has been added as target to existing entry inside <<ReferenceTargetAdded.parent>>'s <<ReferenceTargetAdded.reference>> at <<ReferenceTargetAdded.index>> with <<ReferenceTargetAdded.resolveInfo>>.

[horizontal]
.Parameters
[[ReferenceTargetAdded.parent, `parent`]]parent:: <<targetNodeType>>
[[ReferenceTargetAdded.reference, `reference`]]reference:: <<metaPointerType>>
[[ReferenceTargetAdded.index, `index`]]index:: <<indexType>>
[[ReferenceTargetAdded.newTarget, `newTarget`]]newTarget:: <<targetNodeType>>
[[ReferenceTargetAdded.resolveInfo, `resolveInfo`]]resolveInfo:: <<resolveInfoType>>
[[ReferenceTargetAdded.originCommands]]originCommands:: <<commandSourceType>>[]
[[ReferenceTargetAdded.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[ReferenceTargetAdded.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`ReferenceTargetAdded`

.Related command
<<cmd-AddReferenceTarget>>

[[evnt-ReferenceTargetDeleted]]
===== Reference target deleted
Target <<ReferenceTargetDeleted.deletedTarget>> has been deleted from existing entry inside <<ReferenceTargetDeleted.parent>>'s <<ReferenceTargetDeleted.reference>> at <<ReferenceTargetDeleted.index>> with <<ReferenceTargetDeleted.resolveInfo>>.

[horizontal]
.Parameters
[[ReferenceTargetDeleted.parent, `parent`]]parent:: <<targetNodeType>>
[[ReferenceTargetDeleted.reference, `reference`]]reference:: <<metaPointerType>>
[[ReferenceTargetDeleted.index, `index`]]index:: <<indexType>>
[[ReferenceTargetDeleted.resolveInfo, `resolveInfo`]]resolveInfo:: <<resolveInfoType>>
[[ReferenceTargetDeleted.deletedTarget, `deletedTarget`]]deletedTarget:: <<targetNodeType>>
[[ReferenceTargetDeleted.originCommands]]originCommands:: <<commandSourceType>>[]
[[ReferenceTargetDeleted.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[ReferenceTargetDeleted.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`ReferenceTargetDeleted`

.Related command
<<cmd-DeleteReferenceTarget>>

[[evnt-ReferenceTargetChanged]]
===== Reference target changed
Target of existing entry inside <<ReferenceTargetChanged.parent>>'s <<ReferenceTargetChanged.reference>> at <<ReferenceTargetChanged.index>> with <<ReferenceTargetChanged.resolveInfo>> has been changed from <<ReferenceTargetChanged.replacedTarget>> to <<ReferenceTargetChanged.newTarget>>.

[horizontal]
.Parameters
[[ReferenceTargetChanged.parent, `parent`]]parent:: <<targetNodeType>>
[[ReferenceTargetChanged.reference, `reference`]]reference:: <<metaPointerType>>
[[ReferenceTargetChanged.index, `index`]]index:: <<indexType>>
[[ReferenceTargetChanged.newTarget, `newTarget`]]newTarget:: <<targetNodeType>>
[[ReferenceTargetChanged.resolveInfo, `resolveInfo`]]resolveInfo:: <<resolveInfoType>>?
[[ReferenceTargetChanged.replacedTarget, `replacedTarget`]]replacedTarget:: <<targetNodeType>>
[[ReferenceTargetChanged.originCommands]]originCommands:: <<commandSourceType>>[]
[[ReferenceTargetChanged.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[ReferenceTargetChanged.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`ReferenceTargetChanged`

.Related command
<<cmd-ChangeReferenceTarget>>

[[evnt-miscellaneous]]
==== Miscellaneous

[[evnt-Composite]]
[[evnt-CompositeEvent]]
===== Composite
The events in <<CompositeEvent.parts>> have happened in the given order.{fn-org281}

Composite events don't mention origin commands on their own; they are only mentioned in each part.{fn-org306}
We can nest composite events arbitrarily.{fn-org360}

[horizontal]
.Parameters
[[CompositeEvent.parts, `parts`]]parts:: <<eventType>>[]
[[CompositeEvent.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`CompositeEvent`

.Related command
<<cmd-CompositeCommand>>

[[evnt-NoOp]]
[[evnt-NoOpEvent]]
===== No-op
Nothing happened as result of one or more command(s).{fn-org314}

[horizontal]
.Parameters
[[NoOpEvent.originCommands]]originCommands:: <<commandSourceType>>[]
[[NoOpEvent.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[NoOpEvent.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`NoOpEvent`

.Related command
_none_

[[evnt-Error]]
===== Error
Repository couldn't handle one or more command(s).{fn-org316}

[horizontal]
.Parameters
[[Error.errorCode, `errorCode`]]errorCode:: `String`
[[Error.message, `message`]]message:: `String`
[[Error.originCommands]]originCommands:: <<commandSourceType>>[]
[[Error.sequenceNumber]]sequenceNumber:: <<event-sequence-number>>
[[Error.protocolMessages]]protocolMessages:: <<protocolMessagesType>>

.Technical name
`Error`

.Related command
_none_