[[message-groups]]
=== Message groups

For ease of reference, we label different sets of messages.
The sets are non-exclusive, i.e. they overlap.

[[group-create-node]]
==== Create node messages
All messages that create new nodes.
They contain a <<deltaChunkType>>.

* <<cmd-AddPartition>> / <<evnt-PartitionAdded>>
* <<cmd-AddChild>> / <<evnt-ChildAdded>>
* <<cmd-ReplaceChild>> / <<evnt-ChildReplaced>>
* <<cmd-AddAnnotation>> / <<evnt-AnnotationAdded>>
* <<cmd-ReplaceAnnotation>> / <<evnt-AnnotationReplaced>>

[[group-remove-node]]
==== Remove node messages
All messages that remove a node from the repository.
They contain the id of the removed node, and ids of all removed descendants.

* <<cmd-DeletePartition>> / <<evnt-PartitionDeleted>>
* <<cmd-DeleteChild>> / <<evnt-ChildDeleted>>
* <<cmd-DeleteAnnotation>> / <<evnt-AnnotationDeleted>>
* <<cmd-MoveAndReplaceChildFromContainmentInOtherParent>> / <<evnt-ChildMovedAndReplacedFromContainmentInOtherParent>>
* <<cmd-MoveAndReplaceChildFromOtherContainmentInSameParent>> / <<evnt-ChildMovedAndReplacedFromOtherContainmentInSameParent>>
* <<cmd-MoveAndReplaceChildInSameContainment>> / <<evnt-ChildMovedAndReplacedInSameContainment>>
* <<cmd-MoveAndReplaceAnnotationFromOtherParent>> / <<evnt-AnnotationMovedAndReplacedFromOtherParent>>
* <<cmd-MoveAndReplaceAnnotationInSameParent>> / <<evnt-AnnotationMovedAndReplacedInSameParent>>


[[group-value-add]]
==== Add value messages
All messages that set a value for an unset property or reference.
They contain the parent, the feature, and the new value.

* <<cmd-AddProperty>> / <<evnt-PropertyAdded>>
* <<cmd-AddReference>> / <<evnt-ReferenceAdded>>

[[group-add-node]]
==== Add node messages
All messages that add a new child node.
They contain the parent and the new node.

* <<cmd-AddChild>> / <<evnt-ChildAdded>>
* <<cmd-AddAnnotation>> / <<evnt-AnnotationAdded>>


[[group-value-change]]
==== Change value messages
All messages that overwrite an existing property or reference with a new one.
They contain the parent, the feature, and the old and new value.

* <<cmd-ChangeProperty>> / <<evnt-PropertyChanged>>
* <<cmd-ChangeReference>> / <<evnt-ReferenceChanged>>


[[group-node-replace]]
==== Replace node messages
All messages that replace an existing node with a new one.
They contain the parent, the new node, and the id of the deleted node and ids of all deleted descendants.

* <<cmd-ReplaceChild>> / <<evnt-ChildReplaced>>
* <<cmd-ReplaceAnnotation>> / <<evnt-AnnotationReplaced>>


[[group-value-delete]]
==== Delete value messages
All messages that delete an existing property or reference.
They contain the parent, the feature, and the old value.

* <<cmd-DeleteProperty>> / <<evnt-PropertyDeleted>>
* <<cmd-DeleteReference>> / <<evnt-ReferenceDeleted>>


[[group-node-delete]]
==== Delete node messages
All messages that delete an existing child node.
They contain the parent, the id of the deleted node, and ids of all deleted descendants.

* <<cmd-DeleteChild>> / <<evnt-ChildDeleted>>
* <<cmd-DeleteAnnotation>> / <<evnt-AnnotationDeleted>>


[[group-move-or-replace]]
==== Move or replace messages
All messages that move and/or replace a node.
They contain the old and new parent, and the moved node.

* <<cmd-MoveChildFromContainmentInOtherParent>> / <<evnt-ChildMovedFromContainmentInOtherParent>>
* <<cmd-MoveChildFromOtherContainmentInSameParent>> / <<evnt-ChildMovedFromOtherContainmentInSameParent>>
* <<cmd-MoveChildInSameContainment>> / <<evnt-ChildMovedInSameContainment>>
* <<cmd-MoveAndReplaceChildFromContainmentInOtherParent>> / <<evnt-ChildMovedAndReplacedFromContainmentInOtherParent>>
* <<cmd-MoveAndReplaceChildFromOtherContainmentInSameParent>> / <<evnt-ChildMovedAndReplacedFromOtherContainmentInSameParent>>
* <<cmd-MoveAndReplaceChildInSameContainment>> / <<evnt-ChildMovedAndReplacedInSameContainment>>
* <<cmd-MoveAnnotationFromOtherParent>> / <<evnt-AnnotationMovedFromOtherParent>>
* <<cmd-MoveAnnotationInSameParent>> / <<evnt-AnnotationMovedInSameParent>>
* <<cmd-MoveAndReplaceAnnotationFromOtherParent>> / <<evnt-AnnotationMovedAndReplacedFromOtherParent>>
* <<cmd-MoveAndReplaceAnnotationInSameParent>> / <<evnt-AnnotationMovedAndReplacedInSameParent>>


[[group-move-only]]
==== Move-only messages
All messages that move a node.
They contain the old and new parent, and the moved node.

* <<cmd-MoveChildFromContainmentInOtherParent>> / <<evnt-ChildMovedFromContainmentInOtherParent>>
* <<cmd-MoveChildFromOtherContainmentInSameParent>> / <<evnt-ChildMovedFromOtherContainmentInSameParent>>
* <<cmd-MoveChildInSameContainment>> / <<evnt-ChildMovedInSameContainment>>
* <<cmd-MoveAnnotationFromOtherParent>> / <<evnt-AnnotationMovedFromOtherParent>>
* <<cmd-MoveAnnotationInSameParent>> / <<evnt-AnnotationMovedInSameParent>>


[[group-move-and-replace]]
==== Move and replace messages
All messages that move and replace a node.
They contain the old and new parent, the moved node, and the replaced node.

* <<cmd-MoveAndReplaceChildFromContainmentInOtherParent>> / <<evnt-ChildMovedAndReplacedFromContainmentInOtherParent>>
* <<cmd-MoveAndReplaceChildFromOtherContainmentInSameParent>> / <<evnt-ChildMovedAndReplacedFromOtherContainmentInSameParent>>
* <<cmd-MoveAndReplaceChildInSameContainment>> / <<evnt-ChildMovedAndReplacedInSameContainment>>
* <<cmd-MoveAndReplaceAnnotationFromOtherParent>> / <<evnt-AnnotationMovedAndReplacedFromOtherParent>>
* <<cmd-MoveAndReplaceAnnotationInSameParent>> / <<evnt-AnnotationMovedAndReplacedInSameParent>>


[[group-move-or-replace-child]]
==== Move or replace child messages
All messages that move and/or replace a child node in a containment (_not_ an annotation).
They contain the old and new parent, the moved node, and the old and new containment.

* <<cmd-MoveChildFromContainmentInOtherParent>> / <<evnt-ChildMovedFromContainmentInOtherParent>>
* <<cmd-MoveChildFromOtherContainmentInSameParent>> / <<evnt-ChildMovedFromOtherContainmentInSameParent>>
* <<cmd-MoveChildInSameContainment>> / <<evnt-ChildMovedInSameContainment>>
* <<cmd-MoveAndReplaceChildFromContainmentInOtherParent>> / <<evnt-ChildMovedAndReplacedFromContainmentInOtherParent>>
* <<cmd-MoveAndReplaceChildFromOtherContainmentInSameParent>> / <<evnt-ChildMovedAndReplacedFromOtherContainmentInSameParent>>
* <<cmd-MoveAndReplaceChildInSameContainment>> / <<evnt-ChildMovedAndReplacedInSameContainment>>


[[group-move-or-replace-annotation]]
==== Move or replace annotation messages
All messages that move and/or replace an annotation node (_not_ a child node in a containment).
They contain the old and new parent, and the moved node.

* <<cmd-MoveAnnotationFromOtherParent>> / <<evnt-AnnotationMovedFromOtherParent>>
* <<cmd-MoveAnnotationInSameParent>> / <<evnt-AnnotationMovedInSameParent>>
* <<cmd-MoveAndReplaceAnnotationFromOtherParent>> / <<evnt-AnnotationMovedAndReplacedFromOtherParent>>
* <<cmd-MoveAndReplaceAnnotationInSameParent>> / <<evnt-AnnotationMovedAndReplacedInSameParent>>


[[group-move-or-replace-from-other-parent]]
==== Move or replace from other parent
All messages that move and/or replace a node from another parent.
They contain the old parent, the new parent, and the moved node.

* <<cmd-MoveChildFromContainmentInOtherParent>> / <<evnt-ChildMovedFromContainmentInOtherParent>>
* <<cmd-MoveAndReplaceChildFromContainmentInOtherParent>> / <<evnt-ChildMovedAndReplacedFromContainmentInOtherParent>>
* <<cmd-MoveAnnotationFromOtherParent>> / <<evnt-AnnotationMovedFromOtherParent>>
* <<cmd-MoveAndReplaceAnnotationFromOtherParent>> / <<evnt-AnnotationMovedAndReplacedFromOtherParent>>


[[group-move-or-replace-in-same-parent]]
==== Move or replace in same parent
All messages that move and/or replace a node within the same parent.
They contain the parent, and the moved node.

* <<cmd-MoveChildFromOtherContainmentInSameParent>> / <<evnt-ChildMovedFromOtherContainmentInSameParent>>
* <<cmd-MoveChildInSameContainment>> / <<evnt-ChildMovedInSameContainment>>
* <<cmd-MoveAndReplaceChildFromOtherContainmentInSameParent>> / <<evnt-ChildMovedAndReplacedFromOtherContainmentInSameParent>>
* <<cmd-MoveAndReplaceChildInSameContainment>> / <<evnt-ChildMovedAndReplacedInSameContainment>>
* <<cmd-MoveAnnotationInSameParent>> / <<evnt-AnnotationMovedInSameParent>>
* <<cmd-MoveAndReplaceAnnotationInSameParent>> / <<evnt-AnnotationMovedAndReplacedInSameParent>>

[[group-move-or-replace-from-other-containment]]
==== Move or replace from other containment
All messages that move and/or replace a node from another containment within the same parent.
They contain the parent, the old containment, the new containment, and the moved node.

* <<cmd-MoveChildFromOtherContainmentInSameParent>> / <<evnt-ChildMovedFromOtherContainmentInSameParent>>
* <<cmd-MoveAndReplaceChildFromOtherContainmentInSameParent>> / <<evnt-ChildMovedAndReplacedFromOtherContainmentInSameParent>>


[[group-move-or-replace-in-same-containment]]
==== Move or replace in same containment
All messages that move and/or replace a node within the same containment.
They contain the parent, the containment, and the moved node.

* <<cmd-MoveChildInSameContainment>> / <<evnt-ChildMovedInSameContainment>>
* <<cmd-MoveAndReplaceChildInSameContainment>> / <<evnt-ChildMovedAndReplacedInSameContainment>>
