[[messages]]
== Messages
[[parameter-syntax]]
=== Parameter syntax
* Parameters suffixed with `?` CAN be omitted, or CAN have a value of `null`.
Both representations express the parameter to be unset.{fn-org427}

* Parameters suffixed with `[]` are ordered lists with zero or more elements.

=== Parameter types
[horizontal]
[[additionalInfosType]]additionalInfos:: Optionally empty{fn-org402} list of <<additionalInfo>>s.

[[targetNodeType]]TargetNode:: Target's node as <<{m3}.adoc#node-id, id>>.

[[metaPointerType]]MetaPointer:: MetaPointer-tuple to describe an M2 element (classifier, feature, etc.).
Encoded as <<{serialization}.adoc#meta-pointer, meta-pointer>>.

[[propertyValueType]]PropertyValue:: Property value encoded as <<{serialization}.adoc#property-values, property value>>.

[[resolveInfoType]]ResolveInfo:: ResolveInfo of a reference as string.
Can be `null`.

[[indexType]]Index:: Position inside a multiple link or annotations as integer >= 0.
Cannot be `null`.
Use value `0` for <<{m3}.adoc#multiplicity, single links>>.

[[commandType]]Command:: Any <<commands, command>>.

[[commandIdType]]CommandId:: Id of a command.{fn-org305}
Same format as <<{m3}.adoc#identifiers, identifiers>>; must be unique per <<participation>>.

[[queryIdType]]QueryId:: Id of a query.
Same format as <<{m3}.adoc#identifiers, identifiers>>; must be unique per <<participation>>.

[[chunkType]]SerializationChunk:: Chunk of nodes as described in <<{serialization}.adoc, serialization specification>>.

[[eventType]]Event:: Any <<events, event>>.

[[participationIdType]]ParticipationId:: Id of a <<participation>>.
Same format as <<{m3}.adoc#identifiers, identifiers>>; must be unique for all concurrent participations.

[[clientIdType]]clientId:: Id of a <<client>>.
Same format as <<{m3}.adoc#identifiers, identifiers>>; must be stable over time for the same client to use <<qry-GetAvailableIds, reserved free node ids>>.

[[repositoryIdType]]RepositoryId:: Id of a <<repository>>.
Same format as <<{m3}.adoc#identifiers, identifiers>>; must be unique for all repositories in the same context.
LionWeb doesn't specify the scope of the context.{fn-org401}

[[commandSourceType]]CommandSource:: _(<<participationIdType>>, <<commandIdType>>)_ tuple{fn-org306} this event is based on.
This allows a client to know when its command has been processed (either successful or not).

[[eventSequenceType]]EventSequenceNumber:: <<event-sequence-number>> of this event.

[[freeIdType]]FreeId:: Free <<{m3}.adoc#node-id, node id>>.

[[deltaProtocolVersionType]]DeltaProtocolVersion:: Version of the delta protocol, e.g. `2025.1`.

[[booleanType]]boolean:: A boolean value, i.e. either `true` or `false`.

[[integerType]]integer type:: An integer value.

[[new-nodes, new nodes]]
==== New nodes
The term "new node" refers to nodes that MUST NOT yet exist in the repository.{fn-org327}

[[existing-nodes, existing nodes]]
==== Existing nodes
The term "existing node" refers to nodes that MUST exist in the repository.

[[reused-nodes, reused nodes]]
==== Reused nodes
The term "reused node" refers to nodes that are removed and re-added in the same command/event.{fn-org422}
A client SHOULD keep the identity of the reused node in its internal representation.

These [[replace-with-new-content-commands]] _replace with new content commands_ / [[replace-with-new-content-events]] _replace with new content events_ are:

* <<cmd-ReplaceChild>> / <<evnt-ChildReplaced>>
* <<cmd-ReplaceAnnotation>> / <<evnt-AnnotationReplaced>>

==== How to address references
We refer to references by the tuple of _(parent, reference, index)_.
Rationale: Both reference `target` and `resolveInfo` can be `null`, so they aren't suitable for identifying the reference.
However, `target` and `resolveInfo` MUST NOT both be `null`.

include::errors.adoc[]

include::queries/queries.adoc[]

include::commandsEvents/command-event-overview.adoc[]

include::commandsEvents/commands.adoc[]

include::commandsEvents/events.adoc[]