[[messages]]
== Messages
=== Parameter types
[horizontal]
[[protocolMessagesType]]protocolMessages:: Optionally empty{fn-org402} list of <<protocolMessage>>s.

[[targetNodeType]]TargetNode:: Target's node as <<{m3}.adoc#node-id, id>>.

[[metaPointerType]]MetaPointer:: MetaPointer-tuple to describe an M2 element (classifier, feature, etc.).
Encoded as <<{serialization}.adoc#meta-pointer, meta-pointer>>.

[[propertyValueType]]PropertyValue:: Property value encoded as <<{serialization}.adoc#property-values, property value>>.

[[resolveInfoType]]ResolveInfo:: ResolveInfo of a reference as string.
Can be `null`.

[[indexType]]Index:: Position inside a multiple link or annotations as integer >= 0.
Cannot be `null`.
Use value `0` for <<{m3}.adoc#multiplicity, single links>>.

[[commandType]]Command:: Any <<commands, command>>.

[[commandIdType]]CommandId:: Id of a command.{fn-org305}
Same format as <<{m3}.adoc#identifiers, identifiers>>; must be unique per <<participation>>.

[[queryIdType]]QueryId:: Id of a query.
Same format as <<{m3}.adoc#identifiers, identifiers>>; must be unique per <<participation>>.

[[chunkType]]SerializationChunk:: Chunk of nodes as described in <<{serialization}.adoc, serialization specification>>.
Might be a single _anchor node_ or an arbitrary complex subtree with one _anchor node_.
All other nodes MUST be direct or indirect children or annotations of the _anchor node_.
Nodes in that subtree MAY have references to already existing nodes, and already existing nodes MAY have references to nodes in that subtree.{fn-org327}

[[shallowChunkType]]ShallowSerializationChunk:: Chunk of nodes as described in <<{serialization}.adoc, serialization specification>>.
MUST contain one single _shallow node_.
The _shallow node_ SHOULD contain all properties of that node, and CAN contain containments, references, and annotations.
However, the chunk MUST NOT contain the actual nodes referenced by containments, references, or annotations (except if the referenced node is the _shallow node_ itself).{fn-org425}

[[splitFlagType]]SplitFlag:: boolean flag whether the chunk is complete within this <<splittableMessage>>.{fn-org425}

[[continuedChunkCompletedFlagType]]ContinuedChunkCompletedFlag:: boolean flag whether this <<continuedChunk>> completes its <<splittableMessage>>.{fn-org425}

[[continuedChunkSequenceNumberType]]ContinuedChunkSequenceNumber:: orders connected <<continuedChunk, continued chunks>>.
Positive integer that starts at 0 and increments by one for each consecutive <<continuedChunk>>.{fn-org425}

[[eventType]]Event:: Any <<events, event>>.

[[participationIdType]]ParticipationId:: Id of a <<participation>>.
Same format as <<{m3}.adoc#identifiers, identifiers>>; must be unique for all concurrent participations.

[[clientIdType]]clientId:: Id of a <<client>>.
Same format as <<{m3}.adoc#identifiers, identifiers>>; must be stable over time for the same client to use <<qry-GetAvailableIds, reserved free node ids>>.

[[repositoryIdType]]RepositoryId:: Id of a <<repository>>.
Same format as <<{m3}.adoc#identifiers, identifiers>>; must be unique for all repositories in the same context.
LionWeb doesn't specify the scope of the context.{fn-org401}

[[commandSourceType]]CommandSource:: _(<<participationIdType>>, <<commandIdType>>)_ tuple{fn-org306} this event is based on.
This allows a client to know when its command has been processed (either successful or not).

[[eventSequenceType]]EventSequenceNumber:: <<event-sequence-number>> of this event.

[[freeIdType]]FreeId:: Free <<{m3}.adoc#node-id, node id>>.

[[deltaProtocolVersionType]]DeltaProtocolVersion:: Version of the delta protocol, e.g. `2025.1`.

[[booleanType]]boolean:: A boolean value, i.e. either `true` or `false`.

[[integerType]]integer type:: An integer value.

[[new-nodes, new nodes]]
==== New nodes
The term "new node" refers to nodes that MUST NOT yet exist in the repository.{fn-org327}

[[reused-nodes, reused nodes]]
==== Replaced nodes
The term "reused node" refers to nodes that are removed and re-added in the same command/event.{fn-org422}

These [[replace-with-new-content-commands]] _replace with new content commands_ / [[replace-with-new-content-events]] _replace with new content events_ are:

* <<cmd-ReplaceChild>> / <<evnt-ChildReplaced>>
* <<cmd-ReplaceAnnotation>> / <<evnt-AnnotationReplaced>>

==== How to address references
We refer to references by the tuple of _(parent, reference, index)_.
Rationale: Both reference `target` and `resolveInfo` can be `null`, so they aren't suitable for identifying the reference.
However, `target` and `resolveInfo` MUST NOT both be `null`.

include::errors.adoc[]

include::queries/queries.adoc[]

include::commandsEvents/command-event-overview.adoc[]

include::commandsEvents/commands.adoc[]

include::commandsEvents/events.adoc[]