[[open-questions]]
== Open questions
#TODO#

* Which of the commands can potentially create invalid (recursively contained) trees?

  * Hypothesis: Only moveChild / moveAnnotation commands

    A
        contains A


    A
        contains B
            contains A

    A
        contains B
            contains C
                contains A


* Which kind of errors do we accept?
How does this interact with concurrent edits?
Example: Does <<cmd-DeleteChild>> fail if the `removedChild` does not exist? --> Postpone

* Do we need "swapNodes" event?
  --> definitely not for now
  How different from two composed moved commands?

* Wording for commands/events: Shall we use "deleteXxx" everywhere? Or "removeXxx"? Or "deleteXxx" for deleting nodes, and "removeXxx" for removing properties / references? --> "delete"

* Decide on errors marked with #?# (invalid optional parameter values){fn-org312} --> postponed

* How to report a command has completely been discarded, without any resulting event?{fn-org314} --> NoOpEvent