@startuml
title Typed M2 Library Example

hide empty members
hide stereotypes

!include ../shared/typed-skinparam.puml
!include ../shared/typed-map-legend.puml

package "M3 runtime" {
    object "Metamodel" as metamodel

    object "qualifiedName" as qualifiedName
    metamodel *-- qualifiedName

    object "elements" as elements
    metamodel *-- elements

    object "Concept" as concept

    object "simpleName" as simpleName
    concept *-- simpleName

    object "abstract" as abstract
    concept *-- abstract

    object "features" as features
    concept *-- features

    object "extends" as extends
    concept *-- extends

    object "PrimitiveType" as primitiveType
    primitiveType *-- simpleName

    object "Property" as property
    property *-- simpleName

    object "optional" as optional
    property *-- optional

    object "propertyType" as propertyType
    property *-- propertyType

    object "Reference" as reference
    reference *-- simpleName
    reference *-- optional

    object "multiple" as multiple
    reference *-- multiple

    object "linkType" as linkType
    reference *-- linkType

    object "Containment" as containment
    containment *-- simpleName
    containment *-- optional
    containment *-- multiple
    containment *-- linkType
}

package "M3 generated" {
    interface "Metamodel" as genMetamodel

    interface "MetamodelElement" as genMetamodelElement

    interface "Concept" as genConcept extends genMetamodelElement

    interface "DataType" as genDataType extends genMetamodelElement

    interface "PrimitiveType" as genPrimitiveType extends genDataType

    interface "Feature" as genFeature

    interface "Property" as genProperty extends genFeature

    interface "Reference" as genReference extends genFeature

    interface "Containment" as genContainment extends genFeature
}

' library (metamodel)

object "library : <u>TypedNode<T = generated::Metamodel></u>" as library<<TypedNode>> {
    concept = → m3runtime::Metamodel
}
'metamodel <- library #lightgray: concept


map " " as libraryQualifiedName<<TypedProperty>> {
    → m3runtime::qualifiedName => "library" : <u>TypedProperty<T = String></u>
}
library *-- libraryQualifiedName: properties
'qualifiedName <- libraryQualifiedName #lightgray: property

map " " as libraryChildren<<TypedChild>> {
    elements => → m3runtime::elements : <u>TypedChild<T = generated::MetamodelElement*></u>
}
library *-- libraryChildren: children
'elements <- libraryLibString #lightgray: containment

' LibString

object "LibString : <u>TypedNode<T = PrimitiveType></u>" as LibString<<TypedNode>> {
    concept = → m3runtime::PrimitiveType
}
'primitiveType <- LibString #lightgray: concept

libraryChildren::elements --> LibString: target

map " " as LibStringName<<TypedProperty>> {
    → m3runtime::simpleName => "LibString" : <u>TypedProperty<T = String></u>
}
LibString *-- LibStringName: properties
'simpleName <- LibStringName #lightgray: property

' LibBoolean

object "LibBoolean : <u>TypedNode<T = generated::PrimitiveType></u>" as LibBoolean<<TypedNode>> {
    concept = → m3runtime::PrimitiveType
}
'primitiveType <- LibBoolean #lightgray: concept

libraryChildren::elements --> LibBoolean: target

map " " as LibBooleanName<<TypedProperty>> {
    → m3runtime::simpleName => "LibBoolean" : <u>TypedProperty<T = String></u>
}
LibBoolean *-- LibBooleanName: properties
'simpleName <- LibBooleanName #lightgray: property

' LibInteger

object "LibInteger : <u>TypedNode<T = generated::PrimitiveType></u>" as LibInteger<<TypedNode>> {
    concept = → m3runtime::PrimitiveType
}
'primitiveType <- LibInteger #lightgray: concept

libraryChildren::elements --> LibInteger: target

map " " as LibIntegerName<<TypedProperty>> {
    → m3runtime::simpleName => "LibInteger" : <u>TypedProperty<T = String></u>
}
LibInteger *-- LibIntegerName: properties
'simpleName <- LibIntegerName #lightgray: property

' Book

object "Book : <u>TypedNode<T = generated::Concept></u>" as Book<<TypedNode>> {
    concept = → m3runtime::Concept
}
'concept <- Book #lightgray: concept

libraryChildren::elements --> Book: target

map " " as bookName<<TypedProperty>> {
    → m3runtime::simpleName => "Book" : <u>TypedProperty<T = String></u>
    → m3runtime::abstract => false : <u>TypedProperty<T = Boolean></u>
}
Book *-- bookName: properties

' Book.title

object "title : <u>TypedNode<T = Property></u>" as title<<TypedNode>> {
    concept = → m3runtime::Property
}
'property <- title #lightgray: concept

map " " as bookChildren<<TypedChild>> {
     features => → m3runtime::features : <u>TypedChild<T = generated::Feature*></u>
}
Book *-- bookChildren: children
bookChildren::features -> title: target

map " " as titleName<<TypedProperty>> {
    → m3runtime::simpleName => "title" : <u>TypedProperty<T = String></u>
    → m3runtime::optional => false : <u>TypedProperty<T = Boolean></u>
}
title *-- titleName: properties
'simpleName <- titleName #lightgray: property

object ": <u>TypedReference<T = generated::DataType></u>" as titleType<<TypedReference>> {
    reference = → m3runtime::propertyType
}
title *-- titleType: references
'propertyType <- titleType #lightgray: reference
titleType -> LibString: target

' Book.pages

object "pages : <u>TypedNode<T = generated::Property></u>" as pages<<TypedNode>> {
    concept = → m3runtime::Property
}
'property <- pages #lightgray: concept

bookChildren::features --> pages: target

map " " as pagesName<<TypedProperty>> {
    → m3runtime::SimpleName => "pages" : <u>TypedProperty<T = String></u>
    → m3runtime::optional => false : <u>TypedProperty<T = Boolean></u>
}
pages *-- pagesName: properties
'simpleName <- pagesName #lightgray: property

object ": <u>TypedReference<T = generated::DataType></u>" as pagesType<<TypedReference>> {
    reference = → m3runtime::propertyType
}
pages *-- pagesType: references
'propertyType <- pagesType #lightgray: reference
pagesType -> LibInteger: target

' Book.author

object "author : <u>TypedNode<T = generated::Reference></u>" as author<<TypedNode>> {
    concept = → m3runtime::Reference
}
'reference <- author #lightgray: concept

bookChildren::features --> author: target

map " " as authorName<<TypedProperty>> {
    → m3runtime::simpleName => "author" : <u>TypedProperty<T = String></u>
    → m3runtime::optional => false : <u>TypedProperty<T = Boolean></u>
    → m3runtime::multiple => false : <u>TypedProperty<T = Boolean></u>
}
author *-- authorName: properties
'simpleName <- authorName #lightgray: property


object ": <u>TypedReference<T = generated::Concept></u>" as authorType<<TypedReference>> {
    reference = → m3runtime::linkType
}
author *-- authorType: references
'linkType <- authorType #lightgray: reference


' Library (node)

object "Library : <u>TypedNode<T = generated::Concept></u>" as Library<<TypedNode>> {
    concept = → m3runtime::Concept
}
'concept <- Library #lightgray: concept

libraryChildren::elements --> Library: target

map " " as libraryName<<TypedProperty>> {
    → m3runtime::simpleName => "Library" : <u>TypedProperty<T = String></u>
    → m3runtime::abstract => false : <u>TypedProperty<T = Boolean></u>

}
Library *-- libraryName: properties
'simpleName <- libraryName #lightgray: property

' Library.name

object "name : <u>TypedNode<T = generated::Property></u>" as libraryNameNode<<TypedNode>> {
    concept = → m3runtime::Property
}
'property <- libraryNameNode #lightgray: concept

map " " as LibraryNodeChildren<<TypedChild>> {
     features => → m3runtime::features : <u>TypedChild<T = generated::Feature*></u>
}
Library *-- LibraryNodeChildren: children
LibraryNodeChildren::features --> libraryNameNode: target

map " " as libraryNameName<<TypedProperty>> {
    → m3runtime::simpleName => "name" : <u>TypedProperty<T = String></u>
    → m3runtime::optional => false : <u>TypedProperty<T = Boolean></u>
}
libraryNameNode *-- libraryNameName: properties
'simpleName <- libraryNameName #lightgray: property

object ": <u>TypedReference<T = generated::DataType></u>" as libraryNameNodeType<<TypedReference>> {
    reference = → m3runtime::propertyType
}
libraryNameNode *-- libraryNameNodeType: references
'propertyType <- libraryNameNodeType #lightgray: reference
libraryNameNodeType -> LibString: target

' Library.books

object "books : <u>TypedNode<T = generated::Containment></u>" as books<<TypedNode>> {
    concept = → m3runtime::Containment
}
'containment <- books #lightgray: concept

LibraryNodeChildren::features --> books: target


map " " as booksName<<TypedProperty>> {
    → m3runtime::simpleName => "books" : <u>TypedProperty<T = String></u>
    → m3runtime::optional => false : <u>TypedProperty<T = Boolean></u>
    → m3runtime::multiple => true : <u>TypedProperty<T = Boolean></u>
}
books *-- booksName: properties
'simpleName <- booksName #lightgray: property

object ": <u>TypedReference<T = generated::Concept></u>" as booksType<<TypedReference>> {
    reference = → m3runtime::linkType
}
books *-- booksType: references
'linkType <- booksType #lightgray: reference
booksType -> Book: target

' Writer

object "Writer : <u>TypedNode<T = generated::Concept></u>" as Writer<<TypedNode>> {
    concept = → m3runtime::Concept
}
'concept <- Writer #lightgray: concept


libraryChildren::elements --> Writer: target
authorType -> Writer: target

map " " as Writer_Name<<TypedProperty>> {
    → m3runtime::simpleName => "Writer" : <u>TypedProperty<T = String></u>
    → m3runtime::abstract => false : <u>TypedProperty<T = Boolean></u>
}
Writer *-- Writer_Name: properties
'simpleName <- Writer_Name #lightgray: property

' Writer.name

object "name : <u>TypedNode<T = generated::Property></u>" as writerName<<TypedNode>> {
    concept = → m3runtime::Property
}
'property <- writerName #lightgray: concept

map " " as WriterChildren<<TypedChild>> {
     features => → m3runtime::features : <u>TypedChild<T = generated::Feature*></u>
}
Writer *-- WriterChildren: children
WriterChildren::features --> writerName: target

map " " as writerNameName<<TypedProperty>> {
    → m3runtime::simpleName => "name" : <u>TypedProperty<T = String></u>
    → m3runtime::optional => false : <u>TypedProperty<T = Boolean></u>
}
writerName *-- writerNameName: properties
'simpleName <- writerNameName #lightgray: property

object ": <u>TypedReference<T = generated::DataType></u>" as writerNameType<<TypedReference>> {
    reference = → m3runtime::propertyType
}
writerName *-- writerNameType: references
'propertyType <- writerNameType #lightgray: reference
writerNameType -> LibString: target

' GuideBookWriter

object "GuideBookWriter : <u>TypedNode<T = generated::Concept></u>" as GuideBookWriter<<TypedNode>> {
    concept = → m3runtime::Concept
}
'concept <- GuideBookWriter #lightgray: concept

libraryChildren::elements --> GuideBookWriter: target

map " " as GuideBookWriterName<<TypedProperty>> {
    → m3runtime::simpleName => "GuideBookWriter" : <u>TypedProperty<T = String></u>
    → m3runtime::abstract => false : <u>TypedProperty<T = Boolean></u>
}
GuideBookWriter *-- GuideBookWriterName: properties
'simpleName <- GuideBookWriterName #lightgray: property

object ": <u>TypedReference<T = generated::Concept></u>" as GuideBookWriterExtends<<TypedReference>> {
    reference = → m3runtime::extends
}
GuideBookWriter *-- GuideBookWriterExtends: references
'extends <- GuideBookWriterExtends #lightgray: reference
GuideBookWriterExtends -> Writer: target

' GuideBookWriter.countries

object "countries : <u>TypedNode<T = generated::Property></u>" as countries<<TypedNode>> {
    concept = → m3runtime::Property
}
'simpleName <- countries #lightgray: property

map " " as GuideBookWriterChildren<<TypedChild>> {
     features => → m3runtime::features : <u>TypedChild<T = generated::Feature*></u>
}
GuideBookWriter *-- GuideBookWriterChildren: children
GuideBookWriterChildren::features -> countries: target

map " " as countriesName<<TypedProperty>> {
    → m3runtime::simpleName => "countries" : <u>TypedProperty<T = String></u>
    → m3runtime::optional => false : <u>TypedProperty<T = Boolean></u>
}
countries *-- countriesName: properties
'simpleName <- countriesName #lightgray: property

object ": <u>TypedReference<T = generated::PrimitiveType></u>" as countriesType<<TypedReference>> {
    reference = → m3runtime::propertyType
}
countries *-- countriesType: references
'propertyType <- countriesType #lightgray: reference
countriesType -> LibString: target

' SpecialistBookWriter

object "SpecialistBookWriter : <u>TypedNode<T = generated::Concept></u>" as SpecialistBookWriter<<TypedNode>> {
    concept = → m3runtime::Concept
}
'concept <- SpecialistBookWriter #lightgray: concept

libraryChildren::elements --> SpecialistBookWriter: target

map " " as SpecialistBookWriterName<<TypedProperty>> {
    → m3runtime::simpleName => "SpecialistBookWriter" : <u>TypedProperty<T = String></u>
    → m3runtime::abstract => false : <u>TypedProperty<T = Boolean></u>
}
SpecialistBookWriter *-- SpecialistBookWriterName: properties
'simpleName <- SpecialistBookWriterName #lightgray: property

object ": <u>TypedReference<T = generated::Concept></u>" as SpecialistBookWriterExtends<<TypedReference>> {
    reference = → m3runtime::extends
}
SpecialistBookWriter *-- SpecialistBookWriterExtends: references
'extends <- SpecialistBookWriterExtends #lightgray: reference
SpecialistBookWriterExtends -> Writer: target

' SpecialistBookWriter.subject

object "subject : <u>TypedNode<T = generated::Property></u>" as subject<<TypedNode>> {
    concept = → m3runtime::Property
}
'simpleName <- subject #lightgray: property

map " " as SpecialistBookWriterChildren<<TypedChild>> {
     features => → m3runtime::features : <u>TypedChild<T = generated::Feature*></u>
}
SpecialistBookWriter *-- SpecialistBookWriterChildren: children
SpecialistBookWriterChildren::features --> subject: target

map " " as subjectName<<TypedProperty>> {
    → m3runtime::simpleName => "subject" : <u>TypedProperty<T = String></u>
    → m3runtime::optional => false : <u>TypedProperty<T = Boolean></u>
}
subject *-- subjectName: properties
'simpleName <- subjectName #lightgray: property

object ": <u>TypedReference<T = String></u>" as subjectType<<TypedReference>> {
    reference = → m3runtime::propertyType
}
subject *-- subjectType: references
'propertyType <- subjectType #lightgray: reference
subjectType -> LibString: target

@enduml
