@startuml
' Library

object "<<Node>> Bob's Library" as library {
    id = "idBobLib"
    concept = → idLibrary
}

map "<<PropertyValue>>" as libraryProperties {
    → idLibraryName => "Bob's library"
}
library *-- libraryProperties: properties

' Explorer book

object "<<Node>> Explorer Book" as explorerBook {
    id = "idExplorer"
    concept = → idBook
}

map "<<PropertyValue>>" as explorerBookProperties {
    → idPages => "123"
    → idTitle => "Explorer Book"
}
explorerBook *-- explorerBookProperties: properties

map "<<ChildTarget>>" as libraryChildren {
    libraryExplorerBook => → idLibraryBooks
}
library *-- libraryChildren: children
libraryChildren::libraryExplorerBook -> explorerBook


object "<<ReferenceTarget>>" as explorerBookAuthor {
    resolveInfo = "Jack London"
    reference = → idAuthor
}
explorerBook *-- explorerBookAuthor: references

' Jack London
object "<<Node>> Jack London" as jackLondon {
    id = "idJack"
    concept = → idGuideBookWriter
}

map "<<PropertyValue>>" as jackLondonProperties {
    → idWriterName => "Jack London"
    → idGuideBookWriterCountries => "Alaska"
}
jackLondon *-- jackLondonProperties: properties

explorerBookAuthor --> jackLondon: target
@enduml
