@startuml
title Low-level M2 Library Example

!include ../plantuml-shared/lowlevel-skinparam.puml
!include ../plantuml-shared/map-legend.puml


package "M3 runtime" as meta {
    object "Metamodel" as metamodel

    object "qualifiedName" as qualifiedName
    metamodel *-- qualifiedName

    object "elements" as elements
    metamodel *-- elements

    object "Concept" as concept

    object "simpleName" as simpleName
    concept *-- simpleName

    object "abstract" as abstract
    concept *-- abstract

    object "features" as features
    concept *-- features

    object "extends" as extends
    concept *-- extends

    object "PrimitiveType" as primitiveType
    primitiveType *-- simpleName

    object "Property" as property
    property *-- simpleName

    object "optional" as optional
    property *-- optional

    object "propertyType" as propertyType
    property *-- propertyType

    object "Reference" as reference
    reference *-- simpleName
    reference *-- optional

    object "multiple" as multiple
    reference *-- multiple

    object "linkType" as linkType
    reference *-- linkType

    object "Containment" as containment
    containment *-- simpleName
    containment *-- optional
    containment *-- multiple
    containment *-- linkType
}

' library (metamodel)

object "library" as library<<Node>> {
    id = "idLibMm"
    concept = → m3runtime::Metamodel
}
'metamodel <- library #lightgray: concept


map " " as libraryQualifiedName<<PropertyValue>> {
    → m3runtime::qualifiedName => "library"
}
library *-- libraryQualifiedName: properties
'qualifiedName <- libraryQualifiedName #lightgray: property

map " " as libraryChildren<<ChildTarget>> {
    elements => → m3runtime::elements
}
library *-- libraryChildren: children
'elements <- libraryLibString #lightgray: containment

' LibString

object "LibString" as LibString<<Node>> {
    id = "idLibString"
    concept = → m3runtime::PrimitiveType
}
'primitiveType <- LibString #lightgray: concept

libraryChildren::elements --> LibString: target

map " " as LibStringName<<PropertyValue>> {
    → m3runtime::simpleName => "LibString"
}
LibString *-- LibStringName: properties
'simpleName <- LibStringName #lightgray: property

' LibBoolean

object "LibBoolean" as LibBoolean<<Node>> {
    id = "idLibBoolean"
    concept = → m3runtime::PrimitiveType
}
'primitiveType <- LibBoolean #lightgray: concept

libraryChildren::elements --> LibBoolean: target

map " " as LibBooleanName<<PropertyValue>> {
    → m3runtime::simpleName => "LibBoolean"
}
LibBoolean *-- LibBooleanName: properties
'simpleName <- LibBooleanName #lightgray: property

' LibInteger

object "LibInteger" as LibInteger<<Node>> {
    id = "idLibInteger"
    concept = → m3runtime::PrimitiveType
}
'primitiveType <- LibInteger #lightgray: concept

libraryChildren::elements --> LibInteger: target

map " " as LibIntegerName<<PropertyValue>> {
    → m3runtime::simpleName => "LibInteger"
}
LibInteger *-- LibIntegerName: properties
'simpleName <- LibIntegerName #lightgray: property

' Book

object "Book" as Book<<Node>> {
    id = "idBook"
    concept = → m3runtime::Concept
}
'concept <- Book #lightgray: concept

libraryChildren::elements --> Book: target

map " " as bookName<<PropertyValue>> {
    → m3runtime::simpleName => "Book"
    → m3runtime::abstract => "false"
}
Book *-- bookName: properties

' Book.title

object "title" as title<<Node>> {
    id = "idTitle"
    concept = → m3runtime::Property
}
'property <- title #lightgray: concept

map " " as bookChildren<<ChildTarget>> {
     features => → m3runtime::features
}
Book *-- bookChildren: children
bookChildren::features -> title: target

map " " as titleName<<PropertyValue>> {
    → m3runtime::simpleName => "title"
    → m3runtime::optional => "false"
}
title *-- titleName: properties
'simpleName <- titleName #lightgray: property

object " " as titleType<<ReferenceTarget>> {
    resolveInfo = "LibString"
    reference = → m3runtime::propertyType
}
title *-- titleType: references
'propertyType <- titleType #lightgray: reference
titleType -> LibString: target

' Book.pages

object "pages" as pages<<Node>> {
    id = "idPages"
    concept = → m3runtime::Property
}
'property <- pages #lightgray: concept

bookChildren::features --> pages: target

map " " as pagesName<<PropertyValue>> {
    → m3runtime::SimpleName => "pages"
    → m3runtime::optional => "false"
}
pages *-- pagesName: properties
'simpleName <- pagesName #lightgray: property

object " " as pagesType<<ReferenceTarget>> {
    resolveInfo = "LibInteger"
    reference = → m3runtime::propertyType
}
pages *-- pagesType: references
'propertyType <- pagesType #lightgray: reference
pagesType -> LibInteger: target

' Book.author

object "author" as author<<Node>> {
    id = "idAuthor"
    concept = → m3runtime::Reference
}
'reference <- author #lightgray: concept

bookChildren::features --> author: target

map " " as authorName<<PropertyValue>> {
    → m3runtime::simpleName => "author"
    → m3runtime::optional => "false"
    → m3runtime::multiple => "false"
}
author *-- authorName: properties
'simpleName <- authorName #lightgray: property


object " " as authorType<<ReferenceTarget>> {
    resolveInfo = "Writer"
    reference = → m3runtime::linkType
}
author *-- authorType: references
'linkType <- authorType #lightgray: reference


' Library (node)

object "Library" as Library<<Node>> {
    id = "idLibrary"
    concept = → m3runtime::Concept
}
'concept <- Library #lightgray: concept

libraryChildren::elements --> Library: target

map " " as libraryName<<PropertyValue>> {
    → m3runtime::simpleName => "Library"
    → m3runtime::abstract => "false"

}
Library *-- libraryName: properties
'simpleName <- libraryName #lightgray: property

' Library.name

object "name" as libraryNameNode<<Node>> {
    id = "idLibraryName"
    concept = → m3runtime::Property
}
'property <- libraryNameNode #lightgray: concept

map " " as LibraryNodeChildren<<ChildTarget>> {
     features => → m3runtime::features
}
Library *-- LibraryNodeChildren: children
LibraryNodeChildren::features -> libraryNameNode: target

map " " as libraryNameName<<PropertyValue>> {
    → m3runtime::simpleName =>  "name"
    → m3runtime::optional => "false"
}
libraryNameNode *-- libraryNameName: properties
'simpleName <- libraryNameName #lightgray: property

object " " as libraryNameNodeType<<ReferenceTarget>> {
    resolveInfo = "LibString"
    reference = → m3runtime::propertyType
}
libraryNameNode *-- libraryNameNodeType: references
'propertyType <- libraryNameNodeType #lightgray: reference
libraryNameNodeType -> LibString: target

' Library.books

object "books" as books<<Node>> {
    id = "idLibraryBooks"
    concept = → m3runtime::Containment
}
'containment <- books #lightgray: concept

LibraryNodeChildren::features --> books: target


map " " as booksName<<PropertyValue>> {
    → m3runtime::simpleName => "books"
    → m3runtime::optional => "false"
    → m3runtime::multiple => "true"
}
books *-- booksName: properties
'simpleName <- booksName #lightgray: property

object " " as booksType<<ReferenceTarget>> {
    resolveInfo = "Book"
    reference = → m3runtime::linkType
}
books *-- booksType: references
'linkType <- booksType #lightgray: reference
booksType -> Book: target

' Writer

object "Writer" as Writer<<Node>> {
    id = "idWriter"
    concept = → m3runtime::Concept
}
'concept <- Writer #lightgray: concept


libraryChildren::elements --> Writer: target
authorType -> Writer: target

map " " as Writer_Name<<PropertyValue>> {
    → m3runtime::simpleName => "Writer"
    → m3runtime::abstract => "false"
}
Writer *-- Writer_Name: properties
'simpleName <- Writer_Name #lightgray: property

' Writer.name

object "name" as writerName<<Node>> {
    id = "idWriterName"
    concept = → m3runtime::Property
}
'property <- writerName #lightgray: concept

map " " as WriterChildren<<ChildTarget>> {
     features => → m3runtime::features
}
Writer *-- WriterChildren: children
WriterChildren::features -> writerName: target

map " " as writerNameName<<PropertyValue>> {
    → m3runtime::simpleName => "name"
    → m3runtime::optional => "false"
}
writerName *-- writerNameName: properties
'simpleName <- writerNameName #lightgray: property

object " " as writerNameType<<ReferenceTarget>> {
    resolveInfo = "LibString"
    reference = → m3runtime::propertyType
}
writerName *-- writerNameType: references
'propertyType <- writerNameType #lightgray: reference
writerNameType -> LibString: target

' GuideBookWriter

object "GuideBookWriter" as GuideBookWriter<<Node>> {
    id = "idGuideBookWriter"
    concept = → m3runtime::Concept
}
'concept <- GuideBookWriter #lightgray: concept

libraryChildren::elements --> GuideBookWriter: target

map " " as GuideBookWriterName<<PropertyValue>> {
    → m3runtime::simpleName => "GuideBookWriter"
    → m3runtime::abstract => "false"
}
GuideBookWriter *-- GuideBookWriterName: properties
'simpleName <- GuideBookWriterName #lightgray: property

object " " as GuideBookWriterExtends<<ReferenceTarget>> {
    resolveInfo = "Writer"
    reference = → m3runtime::extends
}
GuideBookWriter *-- GuideBookWriterExtends: references
'extends <- GuideBookWriterExtends #lightgray: reference
GuideBookWriterExtends -> Writer: target

' GuideBookWriter.countries

object "countries" as countries<<Node>> {
    id = "idGuideBookWriterCountries"
    concept = → m3runtime::Property
}
'simpleName <- countries #lightgray: property

map " " as GuideBookWriterChildren<<ChildTarget>> {
     features => → m3runtime::features
}
GuideBookWriter *-- GuideBookWriterChildren: children
GuideBookWriterChildren::features -> countries: target

map " " as countriesName<<PropertyValue>> {
    → m3runtime::simpleName => "countries"
    → m3runtime::optional => "false"
}
countries *-- countriesName: properties
'simpleName <- countriesName #lightgray: property

object " " as countriesType<<ReferenceTarget>> {
    resolveInfo = "LibString"
    reference = → m3runtime::propertyType
}
countries *-- countriesType: references
'propertyType <- countriesType #lightgray: reference
countriesType -> LibString: target

' SpecialistBookWriter

object "SpecialistBookWriter" as SpecialistBookWriter<<Node>> {
    id = "idSpecialistBookWriter"
    concept = → m3runtime::Concept
}
'concept <- SpecialistBookWriter #lightgray: concept

libraryChildren::elements --> SpecialistBookWriter: target

map " " as SpecialistBookWriterName<<PropertyValue>> {
    → m3runtime::simpleName => "SpecialistBookWriter"
    → m3runtime::abstract => "false"
}
SpecialistBookWriter *-- SpecialistBookWriterName: properties
'simpleName <- SpecialistBookWriterName #lightgray: property

object " " as SpecialistBookWriterExtends<<ReferenceTarget>> {
    resolveInfo = "Writer"
    reference = → m3runtime::extends
}
SpecialistBookWriter *-- SpecialistBookWriterExtends: references
'extends <- SpecialistBookWriterExtends #lightgray: reference
SpecialistBookWriterExtends -> Writer: target

' SpecialistBookWriter.subject

object "subject" as subject<<Node>> {
    id = "idSpecialistBookWriterSubject"
    concept = → m3runtime::Property
}
'simpleName <- subject #lightgray: property

map " " as SpecialistBookWriterChildren<<ChildTarget>> {
     features => → m3runtime::features
}
SpecialistBookWriter *-- SpecialistBookWriterChildren: children
SpecialistBookWriterChildren::features -> subject: target

map " " as subjectName<<PropertyValue>> {
    → m3runtime::simpleName => "subject"
    → m3runtime::optional => "false"
}
subject *-- subjectName: properties
'simpleName <- subjectName #lightgray: property

object " " as subjectType<<ReferenceTarget>> {
    resolveInfo = "LibString"
    reference = → propertyType
}
subject *-- subjectType: references
'propertyType <- subjectType #lightgray: reference
subjectType -> LibString: target

@enduml
