@startuml
' Library
title Typed M1 Library Example

skinparam object {
    BackgroundColor<<TypedNode>> LightGreen
    BackgroundColor<<TypedReference>> LightSkyBlue
}
skinparam map {
    BackgroundColor<<TypedProperty>> LightPink
    BackgroundColor<<TypedChild>> LightBlue
}

object "<T = Library> Bob's Library" as library<<TypedNode>> {
    concept = → idLibrary
}

map " " as libraryProperties<<TypedProperty>> {
    → idLibraryName => <T = String> "Bob's Library"
}
library *-- libraryProperties: properties

' Explorer book

object "<T = Book> Explorer Book" as explorerBook<<TypedNode>> {
    concept = → idBook
}

map " " as explorerBookProperties<<TypedProperty>> {
    → idTitle => <T = String> "Explorer Book"
    → idPages => <T = Integer> 123
}
explorerBook *-- explorerBookProperties: properties

map " " as libraryChildren<<TypedChild>> {
    idLibraryBooks => <T = Book*> → idLibraryBooks
}
library *-- libraryChildren: children
libraryChildren::idLibraryBooks -> explorerBook


object "<T = Writer>" as explorerBookAuthor<<TypedReference>> {
    reference = → idAuthor
}
explorerBook *-- explorerBookAuthor: references

' Jack London
object "<T = GuideBookWriter> Jack London" as jackLondon<<TypedNode>> {
    concept = → idGuideBookWriter
}

map " " as jackLondonProperties<<TypedProperty>> {
    → idWriterName => <T = String> "Jack London"
    → idGuideBookWriterCountries => <T = String> "Alaska"
}
jackLondon *-- jackLondonProperties: properties

explorerBookAuthor --> jackLondon: target
@enduml
