@startuml
title Low-level M2 Library Example

skinparam object {
    BackgroundColor<<Node>> LightGreen
    BackgroundColor<<ReferenceTarget>> LightSkyBlue
}
skinparam object {
    BackgroundColor<<PropertyValue>> LightPink
    BackgroundColor<<ChildTarget>> LightBlue
}

package meta {
    object "Metamodel" as metamodel

    object "qualifiedName" as qualifiedName
    metamodel *-- qualifiedName

    object "elements" as elements
    metamodel *-- elements

    object "Concept" as concept

    object "simpleName" as simpleName
    concept *-- simpleName

    object "abstract" as abstract
    concept *-- abstract

    object "features" as features
    concept *-- features

    object "extends" as extends
    concept *-- extends

    object "PrimitiveType" as primitiveType
    primitiveType *-- simpleName

    object "Property" as property
    property *-- simpleName

    object "optional" as optional
    property *-- optional

    object "propertyType" as propertyType
    property *-- propertyType

    object "Reference" as reference
    reference *-- simpleName
    reference *-- optional

    object "multiple" as multiple
    reference *-- multiple

    object "linkType" as linkType
    reference *-- linkType

    object "Containment" as containment
    containment *-- simpleName
    containment *-- optional
    containment *-- multiple
    containment *-- linkType
}

' library (metamodel)

object "<<Node>> library" as library {
    id = "idLibMm"
    concept = → Metamodel
}
'metamodel <- library #lightgray: concept


map "<<PropertyValue>>" as libraryQualifiedName {
    → qualifiedName => "library"
}
library *-- libraryQualifiedName: properties
'qualifiedName <- libraryQualifiedName #lightgray: property

map "<<ChildTarget>>" as libraryChildren {
    elements => → elements
}
library *-- libraryChildren: children
'elements <- libraryString #lightgray: containment

' String

object "<<Node>> String" as String {
    id = "idString"
    concept = → PrimitiveType
}
'primitiveType <- String #lightgray: concept

libraryChildren::elements --> String: target

map "<<PropertyValue>>" as StringName {
    → simpleName => "String"
}
String *-- StringName: properties
'simpleName <- StringName #lightgray: property

' Boolean

object "<<Node>> Boolean" as Boolean {
    id = "idBoolean"
    concept = → PrimitiveType
}
'primitiveType <- Boolean #lightgray: concept

libraryChildren::elements --> Boolean: target

map "<<PropertyValue>>" as BooleanName {
    → simpleName => "Boolean"
}
Boolean *-- BooleanName: properties
'simpleName <- BooleanName #lightgray: property

' Integer

object "<<Node>> Integer" as Integer {
    id = "idInteger"
    concept = → PrimitiveType
}
'primitiveType <- Integer #lightgray: concept

libraryChildren::elements --> Integer: target

map "<<PropertyValue>>" as IntegerName {
    → simpleName => "Integer"
}
Integer *-- IntegerName: properties
'simpleName <- IntegerName #lightgray: property

' Book

object "<<Node>> Book" as Book {
    id = "idBook"
    concept = → Concept
}
'concept <- Book #lightgray: concept

libraryChildren::elements --> Book: target

map "<<PropertyValue>>" as bookName {
    → simpleName => "Book"
    → abstract => "false"
}
Book *-- bookName: properties

' Book.title

object "<<Node>> title" as title {
    id = "idTitle"
    concept = → Property
}
'property <- title #lightgray: concept

map "<<ChildTarget>>" as bookChildren {
     features => → features
}
Book *-- bookChildren: children
bookChildren::features --> title: target

map "<<PropertyValue>>" as titleName {
    → simpleName => "title"
    → optional => "false"
}
title *-- titleName: properties
'simpleName <- titleName #lightgray: property

object "<<ReferenceTarget>>" as titleType {
    resolveInfo = "String"
    reference = → propertyType
}
title *-- titleType: references
'propertyType <- titleType #lightgray: reference
titleType -> String: target

' Book.pages

object "<<Node>> pages" as pages {
    id = "idPages"
    concept = → Property
}
'property <- pages #lightgray: concept

bookChildren::features --> pages: target

map "<<PropertyValue>>" as pagesName {
    → SimpleName => "pages"
    → optional => "false"
}
pages *-- pagesName: properties
'simpleName <- pagesName #lightgray: property

object "<<ReferenceTarget>>" as pagesType {
    resolveInfo = "Integer"
    reference = → propertyType
}
pages *-- pagesType: references
'propertyType <- pagesType #lightgray: reference
pagesType -> Integer: target

' Book.author

object "<<Node>> author" as author {
    id = "idAuthor"
    concept = → Reference
}
'reference <- author #lightgray: concept

bookChildren::features --> author: target

map "<<PropertyValue>>" as authorName {
    → simpleName => "author"
    → optional => "false"
    → multiple => "false"
}
author *-- authorName: properties
'simpleName <- authorName #lightgray: property


object "<<ReferenceTarget>>" as authorType {
    resolveInfo = "Writer"
    reference = → linkType
}
author *-- authorType: references
'linkType <- authorType #lightgray: reference


' Library (node)

object "<<Node>> Library" as Library {
    id = "idLibrary"
    concept = → Concept
}
'concept <- Library #lightgray: concept

libraryChildren::elements --> Library: target

map "<<PropertyValue>>" as libraryName {
    → simpleName => "Library"
    → abstract => "false"

}
Library *-- libraryName: properties
'simpleName <- libraryName #lightgray: property

' Library.name

object "<<Node>> name" as libraryNameNode {
    id = "idLibraryName"
    concept = → Property
}
'property <- libraryNameNode #lightgray: concept

map "<<ChildTarget>>" as LibraryNodeChildren {
     features => → features
}
Library *-- LibraryNodeChildren: children
LibraryNodeChildren::features --> libraryNameNode: target

map "<<PropertyValue>>" as libraryNameName {
    → simpleName =>  "name"
    → optional => "false"
}
libraryNameNode *-- libraryNameName: properties
'simpleName <- libraryNameName #lightgray: property

object "<<ReferenceTarget>>" as libraryNameNodeType {
    resolveInfo = "String"
    reference = → propertyType
}
libraryNameNode *-- libraryNameNodeType: references
'propertyType <- libraryNameNodeType #lightgray: reference
libraryNameNodeType -> String: target

' Library.books

object "<<Node>> books" as books {
    id = "idLibraryBooks"
    concept = → Containment
}
'containment <- books #lightgray: concept

LibraryNodeChildren::features --> books: target


map "<<PropertyValue>>" as booksName {
    → simpleName => "books"
    → optional => "false"
    → multiple => "true"
}
books *-- booksName: properties
'simpleName <- booksName #lightgray: property

object "<<ReferenceTarget>>" as booksType {
    resolveInfo = "Book"
    reference = → linkType
}
books *-- booksType: references
'linkType <- booksType #lightgray: reference
booksType -> Book: target

' Writer

object "<<Node>> Writer" as Writer {
    id = "idWriter"
    concept = → Concept
}
'concept <- Writer #lightgray: concept


libraryChildren::elements --> Writer: target
authorType -> Writer: target

map "<<PropertyValue>>" as Writer_Name {
    → simpleName => "Writer"
    → abstract => "false"
}
Writer *-- Writer_Name: properties
'simpleName <- Writer_Name #lightgray: property

' Writer.name

object "<<Node>> name" as writerName {
    id = "idWriterName"
    concept = → Property
}
'property <- writerName #lightgray: concept

map "<<ChildTarget>>" as WriterChildren {
     features => → features
}
Writer *-- WriterChildren: children
WriterChildren::features --> writerName: target

map "<<PropertyValue>>" as writerNameName {
    → simpleName => "name"
    → optional => "false"
}
writerName *-- writerNameName: properties
'simpleName <- writerNameName #lightgray: property

object "<<ReferenceTarget>>" as writerNameType {
    resolveInfo = "String"
    reference = → propertyType
}
writerName *-- writerNameType: references
'propertyType <- writerNameType #lightgray: reference
writerNameType -> String: target

' GuideBookWriter

object "<<Node>> GuideBookWriter" as GuideBookWriter {
    id = "idGuideBookWriter"
    concept = → Concept
}
'concept <- GuideBookWriter #lightgray: concept

libraryChildren::elements --> GuideBookWriter: target

map "<<PropertyValue>>" as GuideBookWriterName {
    → simpleName => "GuideBookWriter"
    → abstract => "false"
}
GuideBookWriter *-- GuideBookWriterName: properties
'simpleName <- GuideBookWriterName #lightgray: property

object "<<ReferenceTarget>>" as GuideBookWriterExtends {
    resolveInfo = "Writer"
    reference = → extends
}
GuideBookWriter *-- GuideBookWriterExtends: references
'extends <- GuideBookWriterExtends #lightgray: reference
GuideBookWriterExtends -> Writer: target

' GuideBookWriter.countries

object "<<Node>> countries" as countries {
    id = "idGuideBookWriterCountries"
    concept = → Property
}
'simpleName <- countries #lightgray: property

map "<<ChildTarget>>" as GuideBookWriterChildren {
     features => → features
}
GuideBookWriter *-- GuideBookWriterChildren: children
GuideBookWriterChildren::features --> countries: target

map "<<PropertyValue>>" as countriesName {
    → simpleName => "countries"
    → optional => "false"
}
countries *-- countriesName: properties
'simpleName <- countriesName #lightgray: property

object "<<ReferenceTarget>>" as countriesType {
    resolveInfo = "String"
    reference = → propertyType
}
countries *-- countriesType: references
'propertyType <- countriesType #lightgray: reference
countriesType -> String: target

' SpecialistBookWriter

object "<<Node>> SpecialistBookWriter" as SpecialistBookWriter {
    id = "idSpecialistBookWriter"
    concept = → Concept
}
'concept <- SpecialistBookWriter #lightgray: concept

libraryChildren::elements --> SpecialistBookWriter: target

map "<<PropertyValue>>" as SpecialistBookWriterName {
    → simpleName => "SpecialistBookWriter"
    → abstract => "false"
}
SpecialistBookWriter *-- SpecialistBookWriterName: properties
'simpleName <- SpecialistBookWriterName #lightgray: property

object "<<ReferenceTarget>>" as SpecialistBookWriterExtends {
    resolveInfo = "Writer"
    reference = → extends
}
SpecialistBookWriter *-- SpecialistBookWriterExtends: references
'extends <- SpecialistBookWriterExtends #lightgray: reference
SpecialistBookWriterExtends -> Writer: target

' SpecialistBookWriter.subject

object "<<Node>> subject" as subject {
    id = "idSpecialistBookWriterSubject"
    concept = → Property
}
'simpleName <- subject #lightgray: property

map "<<ChildTarget>>" as SpecialistBookWriterChildren {
     features => → features
}
SpecialistBookWriter *-- SpecialistBookWriterChildren: children
SpecialistBookWriterChildren::features --> subject: target

map "<<PropertyValue>>" as subjectName {
    → simpleName => "subject"
    → optional => "false"
}
subject *-- subjectName: properties
'simpleName <- subjectName #lightgray: property

object "<<ReferenceTarget>>" as subjectType {
    resolveInfo = "String"
    reference = → propertyType
}
subject *-- subjectType: references
'propertyType <- subjectType #lightgray: reference
subjectType -> String: target

@enduml
