[[evnt-AnnotationReplaced]]
===== Annotation replaced
<<existing-nodes, Existing node>> <<AnnotationReplaced.replacedAnnotation>>, and all its <<AnnotationReplaced.replacedDescendants>>{fn-org370}, inside <<AnnotationReplaced.parent>>'s annotations at <<AnnotationReplaced.index>> has been replaced with <<new-nodes, new>> or <<reused-nodes, reused>> node <<AnnotationReplaced.newAnnotation>>.

<<AnnotationReplaced.replacedAnnotation>>, and all its descendants, have been deleted.

See also <<splittableMessage>>.

.Technical name
`AnnotationReplaced`

[horizontal]
.Parameters
[[AnnotationReplaced.newAnnotation, `newAnnotation`]]newAnnotation:: <<singleChunkType>>
Subtree that formed the new annotation.
The _anchor node_ MUST contain the <<AnnotationReplaced.parent>> as _parent_.{fn-org357}
All nodes in that subtree MUST either be <<new-nodes>> or <<reused-nodes>>.{fn-org326}

[[AnnotationReplaced.replacedAnnotation, `replacedAnnotation`]]replacedAnnotation:: <<nodeIdType>>
of the node that was replaced in annotations of <<AnnotationReplaced.parent>> at <<AnnotationReplaced.index>>.

[[AnnotationReplaced.replacedDescendants, `replacedDescendants`]]replacedDescendants:: <<nodeIdType>>[]
List of all node ids that used to be descendants (including children and annotations) of <<AnnotationReplaced.replacedAnnotation>>.
Does not include <<AnnotationReplaced.replacedAnnotation>>.

[[AnnotationReplaced.parent, `parent`]]parent:: <<nodeIdType>>
of the node an annotation was replaced in.

[[AnnotationReplaced.index, `index`]]index:: <<indexType>>
where <<AnnotationReplaced.replacedAnnotation>> was replaced in annotations of <<AnnotationReplaced.parent>>.

[[AnnotationReplaced.split, `split`]]split?:: <<splitFlagType>>
Whether <<AnnotationReplaced.newAnnotation>> is complete within this message.

[[AnnotationReplaced.originCommands]]originCommands:: <<commandSourceType>>[]
List of `(participationId, commandId)` pairs this event is based on.

[[AnnotationReplaced.sequenceNumber]]sequenceNumber:: <<eventSequenceType>>
Event sequence number of this event.

[[AnnotationReplaced.additionalInfos]]additionalInfos:: <<additionalInfosType>>
Optionally empty list of <<additionalInfo>>s.

.Related command
<<cmd-ReplaceAnnotation>>
