[[cmd-ReplaceAnnotation]]
===== Replace annotation
Delete <<existing-nodes, current node>> <<ReplaceAnnotation.replacedAnnotation>>{fn-org371} at <<ReplaceAnnotation.parent>>'s annotations at <<ReplaceAnnotation.index>>, and all its descendants (including annotation instances).
Does NOT change references to any of the deleted nodes.{fn-org285}

Replace <<existing-nodes, existing node>> <<ReplaceAnnotation.replacedAnnotation>> inside <<ReplaceAnnotation.parent>>'s annotations at <<ReplaceAnnotation.index>> with <<new-nodes, new>> or <<reused-nodes, reused>> node <<ReplaceAnnotation.newAnnotation>>.

See also <<splittableMessage>>.

[cols="a,a"]
|===
|Before |After

include::ReplaceAnnotation-diagram.adoc[]
|===

.Technical name
`ReplaceAnnotation`

[horizontal]
.Parameters
[[ReplaceAnnotation.newAnnotation, `newAnnotation`]]newAnnotation:: <<singleChunkType>>
Subtree to form a new annotation that replaces <<ReplaceAnnotation.replacedAnnotation>>.
The _anchor node_ MUST contain the <<ReplaceAnnotation.parent>> as _parent_.{fn-org357}
All nodes in that subtree MUST either be <<new-nodes>> or <<reused-nodes>>.

[[ReplaceAnnotation.parent, `parent`]]parent:: <<nodeIdType>>
of the node we want to replace an annotation in.

[[ReplaceAnnotation.index, `index`]]index:: <<indexType>>
where we want to replace <<ReplaceAnnotation.replacedAnnotation>> at in annotations of <<ReplaceAnnotation.parent>>.

[[ReplaceAnnotation.replacedAnnotation, `replacedAnnotation`]]replacedAnnotation:: <<nodeIdType>>
of the node we want to replace in annotations of <<ReplaceAnnotation.parent>> at <<ReplaceAnnotation.index>>.

[[ReplaceAnnotation.split, `split`]]split?:: <<splitFlagType>>
Whether <<ReplaceAnnotation.newAnnotation>> is complete within this message.

[[ReplaceAnnotation.commandId]]commandId:: <<commandIdType>>
Id of this command.

[[ReplaceAnnotation.additionalInfos]]additionalInfos:: <<additionalInfosType>>
Optionally empty list of <<additionalInfo>>s.

.Errors
* <<err-unknownNode>> for <<ReplaceAnnotation.parent>>
* <<err-unknownNode>> for <<ReplaceAnnotation.replacedAnnotation>>
* <<err-invalidAnchorNode>> for <<ReplaceAnnotation.newAnnotation>>
* <<err-nodeAlreadyExists>> for <<ReplaceAnnotation.newAnnotation>>
* <<err-parentContainmentMismatch>> for <<ReplaceAnnotation.newAnnotation>>
* <<err-circularContainment>> for <<ReplaceAnnotation.newAnnotation>>
* <<err-unknownIndex>> for <<ReplaceAnnotation.index>> (is beyond (the number of annotations of <<ReplaceAnnotation.parent>>) - 1)
* <<err-indexEntryMismatch>> for <<ReplaceAnnotation.index>> and <<ReplaceAnnotation.replacedAnnotation>>
* <<err-invalidParticipation>>

.Related event
<<evnt-AnnotationReplaced>>
