include::../shared/issue-footnotes.adoc[]
:serialization: ../serialization/serialization
:m3: ../metametamodel/metametamodel
:refarch: ../reference-architecture/reference-architecture
:roadmap: ../roadmap/roadmap
= Anatomy of a LionWeb Model
:toc: preamble
:toclevels: 3
:sectnums:

This article walks us through a LionWeb model:
What it is, what's inside, how the inside looks, what the contents mean, and why they are that way.
It is meant as introduction to some of the details of LionWeb.
We don't assume any prior knowledge of LionWeb; some experience with general modeling ideas is helpful.

== Introduction
The fundamental world view in LionWeb is "everything is a model".
This means we express everything we talk about in this context in the form of models.

But what is a model?
STOP -- don't run away!
This question is infamous in the modeling community -- but we have to answer it given our world view as stated above.
We deliberately don't use that term in our specifications, as it's so overloaded and ambiguous.
For our purposes, we can always replace "model" with "a bunch of nodes".
Then the question transforms to: What is a node?

[[nodes]]
== Nodes
A node is the fundamental building block in LionWeb.
It consists of a unique identifier (**id**), a **classifier** to define the nature / type / class of the node, the node's **parent** node and lists of **properties**, **containments**, **references**, and **annotation instances**, respectively.
We group a node's properties, containments, and references as the **features** of that node.

Properties are simple values like `name: String`, `age: Integer` or `alive: Boolean`.
Containments are other nodes that this node is composed of; examples would be `mainEntrance: Door[1]` or `corners: Coordinate[0..\*]`.
References are other nodes that this node relates to; examples would be `surface: Material[1]` or `stakeholders: Employee[1..*]`.
Annotation instances are other nodes that represent orthogonal concerns of this node; examples include `ParsedFromLine` or `ReviewComment`.

Let's look into each of these in more detail.

[[node-id]]
=== Node id
The id of a node is a string of arbitrary length, consisting of characters `A`-`Z`, `a`-`z`, `0`-`9`, dash `-` and underscore `_`.
It cannot be empty, and it must be unique for all nodes in the model.

The valid character set coincides to the output of _base64url_-encoding.
This comes very handy if we had to derive the node id from some other source, like a binary hash, or fully qualified name.

We chose this character set, as it should be compatible with any run-time environment, and avoid any encoding issues.
We don't limit the id's length, so any kind of other source can be represented -- fully qualified names tend to get very long, for example.

We assume nodes with equal id string to be identical.
Something went wrong if we had e.g. two different Java objects of class `Node`, but with equal `nodeId` field.

Node ids should NOT carry any meaning:
Only because a node id happens to contain the string `frontLeftWheel`, we should NOT assume its classifier might be `Wheel`, or its containment might be `frontLeft`.
These "descriptive" node ids are quite useful to read examples or in tests, as they provide more context.
However, examples and tests are for human consumption -- real nodes (in their raw form) are not.

[[meta-pointer]]
=== Meta-pointer
Before we get to the next part of a node, classifier, we need to discuss _meta-pointers_.
Any time we refer from an instance model (M1) to its meta-model (M2 a.k.a. _Language_), we use meta-pointers.
They are a triple of {_language key_, _language version_, _element key_}, for example `{language=MyLanguage, version=23-alpha, key=MyConcept}`.
Both language key and element key use the same character set as <<node-id, node ids>>, whereas language version can be any non-empty string.

We need this triple, because a language can be uniquely identified by its key and version, and the element key must be unique within its language.
With language version we support _language evolution_, i.e. the fact that real-world languages tend to change over time.

We don't prescribe anything about language version, as different implementations might use different ways to represent language evolution.
We just assume that equal strings refer to the identical version.

=== Node classifier
A node's classifier is a <<meta-pointer>> that defines the node's nature, or type or class -- "what kind of thing is this node?"
A classifier of a node is equivalent to the class of a Java object.
The classifier can either be a _concrete concept_ or an _annotation_. It cannot be an _abstract concept_ or _interface_, as we cannot instantiate them.

A node must adhere to its classifier.
This means the node can only have features as described in the node's classifier.
footnote:[At least by default; we might deviate from that constraint under special circumstances, like migrations.]

[[parent]]
=== Node parent
The parent of node `A` is the node `B` that contains `A`.
For example, node `10` of classifier `Car` might contain node `5` of classifier `PetrolEngine`, and node `11` of classifier `SteeringWheel`.
Thus, the parent of `5` is `10`, and the parent of `11` is also `10`.

[plantuml, carParent, svg]
----
hide empty members
class car as "10:Car"

class engine as "5:PetrolEngine"

class steering as "11:SteeringWheel"

car *-- engine
car *-- steering
----

Every node MUST have exactly one parent -- except for root nodes.
This implies that, starting from a root node, we can order all nodes in _tree shape_.

The opposite of a node's parent are a node's _children_.
In the example above, node `10` has children `5` and `11`; node `5` does not have any children.

A node's classifier defines which kind of children a node can have -- the node's <<containment, containments>>.
In our example, node `5` might be contained in `engine`, and node `11` in `steering`.

[plantuml, carContainments, svg]
----
hide empty members
class car as "10:Car"

class engine as "5:PetrolEngine"

class steering as "11:SteeringWheel"

car *-- engine: engine
car *-- steering: steering
----

Additionally, a node can have <<annotation, annotation instances>>.
Let's add a node `22` of annotation `DiagramPosition` to our `10:Car`, and node `33` of annotation `ReviewComment` to `11:SteeringWheel`.
Thus, the parent of `22` is `10`, and the parent of `33` is `11`.
We also call this the _annotated node_: node `10` has annotation `22`, and node `22` has annotated node `10`.


[plantuml, carAnnotations, svg]
----
hide empty members
class car as "10:Car"

class engine as "5:PetrolEngine"

class steering as "11:SteeringWheel"

car *-- engine: engine
car *-- steering: steering

annotation pos as "22:DiagramPosition"

car *- pos: <<annotation>>

annotation review as "33:ReviewComment"

steering *- review: <<annotation>>

engine -[hidden]> steering
----

In summary, a node's parent must always be symmetric -- either to the parent's children, or the parent's annotation instances.

If we deleted the parent node, we implicitly delete all its children and annotation instances, each of their children and annotation instances, and so on.
In other words, a child or annotation instance shares the lifetime of its parent.

This also explains why we consider the annotated node the parent of an annotation instance:
If the annotated node is gone, the annotation instance makes no sense anymore -- they share the annotated node's lifetime.

[[properties]]
=== Properties

We use properties to store simple values inside a node.
A node of classifier `Person` might have properties `name: String`, `age: Integer` and `alive: Boolean`.

[plantuml, personProperties, svg]
----
hide empty members
class person as "3:Person" {
  name: String = "Joe"
  age: Integer = 23
  alive: Boolean = true
}
----

A node's classifier describes which properties can appear in the node.
This description includes the property's _name_, _key_, whether it is _optional_, and its _type_.
The name is for humans to understand the property; we use the key to uniquely identify it technically.
With the optional flag we specify whether a node without this property is considered valid or not:
In our system, a `person` without known `name` might be a problem, but we could still process them without knowing their `age`.

A property's type describes what kind of values can appear in that property.
All LionWeb data types, and thus all properties, are _value typesfootnote:[https://en.wikipedia.org/w/index.php?title=Value_type]_.
This means they don't have any identity, we just know their value: We can distinguish `10` and `15`, but `12` and `12` are the same.

Some modeling frameworks allow properties with multiple values, e.g. `luckyNumbers: Integer[0..*] = {23, 42, 4711}`.
LionWeb does not support that, because the values don't have identity.
So if we first had a property value of `{23, 42}`, and then `{23, 42, 42}`, we have no way of telling whether the new `42` has been inserted or appended.
This leads to all kinds of problems we'd like to avoid.

The following subsections describe the kinds of data types supported by LionWeb.

==== Primitive types
LionWeb ships with built-in types for `String`, `Integer`, and `Boolean`, as they are needed in almost all systems.
String properties can have any string value, including empty.
Integer properties support positive and negative decimal integers of any length.
Boolean properties can only have the values `true` or `false`.
A language might define its own additional _primitive types_.
In any case, we store all of them as string on low-level serialization format (i.e. JSON).

==== Enumerations
A property can also be of an _enumeration_ type.
Enumerations have a _name_, _key_, and a list of _enumeration literals_.
Again, name is for human understanding, and key for unambiguous technical reference.
Each literal also has a _name_ and a _key_, with the same purpose.
A language must explicitly declare an enumeration to use it as the type of a property.
Enumeration properties must have one of the enumeration literal values.
On low-level serialization, we store the value as the enumeration literal's key.

[plantuml, personEnum, svg]
----
hide empty members

enum status as "CivilStatus [key=cs]"
{
  single [key=s]
  married [key=m]
  divorced [key=d]
  widowed [key=w]
}
----

==== Structured data types
LionWeb supports another kind of simple type: _structured data type_ (added in LionWeb version 2024.1).
They are a collection of other primitive types, called _fields_.
Both the structured data type and each field has a _name_ and _key_ with the usual meaning.

[plantuml, sdtColor, svg]
----
json "TextPosition [key=tp]" as tp {
  "line [key=lin]": "Integer",
  "column [key=col]": "Integer"
}

json "TextRange [key=tr]" as tr {
  "start [key=st]": "TextPosition",
  "end [key=en]": "TextPosition",
  "label [key=la]": "String",
  "valid [key=va]": "Boolean"
}
----

We store the value of a structured data type as string, the same as all other primitive types.
The content of that string is an escaped JSON structure.
As example, the value of above's `TextPosition` would be `"{\"lin\": \"42\", \"col\": \"-30\"}"`.
Refer to <<{serialization}.adoc#structured-datatype, serialization specs>> for details.

[[containments]]
=== Containments

A node `A` can contain other nodes `B` and `C`.
Then `B` has the <<parent, parent>> `A`; `A` has _children_ `B` and `C`.
If `C` contains `D`, then `D` has the _ancestors_ `C` and `A`; `A` has the _descendants_ `B`, `C`, and `D`.

[plantuml, axis, svg]
----
hide empty members
hide circles

class A
class B
class C
class D

A *-- B
A *-- C
C *-- D
----

Every node (except root nodes) must have exactly one parent, thus no node can be contained more than once.
Containments establish a _tree shape_ of the model (sometimes called _primary containment tree_ or _dominator tree_).
A node can never contain itself, neither directly nor indirectly.

We use containments if the contained node only makes sense together with its parent -- a `Coordinate` is not very useful if we don't know which shape it belongs to.
We also identify different containments -- for a `Rectangle`, we want to know whether a contained `Coordinate` is `topLeft` or `lowerRight`.

[plantuml, rectangle, svg]
----
hide empty members

class Rectangle

class Coordinate

Rectangle *-- Coordinate: topLeft
Rectangle *-- Coordinate: lowerRight
----

A node's classifier describes the valid containments.
This description includes the containment’s _name_, _key_, whether it is _optional_, whether we allow _multiple_ nodes in the containment, and its _type_.
Name, key and optional mean the same for containments and <<properties, properties>>.
A singular containment allows only one contained node, e.g. a `Rectangle` can contain only one `topLeft` coordinate.
In contrast, a `House` can contain multiple ``Room``s.
For multiple containments, we keep track which child is contained at which position.
As every contained node can have only one parent, we cannot have duplicates in multiple containments.

[plantuml, house, svg]
----
hide empty members
class b as "2:House"

class a as "33:Address" {
  street: String = "Main Street",
  zipCode: String = "12345"
}

class c1 as "23:Room" {
  title: String = "Hallway"
}

class c2 as "1:Bedroom" {
  title: String = "Master bedroom"
}

class c3 as "122:Bedroom" {
  title: String = "Guest room"
}

b *- a: address

b *-- c1: rooms [0]
b *-- c2: rooms [1]
b *-- c3: rooms [2]

----

A containment's type refers to a classifier, and describes which nodes can be part of that containment.
Only nodes that have a compatible classifier can be part of that containment.

On serialization level, we store the contained node's id for a containment.
A containment is invalid if the contained node's id cannot be resolved.

[[references]]
=== References

A node can point to other nodes it has some relation to.
For example, a `Project` might refer to its `mainResponsible: Employee`, or to all its `externalParties: BusinessPartner`.
The node containing the reference is called _source_, the referred node _target_ of the reference.
A node can be referenced by none, one, or many other nodes.
It can be referenced by itself.
A node can reference another node more than once.

[plantuml, project, svg]
----
hide empty members

class pr as "6:Project" {
  description: String = "Settle beyond this galaxy"
}

class coop as "9:TemporaryEmployee" {
  name: String = "Cooper"
}

class esa as "87:BusinessPartner" {
  title: String = "ESA"
  budget: Integer = 23
}

class jaxa as "40:BusinessPartner" {
  title: String = "JAXA"
  budget: Integer = 42
}

pr ..> esa: externalParties [0]
pr ..> jaxa: externalParties [1]

pr .> coop: mainResponsible

class pr2 as "90:Project" {
  description: String = "Grow corn"
}

coop <. pr2: mainResponsible
----

A node's classifier describes the valid references.
This description includes the references’ _name_, _key_, whether it is _optional_, whether we allow _multiple_ targets in the reference, and its _type_.
All of them mean the same as for <<containments, containments>>, respectively.
For multiple references, we keep track which target is listed at which position.
The same target can appear several times in a multiple reference.
This can help, for example, to describe steps: `steps: Task[1..*] = {generate, saveAll, compile, saveAll}` refers to Task `saveAll` twice.

LionWeb does not support bi-directional references.
They are very hard to maintain, and also hard to process (i.e. if we want to traverse the whole model).

==== ResolveInfo
For references, we store the target node's id, and additionally a `resolveInfo`.
ResolveInfo is a string that somehow describes the target node.
Typical candidate would be the target's node `name` (if the target node has such a property).
To support this typical default behavior, LionWeb has a built-in interface `INamed` with one property `name: String` that might be implemented by any classifier.
However, it's up to the application to select and set the appropriate resolveInfo.

This serves two purposes:

* In the space project example above, assume some app that displays the list of external parties for the project as `ESA: 23, JAXA: 42`.
Now someone thinks there's no project left with ESA, and deletes node 87 (the ESA one).
If the `externalParties [0]` reference only knew the target node id, the best possible display would be `!unknown target 87!, JAXA: 42` -- not very helpful to the user.
With resolveInfo, we can display `!unknown target ESA!, JAXA: 42`.
Now the user has a much better chance of tracking down the error.

* We need to know the target node id in order to store it in a reference.
But in parser-based systems, after parsing we know only some kind of identifier of a reference target.
We might want to store this unresolved _abstract syntax tree_ (AST).
A later linking step hopefully finds the actual target and fills in the proper target node id.

Target node id, resolveInfo, or both must be set for each reference -- otherwise the reference is pointless.

==== Unresolved references
Assume a node `T` that happens to be the target of a reference `myRef` from node `A`.
When we delete `T`, the reference stays untouched: `A` still contains a reference `myRef` with target node id `T` (and maybe some resolveInfo), but the target cannot be resolved.
LionWeb allows references with unresolvable target.

[plantuml, deadRef, svg]
----
hide empty members
hide circles

skinparam package {
  borderColor Transparent
  backgroundColor Transparent
}

skinparam class<<h>> {
  borderColor Transparent
  backgroundColor Transparent
  stereotypeFontColor Transparent
}

package before {
  class A
  class T
  A .> T: myRef
}

package "after deleting T" {
  class A
  class T<<h>>
  A .> T: myRef
}
----

=== Differences between containment and reference

A contained node shares the lifetime of its parent -- if the parent is deleted, the contained node gets deleted, too.
The contained node makes no sense without its parent.
In contrast, the target of a reference is perfectly valid without the source.
They can be deleted independently.

Containments form a model into tree shape.
With references, we turn that tree into a graph, as a node can be target of several references.

[plantuml, graph, svg]
----
hide empty members
hide circles

together {
  class A
  class E
}

together {
  class B
  class C
}

class D

A *-- B
A *-- C
B *-- D

A <.. D
E <. D
C .> C
B ..> E
----

For containments, the parent node only stores the child node's id.
For references, the source node stores the target node's id and/or resolveInfo.

LionWeb does not support unresolvable containments, but unresolvable references are allowed.

[[annotations]]
=== Annotation instances
Annotation instances are mostly regular nodes, with two exceptions:
Their classifier must be an annotation, it cannot be a concept.
Also, the annotation instance must be mentioned in its parent's annotation instance list, it cannot be mentioned in the parent's containments.
Both these criteria are indirect; thus, when only looking at a node (without examining its classifier or parent), we cannot distinguish annotation instances from other nodes.
That's by design: _everything_ is a node, remember?

An annotation instance can have any kind and amount of properties, containments, references, and other annotation instances.
We can use annotation instances as reference target.

Assuming node `X` mentions node `Y` in ``X``'s annotation instances, we say `X` is _annotated by_ `Y`, and `Y` has _annotated node_ `Y`.
``Y``'s annotated node is always also ``Y``'s parent node.

[plantuml, annotationInstance, svg]
----
hide empty members

class X
annotation Y

X -[#transparent]> Y: < parent
X -[#transparent]> Y: < annotated node
X -[#transparent]> Y: > annotated by <U+00a0><U+00a0><U+00a0>
X *- Y: > <<annotations>>
----

Annotation instances share the lifecycle of their annotated node; when we delete the annotated node, the annotation instance gets also deleted.

==== Applicable classifiers
The classifier of an annotation instance must be an annotation.
Annotations are similar to concepts, and both are classifiers.
But an annotation specifies which other classifier it _annotates_.
The instance of that annotation must adhere to this constraint.

As example, assume we have classifiers `Function` and `Argument`.
We also have an annotation `SourcePosition` that `annotates = Function`.
On M1, we have node `1` of `Function`, and node `3` of `Argument`.
With node `34`, we have an annotation instance of `SourcePosition`.
Node `1:Function` can be _annotated by_ node `34:SourcePosition`, because `SourcePosition` states it _annotates_ `Function`.
In contrast, node `3:Argument` cannot be _annotated by_ node `35:SourcePosition`, because `Argument` is not compatible with `Function` (the kind of classifier ``SourcePosition`` _annotates_).

[plantuml,annotation,svg]
----
hide empty members

package M2 <<Rectangle>> {
  class Function <<Classifier>> {
    name: String
  }

  class Argument <<Classifier>> {
  }
  Function *- "0..*" Argument: parameters

  annotation SourcePosition <<Annotation>> {
    line: Integer
    column: Integer
  }
  SourcePosition .> Function: annotates
}

package M1 <<Rectangle>> {
  class f1 as "1:Function" <<Node>> {
    name = "doIt"
  }

  class a1 as "3:Argument" <<Node>> {
    name = "action"
  }
  f1 *- a1: parameters

  annotation an1 as "34:SourcePosition" <<Node>> {
    line = 2
    column = 13
  }
  an1 -* f1: <<annotations>>

  annotation an2 as "35:SourcePosition" <<Node>>  #line:red {
    line = 2
    column = 18
  }
  a1 *- an2: <<annotations>>
}

M2 -[hidden]- M1

'Function <.. f1: <<classifier>>
'Argument <.. a1: <<classifier>>
'SourcePosition <.. an1: <<classifier>>
'SourcePosition <. an2: <<classifier>>

----

An annotation that is applicable to all concepts says it annotates `Node` from LionWeb's built-in library.
Annotations can _annotate_ other annotations; however, this approach introduces complexities and should be used with great caution.

#TODO:# Do we allow unresolvable annotations?

=== Differences between containment and annotation instance
Both a contained node `C` and an annotated node `A` share the lifecycle of their parent node `P`.
So what's the difference?

A containment must be described in the parent's node classifier.
If the parent is of classifier `House` with containments `rooms`, and `doors`, we cannot add a containment `windows` to the parent node.
The designer of classifier `House` made the choice that for their domain, a house should only care about rooms and doors, but not windows.
The designer might not have anticipated our use case of their domain.
But every user of that classifier relies on this structure of a house, so we must not mess with it.

An annotation instance cannot be mentioned in the parent's node classifier at all.
Instead, an annotation instance's classifier must be an annotation, which mentions the classifier it annotates.
Thus, the designer of the annotation decides which targets their annotation is applicable to.
So we can come up with an annotation `WindowAnnotation` that `annotates: House`, and attach instances to nodes of classifier `House`.
All these nodes still adhere to the intents of ``House``'s designer, but also transport the additional information about windows we need for our use case.

Even more importantly, we can put orthogonal concerns into annotation instances.
For the domain of `House`, we don't want to concern ourselves with the details how a parser constructed that node.
But it would be useful to show users where this node originated from in case of errors.
Not a problem with an annotation `ParserSource` that `annotates: Node` (i.e. any node).
Similarly, we could come up with an annotation `ReviewComment` to be used during code reviews.
The reviewer can attach instances to any node, without interfering with the original intent of these nodes.

Review comments demonstrate one drawback of annotations: we're violating the generally valued idea of _separating concerns_, as we mix domain concerns and process concerns in the same model.
The alternative would be to keep both concerns in separate concerns, and have the review comments reference the node they apply to.
Experience shows this approach is very hard to maintain:
What happens if we deleted a house, and there's still a review comment referring to it?
The review model might not be loaded during the deletion, so it now contains a "zombie" review comment.
We might need to introduce "garbage collection" strategies to find such zombies and deal with them.
For more context-sensitive annotations, moving the annotated node might introduce similar problems.

Annotations should not be used as replacement for proper concept design.
If our language concerned the domain of houses, review comments are completely independent of that domain, should not be part of it, and are perfect candidates for annotations.
However, if our language concerned modeling discussions, then reviews and comments are integral part of that domain, and should be represented by proper containments and (abstract) concepts in our language.
In this case, using annotations only because they seem conveniently applicable at lots of places is a strong modeling smell.

== Languages

plantuml::../metametamodel/metametamodel.puml[format=svg]


[appendix]
[[language-key]]
== Language key
We might ask, "What's the difference between a language id and its key? Everything is a node, thus a language is a node, so it must have a unique id -- that should be enough?!"

A language is indeed a node.
However, languages tend to be interchanged between different systems.
If we exported the language from system `A`, and imported it in system `B`, the node id assigned by `A` might already be taken in `B` -- so we need to assign a new one.
Later, we might transfer instances of that language from `A` to `B`.
The instances would use the language's original id in their meta-pointer.
So we had to store mapping tables from the language import, and apply them every time we import an instance -- not very appealing.

Another problem arose if we had a language in several versions.
Different versions of the same language are represented by different nodes -- otherwise they would not be different.
Then the same language in different versions would have different ids.
Let's assume the language contains three concepts, and only one of them changed from version 1 to 2.
We still must have new (albeit semantically identical) nodes for the other two concepts in version 2, as a concept cannot be part of two versions of a language.
Thus, all three concepts of version 2 must have different node ids from the corresponding concepts in version 1.
Then, if we migrated an instance of that language from version 1 to 2, we had to change _all_ meta-pointers -- again, not very appealing.

Having a key for both languages and all their elements solves all of these problems: The key stays the same in different systems, and through different versions.
