classDiagram

class Concept{
    Boolean abstract
}
FeaturesContainer <|-- Concept

class ConceptInterface
FeaturesContainer <|-- ConceptInterface

class Containment
Link <|-- Containment

class DataType
<<abstract>> DataType
MetamodelElement <|-- DataType

class Enumeration
DataType <|-- Enumeration
NamespaceProvider <|.. Enumeration

class EnumerationLiteral
NamespacedEntity <|-- EnumerationLiteral

class Feature {
    Boolean optional
}
<<abstract>> Feature
NamespacedEntity <|-- Feature

class FeaturesContainer {
    allFeatures() List~Feature~
}
<<abstract>> FeaturesContainer
MetamodelElement <|-- FeaturesContainer
NamespaceProvider <|.. FeaturesContainer

class Link {
    Boolean multiple
}
<<abstract>> Link
Feature <|-- Link

class Metamodel {
    String name
    Id id
}
NamespaceProvider <|.. Metamodel

class MetamodelElement
<<abstract>> MetamodelElement
NamespacedEntity <|-- MetamodelElement

class NamespacedEntity {
    String simpleName
    qualifiedName() String
    Id id
}
<<abstract>> NamespacedEntity

class NamespaceProvider {
    namespaceQualifier() String
}
<<interface>> NamespaceProvider

class PrimitiveType
DataType <|-- PrimitiveType

class Property
Feature <|-- Property

class Reference
Link <|-- Reference


%% relations:

Concept "*" --> "0..1" Concept: extends
Concept "*" --> "*" ConceptInterface: implements

ConceptInterface "*" --> "*" ConceptInterface: extends

EnumerationLiteral "*" --* "1" Enumeration : literals

Feature "*" --* "1" FeaturesContainer: features

Link "*" --> "1" FeaturesContainer: type

Metamodel "*" --> "*" Metamodel: dependsOn
MetamodelElement "*" --* "1" Metamodel: elements

Property "*" --> "1" DataType: type
