@startuml
hide empty members

class Annotation #orange extends FeaturesContainer  {
  platformSpecific: String?
}

class Concept #LightGreen extends FeaturesContainer {
  abstract: boolean
}

class ConceptInterface #LightGreen extends FeaturesContainer

class Containment #LightBlue extends Link

abstract class DataType #LightPink extends MetamodelElement

class Enumeration #LightPink extends DataType implements NamespaceProvider

class EnumerationLiteral #LightPink implements NamespacedEntity

abstract class Feature #LightBlue implements NamespacedEntity {
  <color:#orange>derived: boolean</color>
  optional: boolean
}

abstract class FeaturesContainer #LightGreen extends MetamodelElement implements NamespaceProvider {
  allFeatures(): List<Feature>
}

abstract class Link #LightBlue extends Feature {
  multiple: boolean
}

class Metamodel implements NamespaceProvider {
  qualifiedName: String
}

abstract class MetamodelElement implements NamespacedEntity

abstract class NamespacedEntity {
  simpleName: String
  qualifiedName(): String
}

interface NamespaceProvider {
  namespaceQualifier(): String
}

class PrimitiveType #LightPink extends DataType

class Property #LightBlue extends Feature

class Reference #LightBlue extends Link

class Typedef #orange extends DataType

' relations:

Annotation "*" --> "1" FeaturesContainer #orange;text:orange : target

Concept "*" -> "0..1" Concept: extends
Concept "*" --> "*" ConceptInterface: implements

ConceptInterface "*" --> "*" ConceptInterface: extends

Containment "*" -> "0..1" Containment #orange;text:orange : specializes

EnumerationLiteral "*" -* "1" Enumeration : literals

Feature "*" -* "1" FeaturesContainer: features

Link "*" --> "1" FeaturesContainer: type

Metamodel "*" --> "*" Metamodel: dependsOn
MetamodelElement "*" -* "1" Metamodel: elements

NamespacedEntity "*" --> "1" NamespaceProvider: container

Property "*" -> "1" DataType: type

Reference "*" -> "0..1" Reference #orange;text:orange : specializes

Typedef "*" -> "1" PrimitiveType #orange;text:orange : constraints

legend
  <#LightGray,#LightGray>| <#LightBlue>Feature |
  | <#LightGreen>Feature Container |
  | <#LightPink>DataType |
  | <#orange>Not agreed yet |
end legend
@enduml
