@startuml

' classes

class Metamodel  {
  qualifiedName: String
}

class Concept extends AbstractConcept {
  abstract: boolean
}

class ConceptInterface extends AbstractConcept

class PrimitiveType extends Datatype

class Annotation extends AbstractConcept  {
  platformSpecific: String?
}

class Containment extends Link

class Reference extends Link

class Property extends Feature

' Abstract classes

abstract class MetamodelElement

abstract class AbstractConcept extends MetamodelElement {
  allFeatures(): List<Feature>
}

abstract class Datatype extends MetamodelElement

abstract class Feature {
  multiplicity: Multiplicity
  calculated: boolean
}

abstract class Link extends Feature {
}

' Relations

Metamodel "1" o-- "*" MetamodelElement: elements
Metamodel "*" -- "*" Metamodel: dependsOn

Concept "0..1" -- "*" Concept: extends
Concept "*" -- "*" ConceptInterface: implements

ConceptInterface "*" -- "*" ConceptInterface: extends

Annotation "*" -- "1" AbstractConcept: target

Containment "1" -- "*" Containment: specializes

Reference "1" -- "*" Reference: specializes

Property "*" -- "1" Datatype: type

Link "*" -- "1" AbstractConcept: type

NamespacedEntity "*" -- "1" NamespaceProvider: container

FeaturesContainer "1" o-- "*" Feature: features

@enduml