@startuml
title Serialization Format

hide empty members

legend
    <#transparent,#transparent>|= Legend |= |
    | [key] / [value] | representation as JSON object |
end legend

class SerializationChunk {
    serializationFormatVersion: String
}

SerializationChunk *--> "0..*" UsedMetamodel: metamodels

class UsedMetamodel {
    key: Id
    version: String
}

SerializationChunk *--> "0..*" Node: nodes

class Node {
    id: Id
    parent: Id
}

Node *--> "1" MetaPointer: concept

class MetaPointer {
    metamodel: Id
    version: String
    key: Id
}

Node *--> "0..*" Children: children

class Children {
}

Children *--> "1" MetaPointer: containment

Children *--> "0..1" ChildTarget: children

class ChildTarget {
    target: Id
}

Node *--> "0..*" References: references

class References {
}

References *--> "1" MetaPointer: reference

References *--> "0..*" ReferenceTarget: targets

class ReferenceTarget {
    reference: Id
    resolveInfo: String
}

Node *--> "0..*" PropertyValue: properties

class PropertyValue {
    value: String
}

PropertyValue *--> "1" MetaPointer: property

@enduml